"""
Imported by `cpt_config.py` for use in the Tkinter GUI.

Variable:
    words_two (list): Single words for 10-25 second portion of typing test.
"""

# Two-word strings for 10-25 second portion of typing test.
words_two = ['to many', 'must press', "Yates's eldest", 'And yet', 'principally in',
             'Who took', 'saying that', 'would one', 'shortly afterwards',
             'suitable excuse', 'Street with', 'was so', 'curse I', 'have worked',
             'light of', 'Is so', 'over', 'Only beware', 'my pretty', 'he suddenly',
             'narrow cloister', 'that his', 'the machines', 'the sound', 'Should place',
             'of total', 'back one', 'of evils', 'resolution which', 'gives away',
             'were the', 'dear mrs', 'poor woman', 'brown belly', 'the stricken',
             'idea which', 'this morning', 'the lost', 'of course', 'and Literature',
             'gaping hole', 'salvation sure', 'was equally', 'nature like', 'and coma',
             'true gentleman', 'he cried', 'distantly to', 'lady markby', 'The words',
             'oaring pinions', 'matter in', 'under the', 'should in', 'that coffee',
             'quavering song', 'in them', 'or harwich', 'were quietly', 'and cried',
             'get up', 'of June', 'brought the', 'his lessons', 'to arouse', 'of girl',
             'a wonderful', 'a good', 'I wanted', 'her crew', 'explore the',
             'sister always', 'it may', 'flattering goods', 'You in', 'chest of',
             'head raised', 'to make', 'simply gorged', 'question was', 'a quare',
             'In one', 'rushed up', 'hope that', 'most successful',
             '‘Encyclopedia Britannica', 'is sinking', 'When the', 'been to', 'in peace',
             'fellow Brougham', 'this sheet', 'little specks', 'Then let', 'talk about',
             'long as', 'the talk', 'pointing to', 'extent of', 'When I', 'they worked',
             'most complete', 'taken the', 'performing every', 'exactness and',
             'of sending', 'nor fear', 'my baby', 'would receive', 'he found',
             'little cry', 'voluntarily undertake', 'state until', 'answered holmes',
             'high buskins', 'loud voice', 'rummaged and', 'modern factory', 'lively as',
             'a serious', 'get a', '& Kramer', 'Alexis de', 'they stepped', 'back was',
             'doing it', 'Albert chain', 'CHAPTER IV', 'removed it', 'the mental',
             'than that', 'lock and', 'considerable confusion):', 'my tea',
             'clearly been', 'followed was', 'the high', 'one of', 'thing that',
             'heaven that', 'except myself', 'and now', 'primordial Might', 'one whom',
             'pulled the', 'influence on', 'guys go', "Be pity's", 'foot', 'attempt to',
             'shadows were:', 'a great', 'of this', 'pluck have', "can't believe",
             'got a', 'the key', 'man that', 'thank you', 'tame Our', 'eating their',
             'in addition', 'burnt green', 'the doctor', "got 'em", 'streets and',
             'Of A', 'marry before', 'very picture', 'the evening', 'us nor', 'be calm',
             'have ever', 'Their breasts', 'violences of', 'While according', 'run riot',
             'almost invariably', 'him at', 'why did', 'As she', 'my lord',
             'bristling hair', 'of calico—then', 'thought he', 'determined him',
             'He really', 'he added', 'In travelling', 'who do', 'relation to',
             'he asked', 'he cleared', 'ask for', 'shabby-genteel place', 'the hearer',
             'All thought', 'elaborate almost', 'places again', 'of honour', 'want a',
             'he said', 'box which', 'the complicated', 'evidence is', 'in on',
             'ghostly women', 'the broad', 'by a', 'Whose husband', 'in its',
             'entrance hall', 'soon With', 'Gregor could', 'King of', 'Coburg Square',
             "irene's photograph", 'some tea', 'in his', 'influence in', 'of literary',
             'job and', 'no-one came', 'powers Of', 'immediate relation', 'we brewed',
             'seem to', 'prove That', 'Plunge we', 'the late', "takes George's",
             'and trained', 'so as', 'He got', 'From under', 'are like', 'Even though',
             'Like other', 'no one', 'much easier', 'my worst', 'one angle', 'time not',
             'gained on', 'which the', 'One difficulty', 'wooden boxes', "kiki don't",
             'moved so', 'peter hawkins', 'named may', 'and endeavored', 'feet tramping',
             'her with', 'still with', 'But Robert', 'he made', 'helping to',
             'minutes to', 'few days', 'their imperfections', 'his breakfast', 'give it',
             'if you', 'was take', 'If he', 'in disappointment', "nature's silence",
             'floor', 'I looked', 'looking towards', 'than his', 'replace the',
             'the face', 'to hunt', 'would have', 'the Soup', 'noise like',
             'obviously did', 'the tall', 'His eagerness', 'i answered', 'desire for',
             'long undiscovered', 'must depart', 'never eyes', 'and begins',
             'them anywhere', 'not invisible', 'brought me', 'thoughtful mind',
             'very clearly', 'as time', 'church of', 'informing him', 'impelling ships',
             'and british', 'or the', "don't think", 'suppose i', "can't even",
             'person named', 'little girl', 'never heard', 'really an', 'And it',
             'forgot that', 'she had', 'last week', 'the amount', 'of knitting',
             'my own', 'the cellar', 'is mr', 'in my', 'way: MY', 'brought I',
             'tell him', 'sister also', 'a Chinese', 'lord caversham', 'his protector',
             'the voice', 'what he', 'and Armor', 'The nature', 'perhaps mrs',
             'drive into', 'of gloom', 'word shall', 'and speak', 'opponents were',
             'so completely', 'colored', 'estimation by', 'The King', 'to life',
             'Crawled again', 'The horizon', 'one in', "lucy's father", 'Then I',
             'my new', 'my gog', 'or grieved', 'also proved', 'skill so', 'young lady',
             'local work', 'theatre you', 'except the', 'i asked', 'assemblage on',
             'only just', 'was found', 'quite sharp', 'the blast', "don't want",
             'therefore r', 'Applies the', 'Westhouse &', 'said there', 'not a', 'I was',
             'just have', 'talked to', 'nothing can', 'they was', 'go back', 'For such',
             'meadow lie', 'their follies', 'With that', 'to now', 'his sister',
             'a German', 'surrounded by', 'quiet tune', 'shall see', 'a mustache',
             'Holmes and', 'couch and', 'be done', 'profits realised', "ev'n now",
             'is said', 'came the', 'the little', 'down at', 'done the', 'your lordship',
             'old and', "dozzened an'", 'tear or', 'youth Had', 'had I', '26 may',
             'I do', 'He had', 'and servant', 'better the', 'United States', 'a fifth',
             'sounds rose', "ain't good", 'to is', 'his head', 'his transformation',
             '9 may', 'up a', 'monograph some', 'anybody bringing', 'simply became',
             'was the', 'little mystery', 'see it', 'difficult to', 'going on',
             'And what', 'write here', 'agent of', 'they call', 'But he', 'my lips',
             'lace manufacture', "Grete's face", 'is my', 'parts of', 'master of',
             'out in', 'the other', 'good-night again', 'On the', 'workmen to',
             'Robert Peel', 'And lay', 'side make', 'a light', 'many fathers',
             'degree uncommon', 'ask you', 'come the', '& co', 'for Hatherley',
             'wish to', 'Asking me', 'their personal', 'her I', 'such a',
             'possible explanation', 'courtyard far', 'had been', 'and cheer',
             'something would', 'in thick', 'shattered into', 'no trees',
             'whither bound', "don't walk", 'be anything', 'I must', 'soon became',
             'making of', 'to feel', 'Solomon the', 'i hope', 'erected by',
             'was already', 'expend the', 'with a', 'Conversation with', 'up forever',
             "who won't", 'you come', 'he could', '& Susan', 'his bedroom', 'a school',
             'against the', 'to leave', 'walk up', 'right away', 'the curse',
             'quoth one', 'be called', 'being applied', 'invites us', 'another burgher',
             'men will', 'no need', 'changed my', 'so necessary', 'made a', 'It was',
             'it on', 'boyars: ‘Welcome', 'the quires', 'see the', 'he rose',
             'the ominous', 'of reading', 'that lima', "o' them", 'perhaps accounts',
             'And there', 'set off', 'could not', 'see me', 'opposite my',
             'ferret-like man', 'things up', "I'm at", 'her eyebrows', 'the traces',
             'he answered', 'i forgot', 'a slightly', 'Might it', 'seems to',
             'shorthand all', 'and shoot', 'is cold', 'own to', 'to this', 'poor dear',
             'listen to', 'is master', 'charles mccarthy', 'was a', 'In silence',
             'tossed my', 'be patient', 'I went', 'well a-day', 'of visiting',
             'pardon me', 'over it', 'the crane', 'you need?', 'the Spirit',
             'chief clerk', "Nothin' but", 'but still', 'sneaks out', 'you she',
             'He could', 'with its', 'glowing day', 'or small', 'seven nights',
             'up again', 'have succeeded', 'master the', 'a sail', 'and oily', 'pie and',
             'his new', 'or rome', 'some hours', 'burdensome about', 'the last',
             'sturdy horses', 'the result', 'case I', "heaven's ray", 'And with',
             'alternate chime', 'Where his', 'ye murky', 'correct and', 'morning that',
             'more simple', 'of importance', 'as white', 'three years', 'the printed',
             'And the', 'your assistant', 'Which he', 'impulseit is', 'dust which',
             'the night', 'be too', 'cradled to', 'duty of', 'wrote to', 'he proceeded',
             'years after', 'said he', 'any more', 'having read', 'little bit',
             'a general', 'twenty years', 'very good', 'to fill', 'some hole', 'And I',
             "' ‘why", 'sinewy neck', 'me with', 'the moonlight', 'for instance',
             'babying voice', 'its occupant', 'In reel', 'changing the',
             'nothing compared', 'possible object', 'a thousand', 'should say',
             'Sun uprist:', 'From whose', 'maid had', 'thing I', 'We were',
             'acquiesced in', 'labour the', 'I may', "shan't i", 'a policeman',
             'you meddle', "gasfitters' ball", 'able to', 'seven days', 'Here we',
             'the line', 'so real:', 'he almost', 'I come', 'reach it', 'any visitors',
             'of privileges', 'far better', 'Holmes scribbled', 'it would',
             'who visited', 'hell Will', 'the tide', 'up the', 'am quite',
             'dangerous than', 'he walked', 'do and', 'from bed', 'his voice', 'a man',
             'And her', 'whenever he', 'was shortly', 'heavy for', 'first morning',
             'by the', 'But it', 'which one', 'in which', 'all things', 'You will',
             'net', 'him to', 'more bizarre', 'a lawn', 'really ought', 'by his',
             'vivid flame', 'make anymore', 'for agreement', 'other of', 'through it',
             'not already', 'if there', 'was at', 'The man', 'a youthful',
             'Adventure II', 'bushes', 'of calico', 'in the', 'you get', 'what notes',
             'deeply marked', 'getting an', 'that could', 'means of', "cobbler's wax",
             'book on', 'frame', 'the grace', 'bring in', 'legal matters', 'to stay',
             'fact that', 'thy icy', 'that one', 'stretches out', 'little too',
             'your right', 'little that', 'say at', 'does it', 'the thick', 'key or',
             "hands I'm", 'statue of', 'again until', 'tell her', 'had come', 'my book',
             'she said', 'unquestionably Andrew', 'how to', 'I found', 'desperate man',
             'he is', 'drought all', 'As when', '24 may', 'down in', 'prosaic so',
             'great soup', 'dressed', 'he had', 'did not', 'with the', 'lurks within',
             'wanted to', 'and try', 'face behind', 'a quick', 'two', 'of whose',
             '[SIR ROBERT', 'taken with', 'smoothest voice', 'friend Jonathan',
             "seward's diary", 'there are', 'boot to', 'clergyman beamed', 'in debt',
             'not words', 'And he', 'I drove', 'I felt', 'She pauses', 'he whispered',
             'dint of', 'almost trebled', 'to England', 'the servants', 'leave on',
             'of exeter', 'little problem', 'for if', 'when they', 'oh no', 'its death',
             'and fatigues', 'some bitterness', 'questions on', 'friend is', 'looked at',
             'believe me', 'the oboe', 'the day', 'the truth', 'my boy', 'new scheme',
             'every one', 'rest have', "I'll meet", 'which refreshed', 'Curst be',
             'of imagination', 'the modern', 'was full', 'in fact', 'evening dress',
             'about the', 'you will', 'For it', 'an Indian', 'No trace', 'of in',
             'Watson here', 'troubled you', 'thou wedding-guest', 'a lean', 'morality a',
             'of folding', 'the change', 'we descended', 'of trustees', 'Nor does',
             'faded laurel', '26 july', 'a hard', 'What did', 'I shall', 'what they',
             'might rely', 'have been', 'ready to', 'The previous', 'our respect',
             'Unable to', 'Vincent Spaulding', 'Where ends', 'his son', 'each breast',
             'The steps', 'herself down', 'goes out', 'very well', 'think over',
             'carried me', 'bottom over', 'morrow', 'have already', 'of infinite',
             'all this', 'do so', 'go to', 'to drag', 'Among like', 'glass of',
             "don't order", 'To say', 'escape from', 'interested on', 'down there',
             'offer me', 'with cigars', 'i have', 'himself at', 'and austrian',
             'In ready', 'such estimation', 'get into', 'real self', 'is bizarre',
             'no right', 'School at', 'never mind', 'build our', 'seeing', 'had taken',
             'are his', 'fall wearily', 'and sight', 'or chisel', 'greatest impulse',
             'much thought', 'back at', 'light in', 'miss chiltern', 'who runs',
             'and purpose', 'your prison', 'bold achievement', 'our clothing', 'look at',
             'the windows', 'arthur holmwood', 'making out;', 'anything very',
             'cast eyes', 'window is', 'you inquired', 'of a', 'bird to', 'you just',
             'Hesitating fashion', 'on each', 'no wind', 'are you', 'smile that',
             'enter mason', 'least first', "your worship's", 'talking excitedly',
             'picked up', 'place his', 'distinctly heard', 'Where we', 'the way',
             'opened up', 'a detective', 'But we', 'laboratory to', 'which lead', 'whip',
             'hard to', 'created Deserves', 'Rattling away', 'have tailors', 'He set',
             'and mr', 'am unhappy', 'standest thou', 'into a', '] oh', '(thought i',
             'The word', 'of shining', 'As sunward', 'living room', 'for five', 'a day',
             'must be', 'Curst all', 'damage as', 'But Gregor', 'secret from',
             'dear gertrude', 'away—that tower', 'were kind', 'voice of', 'Has been',
             'meters of', 'a pattern', "that's all", 'a village', 'The father',
             'printing books', 'Europe for', 'go as', 'my friend', 'Wilson here',
             'retire dejected', 'and held', "don't have", 'dreadful to', 'a seraph-man',
             'with none', 'remain made', 'he continued', 'foreign schooner', 'if then',
             'being seen', 'color they', 'golden', 'from a', 'holmes chuckled', 'he was',
             'black on', 'cord in', 'twice what', 'I only', 'gotta go', 'make an',
             'chapter ii', 'copper cylinder—was', 'be enough', 'but it', 'have stopped',
             'to keep', 'the spot', 'I am', 'getting dark', "the surgeon's",
             'would drag', "guess you're", 'fallacious streaming', 'chapel of',
             'They would', 'confoundedly fond', 'these lay', 'said i', 'father tells',
             'Covered those', 'arrived there', 'date of', 'heard the', 'maddening to',
             'on a', 'that the', 'making Gregor', 'To read', 'from his', 'the same',
             'or brass', 'ministers of', 'voice into', 'of his', 'what is', 'The first',
             'shown into', 'I ran', 'observing the', 'endless labyrinth', 'trace it',
             'to my', 'We passed', 'so much', 'at ease', 'me or', 'singular character',
             'run away', 'than them', 'then another', 'go on', 'his wishes',
             'were praying', 'my tablets', 'be told', 'not have', 'us in',
             'becoming gradually', 'Him who', 'paper flattened', 'out watch',
             'to France', 'But the', 'And she', 'With its', 'Saxe', 'must go',
             'His fall', 'lamps were', 'had recently', 'The spirit', 'Until we',
             'The head', 'the spring', 'as here', 'for some', 'mighty masses',
             'first thing', 'a quiet', 'the Buckingham', 'to crawl', 'to cut', 'me a',
             'are eligible', 'him I', 'of Phipps', 'he smiled', 'the table',
             'knowing what', 'As we', "I didn't", "doesn't she", 'said jones', "' ‘yes",
             'of Four', 'ruined it', 'any dream', 'the United', 'of looms', 'wrapped up',
             'in 1605', 'pick it', 'i said', 'to see', 'By means', 'the stillness',
             'as possible', 'myself to', 'degrade it', 'depth would', 'no draught',
             'he seemed', 'told you', 'a better', 'in two', 'near st', 'on one',
             'me see', 'damned scoundrel', 'What a', 'my life', 'were in', 'had my',
             'had to', 'the water', 'is not', 'change in', 'right when', "' ‘certainly",
             'he ran', 'the walls', 'exceedingly unfortunate', 'a snuffling', 'Or that',
             'see you', 'because he', 'the castle', 'he even', 'just fancy', 'wanna get',
             'for that', 'away from', 'to be', 'bowl of', 'the warp', 'he came',
             'thoughts of', 'And you', 'but oh', 'found ourselves', 'clear upon',
             'was accustomed', 'the factory', 'of spirits', 'shook my', 'he lifted',
             'Death his', 'he exclaimed', 'and this', 'were associated',
             'little children', 'it down', 'quite touched', 'Herren Klopstock',
             'one whose', 'friend of', 'her back', 'it gonna', 'but swayed', 'the one',
             'think he', 'And their', 'Unless you', 'the park', "don't even",
             'Heap wigs', 'suns now', 'one is', 'the steps', 'lips ran', 'two or',
             'a burgher', "like we're", 'away as', 'used to', 'half an', 'here for',
             'about it', 'called me', 'I had', 'for such', 'do because',
             'lunatic asylum', 'take care', 'you to', 'a sweet', 'they answer',
             'which had', 'of Briony', 'every', 'his pipe', 'But that', 'fact is',
             "twining Life's", 'with loud', 'the light', 'sort of', 'the ground',
             'you so', 'of shabbily', "You'll have", 'found the', 'to newcastle',
             "come tumblin'", 'man transmitting', 'about ten', 'have to', 'what it',
             "didn't get", 'a small', 'in our', 'before for', 'had not', 'Went straight',
             'the first', "james's street", 'blood with', 'is excessively', 'it ceased',
             'to continue', 'as well', 'that he', 'be sat', "can't eat", 'spoke almost',
             'his passion', 'which are', 'stick upon', 'industry which', 'a little',
             'Angel came', 'morbidly excitable', 'there was', 'want any',
             "what's happened", 'hansom and', 'much tip', 'open to', 'seemed to',
             'and so', 'ye can', 'have had', 'White stones', 'excitement and',
             'From which', 'been the', 'a soup', 'mitts of', 'a weird', 'was no',
             'the whole', 'conduct it', 'hunting in', "As o'er", 'cups chopped',
             'you hear?', 'Their business', 'learn and', 'the old', 'I but', 'soup for',
             'more high', 'of an', 'but unnoticed', 'completely overtopped', 'left of',
             'At first', 'presuming that', 'a woman', 'cried holmes', 'marshy ground',
             'you cause', 'injured man', 'jabez wilson', 'by me', 'her nose',
             'old peasant', 'own letters', 'the bobbin', 'what witch', 'was very',
             'distinct every', 'shave you', 'work in', 'think that', 'my deary',
             'Shivering touch', 'grandeur and', 'husband to', 'at length', 'by ancient',
             'dress or', 'our food', 'you my', 'Words are', 'simmered to',
             'several well', 'i presume', 'commerce flowing', 'say that', 'the machine',
             'The Boscombe', 'it just', 'cheers of', 'restaurant in', 'day life',
             'clubs and', 'Read the', 'ranks of', 'had a', 'fled in', 'As they',
             'you suddenly', 'like', 'we may', 'of the', 'they could', 'caused would',
             'at cromford', 'cannot be', 'sound to', 'got outside', 'his materials',
             'your Majesty', 'seven weeks', 'And Sir', 'lord goring', 'he know',
             'injuring it', 'to curse', 'adoption of', 'poor boy', 'for him', 'state of',
             'vagueness to', 'never before', 'dirty sheepskin', "can't take",
             'proper teeth—how', 'which he', 'fancy trouble', 'ancient mariner',
             'I might', 'daintiest thing', 'there I', 'am not', 'churchyard to',
             'If only', 'it strikes', 'your father', 'and opens', 'sound his',
             'strain herself', 'on this', 'louder and', 'all sorts', 'respect with',
             'While one', 'and smashed', 'sanguine temperament', 'believe that',
             'james windibank', 'the bells', 'recovered something', 'the sunshine',
             'man of', 'almost compellingly', 'steps forward', 'details of', 'that I',
             'way of', 'as now', 'a source', 'Taking a', 'of which', 'the 3rd',
             'his hand', 'stamping money', 'and said', 'uncongenial atmosphere',
             'Some letters', 'mabel chiltern', 'like it', 'arewaiting to', "Alroy' and",
             'heretofore been', 'I seized', 'god knows', 'And how', 'little monograph',
             'seriously ill', 'that was', 'I left', 'the ravages', 'humblest ranks',
             'got properly', 'I saw', 'for herself', 'cell confined', 'quite as',
             'said they', 'back against', 'absolutely love', 'upon the', 'do you?',
             'point our', 'the occipital', 'threw me', 'window at', 'upon his',
             'afford him', 'a clean', 'through which', 'dressed straight', 'danced the',
             'qualities very', 'abbey he', 'was I', 'one to', 'of easy', 'must have',
             'job would', 'of these', 'ingenious minds', 'where the', 'listened to',
             'prosecution of', 'eyes like', 'I should', 'and they', 'get your',
             'monstrous pedestals', 'not be', 'encheiresis naturæ', 'airy footing',
             'babe at', 'things that', 'was requested', 'through the', 'a bitter',
             'head to', 'to lock', 'and run', 'dashed forward', 'What the', '& Sheila',
             'the Pool', 'his bed', 'the grey', 'when you', 'all kinds', 'prospect he',
             'the best', 'later I', 'more folds', 'I cancelled', 'to about', 'that a',
             'Whenever he', 'straight to', 'to do', 'women with', "they ne'er",
             'Simply placing', 'drift apart', 'in forming', 'the time', 'grimly as',
             'given me', 'into the', 'always prowling', 'dear I', 'his arm', 'around it',
             'tired man', 'room he', 'What office', 'When praising', "didn't have",
             'hover there', 'ride to', 'is really', "- let's", 'ever happen',
             'will pass', 'think they', 'i know', 'Briony Lodge', 'passes by',
             'is abated', 'admits the', '[enter mason', 'i understand', 'With the',
             'from behind', "don't cry", 'The eagle', 'too much', 'night no',
             'is himself', 'her sails', 'what had', 'family circle', 'I thought',
             'went to', 'he remarked', 'curst when', 'more heartily', 'from my',
             'upon it', 'all at', 'vales and', 'He said:', 'use the', 'has discovered',
             'bear me', 'his way', 'as a', 'he thought', 'Although it', 'like Al',
             'no fasting', 'footfall in', 'attention on', 'much is', 'laid full',
             'and inventions', 'cup of', 'the neighboring', 'noble in', 'look after',
             'just come', 'ceased to', 'the long', 'over what', 'that we',
             'soup standing', 'had so', 'his great', 'these discs', 'with me', 'I know',
             'will be', 'if it', 'is he', 'desk had', 'is wearing', 'tearing sound',
             'same feet', 'And to', 'come very', 'be watching', 'And once', 'light',
             'it was', 'And his', 'turned the', "the Bachelors'", 'that our',
             'still time', 'his pushing', 'their homage', 'about with', 'use it',
             'to get', 'reason for', "pawnbroker's business", 'in a', 'mood which',
             'falling out', 'nothing in', 'Seeing what', 'and energy', 'each other',
             'and pausing', 'and handed', 'been away', 'love your', 'I knew', 'create a',
             'surplus money', 'but china', 'or durham', 'given it', 'the use', 'to put',
             'away like', 'has ever', 'came to', 'you doing', 'those preposterous',
             'noble when', 'at a', 'Lestrade called', 'something in', 'three sheets',
             'are elements', 'Tried as', 'at and', 'this new', 'And Robert',
             'heavy door', 'pounds of', 'be to', 'not think', 'his client', 'He would',
             'sherlock holmes', 'qualities inherent', 'carried on', 'of life',
             'the press', 'But did', 'answered: Because', 'and declared', 'late m',
             'Whose practical', 'a deep', 'oh yes', 'to let', 'and a', 'to him',
             'You have', 'shot the', 'slow and', 'Let us', 'desire to', 'two miles',
             'a lass', 'eyes from', 'my very', 'accumulated by', 'is time',
             'Lady Chiltern', 'answered all', 'warren hastings', 'does she',
             'and hungarian', 'have distributed', 'and the', 'you see',
             'your step-father', 'was not', '] phipps', 'then mr', 'or perhaps',
             'There was', 'lurk in', 'in this', 'the Count', 'me as', "don't forget",
             'have some', 'the sort', 'certain places', 'just gonna',
             'conversation which', 'yard', 'you know', 'thing was', 'And devoted',
             'her child', 'would you', 'that back', 'As he', 'another for', 'shelter on',
             'lived in', 'all the', 'puts on', 'the pang', 'to town', 'around the',
             'himself has', 'from the', 'existence does', 'near the', 'a cup',
             'those things', 'mccarthy threatened', 'form that', 'Fine Art',
             'happens if', 'for a', 'to ease', 'bowed her', 'more than', 'should vaunt',
             'die away', 'you look', 'more crude', '[exit mason', 'any of',
             'good enough', 'done in', 'just slightly', 'through Soup', 'the noblest',
             'of hearing', 'my throat', 'yet opened', 'fall into', 'deceitful thrall',
             'fear not', 'who has', 'about that', 'mind mainly', 'distressed with',
             'out of', 'in derbyshire', 'of it', 'the observance', 'carry out',
             'and gained', 'Only holding', 'store for', 'a hundred', 'As soon',
             'to work', 'a storm', 'for an', 'in victoria', 'quite improper', 'about if',
             'like mad', 'one you', 'and somewhat', 'But I', 'I can', 'news has',
             'it not', 'lady chiltern', 'of problem', 'in old', 'draught to', 'find the',
             'have you', 'printing by', 'see him', 'sight of', 'but how', 'line is',
             'tops of', 'in body', 'all sleep', 'when he', 'foundations and',
             'blood were', 'she was', 'to me', 'heavy window', 'to us', 'its change',
             'but now', 'is probable', 'me in', 'I wonder', '[sitting down', 'no cops',
             'is an', 'go silent', 'well furnished', 'the hall', 'the corner',
             'his father', 'would inform', 'clean black', 'at the', 'the most',
             'eloquence had', 'the glasses', 'beds', 'with dishevelled', "just don't",
             'who understands', 'to hand', 'you join', 'was asking', 'was glad',
             'I have', 'said holmes', 'on the', "gregor's mother", "can't we",
             'with your', 'Would always', 'Friday night', 'will suck', 'for example',
             'the article', 'to the', 'in connection', 'French accent', 'would just',
             'When pursued', 'he may', "can't out', 'argue", 'longing and', 'he were',
             'of that', 'although he', 'hosmer angel', 'with his', 'hover here',
             'their bodies', 'enough space', 'dated at', 'hair and', 'than usual',
             'morning of', 'still the', 'that it', 'you are', 'drop you', 'i shall',
             'Jerry and', 'not deduce', 'Arkwright now', 'mass of', 'tweetie weetie',
             'pursue their', 'part he', 'men and', 'Going away', '] gertrude', 'headed',
             'nearly so', 'you  know', 'the nest', 'by one', 'isles of', 'for you',
             'in short', 'paths were', 'james mccarthy', 'night', 'earning a',
             'to paris', 'everyone in', "john's wood", 'or two', 'were taught',
             'or dover', 'can reach', 'a huge', 'On whom', 'so was', 'about Lucy',
             'what then', 'said gregor', 'copy out', 'moment the', 'that certainly',
             'There could', 'heart beat', 'said lestrade', 'Count himself',
             'of extraordinary', 'nice of', 'it is', 'storied brick', 'And all',
             'had in', 'as an', 'a fool', 'bald enough', 'received many', 'am done',
             'never be', 'describe it', "the girl's", 'at Sir', 'never would',
             'grinding corn', 'my dear', 'grass and', 'should I', 'a tradesman',
             'with deference', 'his ears', 'than I', 'the room', 'But now', "Don't say",
             'ah wretch', 'lamps shone', 'time added', 'the movies', 'owe your',
             "that woman's", 'the interview', 'be of', 'which our', "as apothecary's",
             'you not', 'luck little', 'he explained', 'is a', "can't fool", 'case in',
             'been going', 'lot of']
