"""
Imported by `cpt_config.py` for use in the Tkinter GUI.

Variable:
    short_sentences (list): Short sentences for 25-40 second portion of typing test.
"""

# Short sentences for 25-40 second portion of typing test.
short_sentences = ['tell ya where I got', 'never been so', 'And an above.',
                   'As to the letters.', 'Asked the waiter.', 'Father stranger.',
                   'My heart is beating.', 'Not only that.', 'So clear and pure.',
                   'Is it not so.', 'She bore Nestor.', 'really like Sheila a',
                   "It's strange though.", 'They had separated.',
                   'there eating that and', 'Is it worth while.', 'Traces indeed.',
                   'In this grey house.', 'Poor gentle things.', 'The Count smiled.',
                   'Third class.', 'What saw I there.', 'Having once failed.',
                   'Is perfectly true.', 'Just our friends?', 'you already get',
                   'Rex probably did.', 'Queen Penelope!', 'if he catches',
                   'When he got back.', "You'd be sure to.", 'had this guy all',
                   'Why the word ought.', 'Here was the house?', 'As much as I liked.',
                   'Became wealthy men.', 'I love you so', 'I am a student.',
                   'Allow me to observe.', 'From a child.', 'All out of sight.',
                   'go to 3rd', "Don't you mind her.", 'Relax and have fun',
                   'From every one.', 'One of the broad.', 'It made me ill.',
                   'I knew it was for', '[The butler enters.', 'Burning matches.',
                   'Where are you going.', 'Come along.', 'It passed me by.',
                   'To get dressed.', 'To live the truth.', 'do they have to',
                   'I pray not.', 'The twin volcanoes!', 'to one of',
                   'Formerly a student.', 'He was so kind.', 'So big and dense.',
                   'You are not asleep.', 'know what this', 'If he can help it.',
                   "Cote d'Ivoire", 'more soup for any of', "that's all there is to",
                   'THE LAESTRYGONES.', 'Bring me sulphur!', 'O swineherd Eumaeus!',
                   'way I figure', 'Not a commonplace.', 'The hobbit has been.',
                   'Yet a few paces.', 'Meanwhile Ulysses.', 'This god appeared.',
                   'To be sure.', 'It was a pokey.', 'As regards mortals.',
                   'Ask a question', ' he muttered.', 'And mocked at him?',
                   '] Dear Lady Markby.', 'I am sure.', 'And to and fro.',
                   'As for the suitors.', 'and personally thank', 'it up from',
                   'on the street', 'love thy neighbour?', 'The sun was now set.',
                   'Ask the porter.', 'guess I have all the', "D'you hear!",
                   'Opened her mouth.', 'And in them.', 'To my astonishment.',
                   'About This Article:', 'Our one stay.', 'the rules and then',
                   "I've no boots.", 'I wish Father Jove?', 'I would obey you.',
                   'meet new people', 'And the purse too.', 'I am sorry for him.',
                   "Apollo's messenger.", 'Telemachus wept.', 'You are forgetting.',
                   'small workshops', 'To smaller animals.', 'like this all the',
                   'Has a cleft palate.', 'One less to keep.', 'Blinking eyelashes.',
                   '- I think', 'would have taken', "I'll tell ya", 'He was pale.',
                   'are the guys', 'He waved his hand.', 'Tell her tobegin.',
                   'I am still strong.', 'I know all about it.', 'Tell me also truly.',
                   'Good heavens.', 'Not even to Mr.', 'is an antique',
                   'Enter a Student.', 'Rex had feathers.', 'As for the boar.',
                   'It must be bought.', 'She bore Nestor?', 'Coming forward.',
                   'Faults and all.', 'There I saw Helen.', 'Across the room.',
                   'As for my escort.', 'Another three days.', 'He shouted.',
                   "For God's sake.", 'A good old woman.', 'And say nothing.',
                   'More simply.', 'beware the projector', 'He thought?',
                   'conference talks', 'North Korea', 'And high to climb.',
                   'To grasp the key.', 'And the master.', 'If he did see it.',
                   'Only to get it over?', 'does not go with', 'Leave me in peace!',
                   'He is very rich?', 'Sulphur dioxide.', 'He showed you too?',
                   'To my horror?', 'With a rending.', 'Have you met before.',
                   'armoire in my', 'Yet if you like.', 'Where Gregor was.',
                   'And mocked at him.', 'With his wide hat.', "- wha - what's the",
                   'more soup for', 'About my mother.', 'do you want to?',
                   'And every soul.', 'The mules drew well.', 'I dare be sworn.',
                   'In yellow covers.', 'I did it.', 'For that reason.',
                   'Wish to ship goods.', 'In other words,', 'He turned round.',
                   'Without hurry.', 'Be off with you.', "I'm gonna share with",
                   'That I know.', 'In every dance.', 'Strike me openly.',
                   'The phantom shapes.', 'And not from fear.', 'Not a word.',
                   'How do you mean.', "He's a young man.", 'so open with',
                   'And I charge you.', 'I come from Alybas.', 'As through a grate.',
                   'happen to love that', 'I shall say no more.', 'My dear father.',
                   'She added.', 'you know what?', '[To LORD GORING.',
                   'You will be unhappy.', "It's like a tomb.", 'When a boy.',
                   'You are not going.', 'is a soup', 'Just now.', 'Winds from East.',
                   'If these Achaeans.', 'The sly dog!', 'soup in the', 'no moving on',
                   'toughs took my', 'We find Copernicus.', '- wha - what are',
                   'If you can?', 'I am afraid.', 'She is an angel.',
                   'As fair as can be.', "- I'm your baby", 'are you gonna',
                   'We carry it home.', 'I had a dozen.', 'He bowed gravely.',
                   'For nearly 60 years.', 'While He is near.', 'would hit the',
                   '[With a curtsey.', 'It is nothing.', 'They threatened him.',
                   'Good luck to you.', ' Razumihin insisted.', 'Mumbled Zossimov.',
                   'just happens to', 'If you were their.', 'My dear Watson.',
                   "I'll be bound.", 'I desire it much.', 'He answered dryly.',
                   'More than that.', 'Grinding his teeth!', 'You are right.',
                   'We are just here.', 'Find collaborators', 'But I prevented him.',
                   'And are there two.', 'My dear fellow.', 'Am I not a goddess.',
                   'Nikolay Dementyev.', 'Accursed be Mammon.', 'Hour after hour.',
                   'But my dear nurse.', 'She is only a woman.', 'I am also stronger.',
                   'It is tyranny?', 'It is despotism.', 'has to leave her',
                   'Did you tell him.', 'Razumihin agreed.', 'know what I just',
                   'He asked suddenly.', 'Bear everything.', 'She then cried.',
                   'I besought her aid.', 'Known as moonquakes?', 'Are you still here.',
                   'This smartness.', 'Here he is himself.', 'Joy and sorrow.',
                   'Not far from here.', 'Their red jaws.', 'Cigarette case.',
                   'even give you', 'If I were told.', 'Very good.',
                   'And so at all costs.', 'Fully penitent.', 'As to this science.',
                   'And a dirty one.', 'We are neighbours.', 'Come sit down.',
                   'Ulysses himself.', 'In your case.', 'And left a square.',
                   'By the holy rood.', 'taking the armoire', 'a little strange',
                   'He muttered.', 'But come inside.', "I don't know.",
                   'Or else Crevez.', 'Saudi Arabia', 'You may amuse him.',
                   ' I would say.', 'Loss and gain.', 'with a bowl of',
                   "Don't be too sure.", 'me for the', 'Asked Razumihin.',
                   'With either of you.', "It's all clear.", 'You are forgetting!',
                   'Said his father.', 'I saw that curse.', 'To be sure?',
                   'And blue and white.', 'So I lost my temper.', 'This means that.',
                   'he just let me have', 'just cost yourself a', 'I would like a cat.',
                   'Pear grows on pear.', 'But heavens.', "' she said.", 'He knows me?',
                   'New Zealand', '- which I', 'And in return.', 'we had a',
                   'For love of God.', 'It was a disgrace.', 'Queen Penelope.',
                   'It is past ten.', 'That is important.', 'drawing people in',
                   'To ruin me.', 'Is this the man.', 'Who was listening.',
                   'And with reason.', 'Even as wax melteth.', 'She took his shape.',
                   'May I try.', 'you got a nice', 'He is Egyptian.', 'There is a way.',
                   'Cried the King.', 'But he is right.', '- I was really',
                   'Periods of gloom.', '[After a pause.', 'Suddenly he started.',
                   "I'll show you.", 'Le beau sabreur.', 'I hope so.',
                   'She was howling.', 'what the axes mean', 'What was I saying.',
                   'see what happens to', 'is that with the', 'Roused himself.',
                   'He passed him by.', ' what came of it.', 'So I see.',
                   'Semyon Zaharovitch!', 'Richer by some £30.', 'Away with it.',
                   'A sure possession.', 'Her lips parted.', 'Is epsom salt good?',
                   'I must stop.', 'people to sit on', 'To be depended upon.',
                   'heading over to', "She'll jog along.", 'More simply!', 'I remember.',
                   'Or to any other.', 'Under me the sea.', '* 31 May.',
                   'Bring me sulphur.', "And I'm sick of it.", 'chose soup over a',
                   'Excuse my saying so.', 'No mistake about it.', "But by God's mercy.",
                   'with the soup', 'The case has.', 'very important not',
                   'Another week gone.', '] LORD CAVERSHAM.', "we're kind of",
                   'Probing her further.', 'Warm gratitude.', 'As I understand.',
                   'With many kisses.', 'From four to seven.', 'Be off with you!',
                   'O pass not by.', 'Which opened south.', 'An italian banker.',
                   'There is a pause.', 'When Marmeladov.', 'What do you want.',
                   'Yesterday Zametov.', 'I must watch him.', 'I need hardly say.',
                   'Leave me in peace.', 'can be so weird', 'If they question me.',
                   'Burkina Faso', 'Wake up Penelope.', 'The root was black.',
                   'pie joke I told', 'You can smell ants?', 'As for Telemachus.',
                   'She was untruthful.', 'It is very possible.', 'We may take it.',
                   'Here I am noble.', 'follow the ordering', 'Matryoshka Dolls',
                   'all hand made', 'And by the sea.', 'And his wife.', 'It was dark.',
                   'I am boyar.', 'Light of my eyes!', 'to hold this for',
                   "think he's in a good", 'Just as I expected.', 'Pear grows on pear!',
                   "'bout a little", 'Life is real.', 'I dropped my gun.',
                   'had to listen to a five', 'The career of Mr.', 'Gilberto Baschiera!',
                   'How much water?', 'To his successors.', 'suffer for your',
                   'go there the', 'In a technical talk', 'My lips were wet.',
                   'Remember that', "' I asked.", 'It is tyranny.', 'And so long ago.',
                   'And rang at No.', 'I am sure Mr.', "don't want you causing",
                   'Pacing up and down.', 'I fear thee.', 'finally got a',
                   'Considerate even?', '7 million dollars?', 'the man make his',
                   'Any of you.', 'But who is he.', 'Let my life go.',
                   'There is no one.', 'engaged to be', "' My dear Mina.",
                   'We shall see.', 'to as the soup', 'what are you',
                   'Dmitri Prokofitch?', 'Lifeless and flat.', 'life was in',
                   'Volume adds emphasis', 'But down below.', 'And Irene Adler.',
                   'Our one hope.', 'Sail night and day!', 'Messenger Mercury.',
                   'Here was the gate.', 'He was overwhelmed.', 'You can smell ants.',
                   'But with sour sugar.', 'Do you have to?', 'Began Zossimov.',
                   'Why was he here.', 'In a voice which.', 'Am I awake.', 'By the way.',
                   'can move it in', ' Do you hear.', 'I went to Cyprus.',
                   'Fajita is a Tex-Mex.', 'He got him there.', 'Having lit it.',
                   'I hasten on.', 'The other was fair.', 'After the talk',
                   'have to taste', 'you walk in the place', 'She is a quick girl.',
                   'Another thought.', 'They had just left.', 'Impudent baggage.',
                   'I am not sure.', 'practice some more', 'The idea struck him.',
                   'Then Euryalus said.', 'I am no prophet.', 'He did not.',
                   'Telemachus Euryades.', 'And vulgar enough.', 'After the wedding.',
                   'a cup of olive', 'What a misfortune.', "You've heard that.",
                   'The gospel of gold.', 'shifting into soup', 'Known as moonquakes.',
                   'We have suffered.', 'I did was shake your', 'There are none.',
                   'The doors were gold.', 'Dmitri Prokofitch.', 'For instance!',
                   'Why did I add that.', 'To-day is Saturday.', 'And so masters it.',
                   "just can't tell you", 'After the trial.', 'Let us then be off.',
                   'What are they doing.', 'Raised his head.', "And comin' quick.",
                   'But Vrazumihin.', 'Wearing a full.', "I don't want.", 'A man who.',
                   'just wanted the', "You're a loose fish?", 'Papua New Guinea',
                   'Here was his house.', 'On his own account.', 'Bring in the parcel.',
                   'Practice makes more', 'At your service.', 'Then a third man.',
                   'can I tolerate', 'To the door.', 'Neither his mother.',
                   'Tit Vassilitch.', 'You filthy glutton.', 'This is Mr.',
                   'I am in great want?', 'As he released me.', 'got it from the',
                   'And a name.', 'a guy on the', ') 12 May.', 'An under be.',
                   'I have thee now.', 'For some reason.', 'Here we are.',
                   'embellish on your', 'Only to get it over.', 'Has no will.',
                   "But I'm content.", 'On the contrary.', 'Take this pitcher.',
                   'Her lips were red.', 'can I possibly thank', 'The hopelessness.',
                   'And cheeks so red.', 'And no news.', 'I love the',
                   'He appears as Mr.', 'And in my garb.', 'His old thoughts.',
                   'We must part.', 'How can i get copy?', 'I am not changed.',
                   'Though poorly clad.', 'How strange it was.', 'Sound thou on.',
                   'Here I am.', 'For instance.', 'Lies all of them.',
                   'could give these', 'gave you the', 'It was damp.',
                   'Well and what then!', 'He left me.', 'was stupid of',
                   'As for your voyage.', 'O happy he.', 'Sound at heart.',
                   'My darling?', 'As I expected.', 'Tell her tobegin!',
                   "Therefore I'm mad.", 'Cried Raskolnikov.', 'this is so nice and',
                   "But we'll see.", 'Why do you keep on.', "g  can't you",
                   'And approved fully.', 'As they think.', 'Along that theme.',
                   'And live at ease.', 'Confound you then.', 'Turned on his heel.',
                   "' she cried.", 'Like a witchs oils.', 'get a big',
                   'Exaggerating it all.', 'and your institution', 'You are harsh.',
                   'No reason to.', 'still with the', 'During the Season.',
                   'She must be forty.', 'He wore spectacles.', 'He is an Egyptian.',
                   'What am I to do.', 'A friend of mine.', 'Had the same habit.',
                   "D'you hear.", 'That is to say.', 'you to be', "didn't get any",
                   'Even when a boy.', 'How Many ML Is 6 MG?', 'could - I',
                   'Look at it well.', 'Nor terrors appall.', 'Never to return.',
                   'He calls attention.', 'Generally speaking', 'guy is gonna get',
                   'Driven by horses.', 'A man all light.', 'Are fajitas Mexican?',
                   'Grinding his teeth.', 'My poor unhappy man.', 'Blinking eyelashes!',
                   'I only wanted.', 'Gazing after him.', 'It is so.', 'I should think.',
                   'If I be sane.', 'When he was.', 'Considerate even.',
                   'It was now daylight.', 'it he says', 'Put in Raskolnikov.',
                   "He's waited long.", 'A good old woman!', 'Chorus of Spirits.',
                   'Have mercy upon me.', 'Is it possible.', 'and you will be',
                   'She is mistrustful.', 'It is this spirit.', 'In his stately way.',
                   ' Razumihin insisted!', 'Give him his helmet.', 'For the Friday.',
                   'This is the point?', "we'll meet you and", 'Not to be beaten.',
                   "That won't harm ye.", 'I am writing now.', 'made the right',
                   'In any event.', 'And only fancy.', 'If I had.',
                   'Addressing Zossimov.', 'Limp and helpless.', 'And then he choked.',
                   'His eyes glowed.', 'Quite right.', 'Tell an anecdote',
                   'What can you do?', 'You country louts.', 'I shall never.',
                   'To Razumihin.', '- or do', 'I looked down once.', 'He is injured.',
                   'Strange to say.', "That's evident.", 'Or pen shall it be.',
                   'Bless my heart.', 'As you say.', 'Not Razumihin.',
                   'And to know that.', 'a look at', 'The sly dog.', 'And turning iron.',
                   "I don't want!", '] I hope so.', 'Wretched creature.',
                   'Leave off doing so.', '{45} At length.', "At two o'clock.",
                   'But she stopped!', 'I tell you', 'You precious idiot.',
                   'Why do you go.', 'You were wrong.', 'And high boots.',
                   'much I appreciate', 'Again the hospital.', 'Gazing after him?',
                   'As for the day time.', 'On the other hand.', 'Hunting big game!',
                   'At that very hour.', 'We must have a cab.', "It's impossible.",
                   'Let me persuade you.', 'Go to hell then.', 'A workman at Lyons.',
                   "I'm not rich.", 'Or as a blind.', 'It is not right.', 'us for lunch',
                   'As for your own end.', 'At this hour.', 'Close in swiftly.',
                   'And all be well.', "could have 'em", 'As you know.',
                   'Tell me then truly.', 'A wager on it.', 'of these days',
                   'It is all right.', 'So that the client.', 'I said to my men.',
                   'He answered: Well.', 'was talking to', 'Mad besides.',
                   'Dounia and I.', 'O swineherd Eumaeus.', 'told him the whole',
                   'We have suffered?', 'My darling.', 'And sat down again.',
                   "'Press F10 to save'", 'What has poor Mr.', 'But for that.',
                   'just want you to know', 'Duncan Ross was.', 'it unbearable to',
                   'When you exercise.', 'So they have.', 'I want to get home.',
                   'in front of', 'do you mean?', 'Am I not a goddess!',
                   'So he at once said.', 'I was all dismayed.', 'She came up to me.',
                   'Now I have been ill?', 'This further grief.', 'Hurriedly dressing.',
                   'just gonna go down', 'you you look', 'Believe me.',
                   'plane above the', 'Now another point.', 'I noticed that.',
                   'But never mind.', 'The door is shut.', 'This is the point.',
                   'He cried again.', 'When the maid.', " 'I was frightened.",
                   'In vexation.', 'It is obvious.', 'He continued.', 'does he do',
                   'And yet My dear.', "they won't do it", 'All that time.',
                   "' said he.", 'He stands already.', 'Almost physical.',
                   'Wake up Pisistratus.', 'were making me and', "I can't imagine.",
                   'He embraced him.', 'Ask your father.', "think it's great",
                   "That's very natural.", 'you gotta have', 'because I know',
                   'me got free', 'Martin, an island', 'Said the stranger.',
                   'And he is my friend.', 'I prefer books.', 'affection - which',
                   'Mina is a woman.', 'think you can get', 'that his recipes are',
                   "Nastasya's with him.", 'Like one distraught.', 'and how to read it',
                   'She cried to him.', 'Here was the house.', 'gave you a', 'of on the',
                   'I have already told.', 'the K Man do it', 'Then Antinous said.',
                   'I bit my arm.', 'out of my', 'He muttered!', 'You must admit that.',
                   'hold out your', "She'll gallop.", "Don't be impudent?",
                   'What endurance too.', 'working meetings', 'She cried to him?',
                   'She held a veil.', 'While blessings.', 'Let us be going.',
                   "An' the like.", 'Her name is Arete.', 'Heaven help me.',
                   'Like a leaf?', 'If you can.', 'A lad of eighteen.',
                   'Observed Zametov.', 'if all else fails', 'the main result',
                   'Nor dim nor red.', 'Then bring it to me.', 'Of course.',
                   'Stay where you are.', 'I was so proud of', 'What do you think.',
                   'What am I to do now.', 'To an end.', 'Entered the room.',
                   'South Africa', "It's my property.", 'Order in person!',
                   '] MABEL CHILTERN.', '] LADY CHILTERN.', 'I thought as much.',
                   'got a nice', 'Ulysses saw her.', 'PART THE SIXTH.',
                   'It could come soon.', '] The fact is.', 'Then he got up.',
                   'It is possible.', 'Than with them.', 'With gentle eyes.',
                   'one of your friends', 'I wish Father Jove.', 'Using the jaw.',
                   'He raised his hand.', 'I knew all about it.', 'That is it.',
                   'You know what this', 'Farewell stranger.', 'K Man did',
                   'you want to pick it', "But we'll see!", 'United States',
                   'And in and out.', 'Such a soft.', 'is what comes from',
                   'He had not the axe.', 'I find that black', 'He let go the helm.',
                   'All the time.', "What's the slope?", 'Sitting up again.',
                   'I left him.', 'As a rule.', 'Coming here.', 'that - but',
                   "But don't mind me.", 'and design elements', 'You are a one.',
                   'With an excuse.', 'PART THE FOURTH.', 'have been a good',
                   'you noticed George is', "' said I.", 'Man in general.',
                   'My throat was cold.', 'There is a date.', 'all kinds of',
                   'Do you know.', 'Light of my eyes.', 'From unseen hand.',
                   'The Count stood up.', 'Of the Hall.', 'Mark that point.',
                   'But she stopped.', 'Alice was silent.', 'No one but Mr.',
                   'He is very rich.', 'The twin volcanoes.', 'off with the',
                   'But Ulysses said.', 'About 300,000', 'In a conference talk',
                   'Sail night and day.', 'because the two', 'Goodness knows why.',
                   'Near the city.', 'He felt the change.', 'I am coming to you.',
                   '] Do you know.', 'But I fear.', 'and it is so', 'To share its life.',
                   'on one of', 'Father Eumaeus.', 'Silent and frowning.',
                   'Would you believe.', 'With glaring eyes.', 'Partly by day.',
                   'Stay where you are?', 'been a big', 'What are you saying.',
                   'How they push.', 'Quire of Women.', 'We hate and love.',
                   'One of them said.', 'I then bored a hole?', 'Scaling this up to.',
                   'You will sign it.', 'The devil.', 'This is your case.',
                   'Close with my plan.', 'As for yourself.', 'Like a leaf.',
                   'Glancing over them.', 'As for the stranger.', 'And his hometown.',
                   'South Sudan', 'he allowed to do', 'make me hurt', 'And I am master.',
                   'large crab bisque to', 'gonna guard it for', "giving away what's",
                   'in the mood', 'We become casuists.', 'no truth to', 'The student.',
                   'Now I have been ill.', 'I want to get home?', 'In magic veil.',
                   'Night was coming on.', 'Use vocal energy', 'Unstable Wi-Fi',
                   'Do you hear.', 'She added!', 'to get back with', 'Holding it out.',
                   'Without opening it.', "I couldn't do it.", "' All right.",
                   'This is serious.', 'His head ached less.', 'gives him back his',
                   'O swineherd Eumaeus?', 'During that time.', 'That is all.',
                   'What do you mean.', 'Said Jabez Wilson.', "Don't go away.",
                   'Obtain feedback', 'It may be.', 'Who was listening?',
                   'Just what I thought.', 'They meant no guile.', 'But let us watch.',
                   'Is that a DEATH.', "Therefore I'm mad!", 'Flat Number 14.',
                   'It is excluded.', 'Jerry and that', 'When over us.',
                   'Was then called.', 'Gallop indeed.', 'Mumbled Zossimov?',
                   'Speed can energize', 'in my entire', 'yells and you',
                   'Not a commonplace?', 'And cause headaches.', 'Hunting big game.',
                   "That's enough.", 'The day before me.', '* 19 May.',
                   'He went on gaily.', 'trouble down at that', '] Lord Goring.',
                   'gotta go to the soup', 'We to the mill.', 'Just our friends.',
                   'He stood still.', 'Immense experience.', 'Great Goddess Diana?',
                   'gave me the', 'Nothing of the sort.', 'And sat down again?',
                   'My dear boy.', 'Accursed be Faith.', 'He will forgive.',
                   'Just as mine are.', 'at the movie', 'And your father.',
                   'As Spaulding said.', 'It is so pretty.', 'More loudly.',
                   'After scanning Mr.', 'is it you', 'Said a woman.', 'Turn a little.',
                   'PART THE SECOND.', 'Member for Salford.', 'He thought.',
                   'In this room.', 'As for Telemachus?', ' and so on.', 'is that right',
                   "That's a sin.", 'are you getting', 'She must be forty!',
                   'In these cases', 'wrong with this', 'United Kingdom',
                   'About my mother?', 'guy makes the', 'in the first', 'in to fall',
                   'The cheapest.', 'I motioned for air.', '—to travel abroad.',
                   'can make my own', 'Or if at only one.', 'Give it to her.',
                   'Well and what then.', ' I should think so.', 'May visit you also.',
                   "Don't be impudent.", 'In some respects.', 'Exaggerating it all?',
                   'The drunkard.', 'An obstinate.', 'Fool that he was.',
                   'I will put bread.', "That's very natural?", 'Even you would not.',
                   'Ajax was wrecked.', 'Is a short time.', 'He said to himself.',
                   'Calypso went home.', 'Presently she said.', 'you talking to',
                   'It is only fair.', 'What is it.', 'To the war.',
                   'Another must go to.', "didn't know you liked", 'I tell you that.',
                   'My dear sir.', 'Is not the meanness.', "' He wrung my hand.",
                   'And reads it.', 'I then took my gun.', 'I began to jeer.',
                   'He knew me and said.', 'And also to Mina.', 'your soup in a',
                   'Makes it indeed.', 'As she left him.', 'have a good',
                   'Ringing the bell.', 'love thy neighbour.', 'Semyon Zaharovitch.',
                   'Their messenger!', 'to the left and', 'Muttered to himself.',
                   "' I answered.", 'Said my wife.', "You're a loose fish.",
                   'Eggs are rich.', 'then they just', 'I had nine ships.', 'get hurt I',
                   "Jove's daughter.", 'But now tell me.', 'gotta go back',
                   'In the chair.', 'You are tired.', "he's better than",
                   'What does this mean.', 'yum little tuna', 'Disdainful of ease.',
                   'A model of which.', 'You must know.', 'Winking at me.',
                   'What do you say.', 'immediately to your', 'All right.',
                   'Not that your wife.', 'I quite understood.', 'Hawkins in secret.',
                   'Ten minutes passed.', 'Was one of them.', 'To my horror.',
                   'If you leave.', '* 15 May.', 'I tell you all.', 'Thy goodly round.',
                   'As for yourselves.', 'Do you hear?', "can't go in",
                   'What does it mean?', 'go get some', 'Furthermore I say.',
                   "That's what's bad.", 'You are our all.', 'We must lock up.',
                   'Who was he.', '] LORD GORING.', 'German women.', 'She is afraid.',
                   'did the K Man do', 'He answered.', 'and I are', '3rd or 84th and',
                   'to get soup', 'On this Polites.', 'Used to say.',
                   'Neither his mother!', 'One less to keep?', 'She was beseeching.',
                   'He knows me.', 'Is it he.', 'House and hearth.', 'could be a little',
                   "I didn't do", 'I should think so.', 'In this type of talk',
                   ' what came of it?', 'Give him the bow.', 'are the only',
                   'Most importantly', 'With a rag of sail.', 'There he married.',
                   'Like Gods own head.', "I'm walking out", 'How many carbs?',
                   'Not only that!', 'should I be', 'more normal than',
                   'Sulphur dioxide?', 'As it pulled up.', 'But he went on.',
                   'Then they cut it up.', 'And I ran after him.',
                   'Get you to your bed.', 'So here you are.', 'The tear doth gush.',
                   'need something to sit', 'The other answered.', 'top priority is',
                   'Then I said to them.', ' he muttered?', 'Accursed be Hope.',
                   'have it in', "don't see how you can", 'Their messenger.',
                   'main thing is', 'you tastes the', 'This is your case!',
                   'And proved it.', 'Same thing often.', 'I am in great want.',
                   'They do not breed.', 'that that Bania']
