"""
Imported by `cpt_config.py` for use in the Tkinter GUI.

Variable:
    words_one (list): Single words for sub-15 second portion of typing test.
"""

# Single words for 0-10 second portion of typing test.
words_one = ['inviolate', 'heedfully', 'beat', 'things', 'slight', 'Hera', 'to', 'Came',
             'heroes', 'obey', 'pilgrimage', 'are', 'flung', 'new', 'yawn', 'Son',
             'sounded', 'mind', 'teach', 'Prytaneum', 'entreat', 'tales', 'conversing',
             'Chained', 'dost', 'music', 'carcanet', 'towards', 'turns', 'lesser',
             'endure', 'different', 'truly', 'Stood', 'Holding', 'warn', 'from', 'Deep',
             'says', 'report', 'surely', 'beating', 'gives', 'assembly', 'Prytanes',
             'meekly', 'Chorus', 'away', 'thrall', 'successor', 'convincing', 'Gate',
             'Loves', 'hither', 'thirty', 'fight', 'Shalt', 'Accepted', 'strayed', 'Men',
             'The', 'may', 'name', 'curious', 'straw', 'athwart', 'tide', 'exiled',
             'smitings', 'rarer', 'deserves', 'Come', 'case', 'believed', 'locks',
             'comedy', 'presidency', 'Oath', 'wrongs', 'numberless', 'Childless', 'past',
             'soothsayers', 'after', 'beside', 'shaft', 'herself', 'endured', 'practise',
             'As', 'quarrel', 'Like', 'means', 'driven', 'Back', 'eyeballs', 'happiness',
             'took', 'gods', 'spoil', 'foals', 'sensible', 'apt', 'doorway', 'untimely',
             'sufferings', 'rule', 'saw', 'think', 'break', 'standest', 'tiding',
             'selected', 'feasts', 'origin', 'fall', 'smallest', 'proud', 'nymphs',
             'Cast', 'genius', 'boldness', 'consequence', 'other', 'makes', 'Fear',
             'Theodotus', 'whither', 'slander', 'Prodicus', 'Beggared', 'Muses',
             'Spring', 'nothing', 'ails', 'drive', 'Home', 'faith', 'alien', 'Seemed',
             'struggle', 'deserve', 'city', 'swear', 'Wild', 'style', 'high', 'spread',
             'Gifts', 'possess', 'pity', 'heads', 'swept', 'fear', 'scarce', 'country',
             'Reasons', 'citizen', 'Reflecting', 'hearts', 'occur', 'under', 'Beseech',
             'waited', 'suffer', 'intentionally', 'certainly', 'unseen', 'manifest',
             'Lay', 'evermore', 'Clash', 'despised', 'ills', 'Sooner', 'Hell', 'fools',
             'mark', 'humble', 'worst', 'bitter', 'door', 'grief', 'Amphipolis',
             'perilous', 'frail', 'faint', 'grant', 'beareth', 'well', 'send', 'find',
             'It', 'Lest', 'Make', 'advanced', 'wounded', 'brow', 'honour', 'afar',
             'seized', 'fingers', 'Greeks', 'Cyprian', 'follow', 'husband', 'less',
             'asks', 'slowly', 'Yet', 'comes', 'served', 'refused', 'exile',
             'deficiency', 'unfortunate', 'lucky', 'space', 'Seeking', 'Haunting',
             'beast', 'cup', 'banishment', 'what', 'censuring', 'stealing',
             'reproaching', 'starved', 'moods', 'undreamed', 'passed', 'sun',
             'patiently', 'left', 'wherefore', 'dishonourable', 'side', 'reached',
             'JASON', 'deny', 'me', 'unholy', 'ghastly', 'feast', 'Far', 'prosper',
             'constantly', 'We', 'escaping', 'benefited', 'himself', 'waste', 'Unlit',
             'spent', 'wearied', 'during', 'corrupted', 'daughter', 'Take', 'corrupts',
             'often', 'all', 'While', 'mock', 'the', 'stoutly', 'earned', 'request',
             'foundation', 'shared', 'gold', 'dire', 'old', 'praise', 'impious',
             'reflected', 'encastled', 'star', 'spell', 'hard', 'stars', 'line', 'beach',
             'faced', 'wipes', 'unto', 'Have', 'that', 'unfrequently', 'hopeth',
             'raiment', 'love', 'injury', 'One', 'Look', 'avenge', 'associated',
             'tongue', 'landless', 'stricken', 'vain', 'this', 'orators', 'testimony',
             'simply', 'smite', 'passionately', 'Thy', 'Lord', 'doth', 'babes', 'afford',
             'made', 'ask', 'tarry', 'informing', 'garden', 'Golden', 'fierier',
             'desires', 'fragrance', 'pursuing', 'so', 'Certainly', 'crew', 'before',
             'Aid', 'really', 'hating', 'riddle', 'corrupting', 'moves', 'childless',
             'mine', 'denying', 'knee', 'desert', 'longer', 'discourses', 'chances',
             'taught', 'lowest', 'Woe', 'myself', 'together', 'inward', 'call', 'asked',
             'craft', 'toils', 'braving', 'lies', 'body', 'plan', 'empty', 'dawn',
             'Mere', 'heal', 'class', 'Drew', 'Dark', 'Pittheus', 'Get', 'Fruits',
             'Join', 'skies', 'busying', 'Grief', 'charged', 'won', 'Socrates',
             'miserable', 'gently', 'Names', 'brain', 'source', 'either', 'There',
             'security', 'brave', 'Argo', 'filled', 'Mark', 'memory', 'received',
             'finds', 'conceiving', 'conduct', 'complete', 'now', 'Let', 'dread',
             'justice', 'master', 'raise', 'swerve', 'feeble', 'Had', 'Gorgias', 'her',
             'dark', 'Keep', 'by', 'laughed', 'interpretation', 'await', 'paths',
             'wisdom', 'quietly', 'when', 'white', 'books', 'taketh', 'clearly', 'games',
             'explain', 'speaks', 'fast', 'untrodden', 'she', 'inquisition', 'allege',
             'blows', 'but', 'sweeps', 'folk', 'occasion', 'oligarchy', 'quite',
             'fearest', 'mirror', 'watch', 'Cephîsus', 'confirm', 'harmed', 'Feel',
             'attained', 'day', 'arousing', 'neglected', 'shroud', 'Blessing', 'grew',
             'affirm', 'gates', 'pretended', 'Nor', 'twined', 'sunlight', 'persuasive',
             'mighty', 'alone', 'rises', 'Shrouded', 'Children', 'forbids', 'another',
             'for', 'not', 'conviction', 'recking', 'aside', 'halls', 'suffers', 'eager',
             'military', 'relations', 'family', 'groom', 'slanderers', 'carelessness',
             'fire', 'quit', 'running', 'trying', 'tall', 'fiercely', 'trod', 'somewhat',
             'workings', 'goes', 'my', 'blest', 'alarms', 'keel', 'molten', 'red',
             'interest', 'burning', 'there', 'error', 'Tempestuous', 'acquitted',
             'sound', 'betrayed', 'Was', 'disobedience', 'arrowy', 'Hellas', 'temples',
             'minæ', 'regard', 'Away', 'Woman', 'rather', 'river', 'planted', 'Reject',
             'bodies', 'dazzle', 'stay', 'entreaty', 'burneth', 'which', 'Troy',
             'condemning', 'caught', 'imposed', 'passing', 'petition', 'VOICE',
             'private', 'doubt', 'us', 'honestly', 'ought', 'Comes', 'assume', 'held',
             'ancient', 'troth', 'vote', 'laughest', 'hardly', 'none', 'tables',
             'knoweth', 'punish', 'near', 'those', 'defence', 'indictment', 'injure',
             'Wouldst', 'breast', 'come', 'beaked', 'Rude', 'Their', 'Great', 'stain',
             'deft', 'ridicules', 'dream', 'though', 'journey', 'deigned', 'fashion',
             'reasons', 'Reach', 'deme', 'because', 'hear', 'could', 'sown', 'service',
             'upon', 'being', 'plea', 'lie', 'hid', 'blessed', 'fareth', 'bade',
             'wickedness', 'beats', 'bred', 'waxeth', 'Who', 'sweetest', 'assure',
             'swiftly', 'great', 'head', 'touched', 'They', 'Do', 'curses', 'slower',
             'gripped', 'pondering', 'workmen', 'divers', 'begin', 'erst',
             'imprisonment', 'happy', 'nor', 'likes', 'drivest', 'citizens', 'Next',
             'Her', 'godhead', 'Unholy', 'possibly', 'shiver', 'since', 'Heard',
             'deliverance', 'hurt', 'Beside', 'apprehend', 'spoke', 'shall', 'Won',
             'hurrying', 'cast', 'maketh', 'Rend', 'trackless', 'Holder', 'Ye', 'Only',
             'falsest', 'rumours', 'creep', 'deep', 'looks', 'shameful', 'strive',
             'three', 'deters', 'sight', 'fulfilled', 'Myself', 'menace', 'compliance',
             'been', 'sapped', 'pay', 'middle', 'flow', 'daring', 'Homer', 'lave',
             'panting', 'whose', 'hurts', 'teacher', 'dramatic', 'feed', 'also', 'Old',
             'an', 'into', 'Hunted', 'How', 'Stole', 'castle', 'Slow', 'Whereupon',
             'roamed', 'fit', 'build', 'Grew', 'discreditable', 'improvement', 'does',
             'venture', 'more', 'where', 'penalty', 'seem', 'raised', 'turning',
             'fountain', 'Unhappy', 'search', 'dear', 'reproach', 'punishment',
             'political', 'Through', 'stintless', 'going', 'Crosseth', 'falleth', 'Must',
             'Ajax', 'last', 'casts', 'faces', 'defending', 'liked', 'About', 'hopes',
             'exhibitions', 'Still', 'trouble', 'subtly', 'consider', 'sons', 'Shore',
             'easily', 'midnight', 'fortune', 'Wrought', 'son', 'Up', 'latter', 'signet',
             'look', 'battle', 'stood', 'answer', 'loved', 'harbourage', 'shaped', 'Him',
             'shapes', 'loving', 'bloom', 'dreamed', 'war', 'accustomed', 'indeed',
             'numerous', 'sepulchre', 'Give', 'facing', 'possible', 'innumerable',
             'bosom', 'striving', 'loathing', 'kindness', 'bend', 'youth', 'Quest',
             'meaning', 'Seek', 'burden', 'conceit', 'event', 'pen', 'chariot',
             'abhorred', 'concealed', 'spoken', 'seventy', 'imitate', 'hastily',
             'lasting', 'Women', 'witnesses', 'Zeus', 'Greek', 'Sate', 'Oh', 'way',
             'undervaluing', 'early', 'opinion', 'dreadful', 'guilty', 'rock', 'kinsmen',
             'demean', 'Strangling', 'grasp', 'childish', 'wherever', 'discrowned',
             'bearing', 'story', 'Wisdom', 'wherein', 'town', 'maintained', 'regular',
             'Served', 'duteously', 'evil', 'fruits', 'differ', 'sway', 'stint',
             'rolled', 'amid', 'got', 'bravely', 'alway', 'entire', 'maintenance',
             'enmity', 'ample', 'bridegroom', 'survived', 'foot', 'hearers', 'ranger',
             'pretence', 'fierce', 'exhortations', 'boldly', 'couch', 'Rail', 'piety',
             'rages', 'suing', 'slain', 'intends', 'ivy', 'no', 'waver', 'dipping',
             'pained', 'absolutely', 'betray', 'lead', 'anywhere', 'Long', 'Chose',
             'extraordinary', 'prophetic', 'regarded', 'approaching', 'yore', 'loveth',
             'hands', 'internal', 'Gods', 'shield', 'enemies', 'watching', 'Muse',
             'Please', 'fulfil', 'Such', 'measured', 'follows', 'precinct', 'strange',
             'lore', 'delicate', 'cloudy', 'brazen', 'care', 'borrowed', 'glow',
             'decided', 'asking', 'lest', 'night', 'chiefly', 'half', 'somewhere',
             'time', 'homeward', 'borne', 'winged', 'Often', 'touching', 'wounds',
             'true', 'answering', 'threatened', 'rare', 'inclination', 'warned', 'god',
             'Where', 'grow', 'flights', 'honest', 'Thyself', 'Alas', 'Sweet', 'natural',
             'truest', 'prophecy', 'task', 'altogether', 'bless', 'youthful',
             'compounded', 'Nobody', 'setting', 'dissembled', 'fray', 'kneels',
             'opposed', 'stays', 'endless', 'decide', 'acres', 'Aeacus', 'offering',
             'Bid', 'Trojan', 'poverty', 'store', 'overshadowed', 'decketh', 'it',
             'pleasure', 'stronger', 'flame', 'Iôlcos', 'little', 'nearer', 'intimation',
             'unconscious', 'wake', 'falter', 'Longing', 'select', 'Rested',
             'chambering', 'scene', 'cared', 'slanderously', 'inevitable', 'vaulted',
             'understand', 'turn', 'appearance', 'evidence', 'whether', 'smiling',
             'would', 'bid', 'ease', 'Prevailing', 'counted', 'bliss', 'common',
             'craftsmen', 'inflicted', 'separate', 'admitted', 'steps', 'guiding',
             'sense', 'gifted', 'arrives', 'yearly', 'Unless', 'pretty', 'listen',
             'joined', 'stranger', 'nurture', 'serve', 'older', 'salt', 'its', 'their',
             'kept', 'suitable', 'alive', 'ago', 'impudence', 'fly', 'comrade',
             'firmament', 'placed', 'handmaids', 'thereupon', 'dearest', 'talked',
             'migration', 'spurned', 'wreck', 'bring', 'Beneath', 'blaspheming',
             'wanting', 'claps', 'with', 'nailed', 'utter', 'difficult', 'Critobulus',
             'stir', 'Symplêgades', 'improves', 'Leon', 'pride', 'breeze', 'course',
             'princess', 'imputed', 'These', 'noblest', 'you', 'deem', 'Defeat',
             'softness', 'opened', 'avail', 'deprive', 'far', 'forth', 'ATTENDANT',
             'perisheth', 'anything', 'escape', 'earnest', 'knowest', 'perils', 'king',
             'What', 'scarcely', 'Of', 'wayfarings', 'wit', 'helped', 'whence',
             'overpower', 'I', 'never', 'Be', 'ashamed', 'Betray', 'backward', 'times',
             'seeing', 'senses', 'Hesiod', 'passeth', 'place', 'implicating', 'converse',
             'most', 'lingering', 'shelter', 'hath', 'sets', 'Delphi', 'grudge',
             'hereafter', 'If', 'plot', 'requires', 'said', 'MEDEA', 'smooth', 'matters',
             'healing', 'hunted', 'savage', 'sleep', 'hire', 'Three', 'Until',
             'Arranged', 'estimate', 'greater', 'disturbance', 'marked', 'agonies',
             'engaged', 'contrast', 'encompass', 'flieth', 'lands', 'cause', 'wheel',
             'Then', 'Skylla', 'Art', 'sword', 'save', 'using', 'stored', 'griefs',
             'proof', 'station', 'taken', 'must', 'waves', 'dangerous', 'wedded',
             'heals', 'mood', 'perfect', 'planned', 'acknowledge', 'accused', 'accusers',
             'land', 'seldom', 'verily', 'Well', 'haters', 'wings', 'kind', 'walks',
             'up', 'masters', 'set', 'Forth', 'clean', 'face', 'grovelled', 'divinity',
             'cruel', 'grown', 'impiety', 'men', 'round', 'count', 'robe', 'unexamined',
             'glad', 'blessing', 'poor', 'drew', 'concern', 'Provisionless', 'allowed',
             'fiery', 'wait', 'bards', 'comfort', 'barred', 'limbs', 'moans', 'repent',
             'seas', 'unintentional', 'Whatso', 'sheer', 'propose', 'pace', 'wakes',
             'behind', 'ear', 'payment', 'minds', 'wood', 'remainder', 'stealeth',
             'Loose', 'harvest', 'steep', 'confess', 'magistrates', 'pent', 'Love',
             'feel', 'Vision', 'block', 'sicknesses', 'dwells', 'fairly', 'port',
             'spill', 'givest', 'obedient', 'sleeping', 'Corinth', 'Seeing', 'Beyond',
             'refutation', 'short', 'kissed', 'cheated', 'deteriorating', 'Shaped',
             'hap', 'leave', 'bear', 'termed', 'fifth', 'wed', 'how', 'graves', 'swell',
             'between', 'gained', 'brook', 'eat', 'Rhadamanthus', 'extracted',
             'Athenian', 'Wert', 'facetious', 'lost', 'play', 'want', 'sent', 'some',
             'value', 'conclusion', 'art', 'majesties', 'sworn', 'notions', 'am',
             'least', 'shut', 'man', 'bride', 'sundry', 'But', 'convict', 'devouring',
             'fancy', 'days', 'hallowed', 'Does', 'lacking', 'lifteth', 'cry', 'lasted',
             'able', 'fitting', 'convinced', 'dares', 'More', 'prevent', 'vintage',
             'pilot', 'become', 'needs', 'conceive', 'foam', 'wiser', 'philosophers',
             'told', 'You', 'strangest', 'strong', 'Tread', 'suns', 'warrant', 'future',
             'several', 'delight', 'drag', 'heed', 'Shall', 'across', 'Evil', 'lawless',
             'standing', 'godlike', 'condemn', 'garments', 'yielded', 'these', 'fling',
             'twine', 'Parian', 'jointing', 'reward', 'torn', 'sufficient',
             'instruction', 'At', 'friends', 'thy', 'Red', 'tidings', 'Themis', 'can',
             'joyful', 'order', 'elevates', 'road', 'throat', 'Though', 'fain', 'found',
             'living', 'Dire', 'poising', 'Hill', 'above', 'apart', 'broken', 'saying',
             'Scarce', 'Tell', 'beautiful', 'examining', 'kings', 'just', 'Shrieking',
             'followed', 'friendless', 'our', 'faster', 'good', 'rotunda', 'daughters',
             'scattered', 'elder', 'rouse', 'tower', 'stone', 'helplessness', 'clasped',
             'Chaerephon', 'gnawing', 'interrupt', 'shame', 'After', 'pilgrim', 'did',
             'chance', 'speech', 'steed', 'injurer', 'Strong', 'willing', 'hatred',
             'gathered', 'mother', 'false', 'neither', 'yokes', 'arisen', 'dreameth',
             'too', 'weak', 'Ever', 'died', 'disgraceful', 'injustice', 'unless',
             'ready', 'soldiers', 'sung', 'winds', 'back', 'seed', 'condition', 'base',
             'women', 'Methinks', 'office', 'baffle', 'New', 'doctrine', 'Show',
             'compelled', 'Good', 'ignorant', 'deceived', 'Twice', 'help', 'mean',
             'reckless', 'amongst', 'naked', 'reply', 'aims', 'walls', 'flew', 'abate',
             'knees', 'granted', 'tremble', 'desire', 'stab', 'concerning', 'passes',
             'dole', 'pitiless', 'produced', 'Athens', 'proved', 'flock', 'maids', 'Bar',
             'Green', 'part', 'denounce', 'worth', 'justly', 'both', 'savagery',
             'Mocked', 'argue', 'Would', 'Much', 'Salamis', 'later', 'paced', 'thought',
             'fetch', 'Perhaps', 'passages', 'anyone', 'prove', 'cling', 'doom', 'useth',
             'assuredly', 'neighbours', 'Blue', 'companion', 'inmost', 'gadfly', 'cries',
             'draughts', 'lay', 'simple', 'Atonement', 'daily', 'hunt', 'respect',
             'judges', 'Touching', 'Wherefore', 'unjustly', 'fleece', 'somebody',
             'pleasantly', 'interests', 'produce', 'enquire', 'end', 'ruined', 'dooms',
             'favour', 'contradict', 'leaving', 'chambers', 'behalf', 'improver',
             'clashing', 'concerns', 'bosoms', 'full', 'deceive', 'bitterness', 'Nine',
             'Athenians', 'Granted', 'reach', 'raging', 'aught', 'single', 'Help',
             'Meseems', 'rest', 'returned', 'tender', 'chimes', 'My', 'spiritual',
             'straight', 'specimen', 'self', 'purge', 'over', 'remained', 'used',
             'years', 'receiving', 'eloquence', 'changed', 'was', 'hour', 'shaking',
             'work', 'calls', 'risen', 'Thought', 'Within', 'Unfathered', 'particular',
             'shed', 'Musaeus', 'stands', 'wakened', 'whereas', 'figure', 'superior',
             'profiteth', 'feet', 'here', 'arts', 'devisers', 'knew', 'mention', 'Pray',
             'brides', 'once', 'happened', 'corrupter', 'motive', 'NURSE', 'ice',
             'chariots', 'lonely', 'Accordingly', 'trial', 'rich', 'whom', 'righted',
             'Hath', 'bed', 'moderate', 'fruit', 'scent', 'home', 'teaching', 'riseth',
             'Young', 'ones', 'searched', 'diest', 'sufficiently', 'in', 'wrought',
             'Stand', 'bond', 'aileth', 'wailing', 'hardihood', 'list', 'Die',
             'inflicting', 'atheist', 'escaped', 'trusty', 'Most', 'wealth', 'desolate',
             'invented', 'see', 'votes', 'pallor', 'Meletus', 'declare', 'further',
             'incurred', 'possession', 'prophetess', 'Toward', 'doleful', 'prosperous',
             'Whereby', 'anger', 'troubleth', 'Friend', 'oration', 'searching', 'needed',
             'against', 'meet', 'command', 'them', 'rear', 'inveterate', 'bears',
             'lessons', 'wisest', 'nevertheless', 'heart', 'about', 'essay',
             'counselled', 'ways', 'moment', 'Doubtless', 'iron', 'passions', 'study',
             'Lysanias', 'jealous', 'exactly', 'Mine', 'Awakening', 'headed', 'O',
             'herb', 'gaze', 'therefor', 'amain', 'inclined', 'refuse', 'Am', 'let',
             'Happy', 'money', 'Me', 'wanderings', 'flesh', 'die', 'moon', 'armed',
             'saved', 'smell', 'clustering', 'brethren', 'seemed', 'litten', 'sovranty',
             'terrible', 'understanding', 'wooing', 'bravest', 'shadows', 'fold', 'gave',
             'mankind', 'mistress', 'passage', 'gift', 'cognizance', 'convicted', 'dews',
             'diverse', 'take', 'bad', 'hast', 'train', 'juvenile', 'prophesy',
             'draweth', 'lamps', 'procured', 'misleader', 'Set', 'Unstrivingly', 'curse',
             'degree', 'owing', 'marred', 'bent', 'Our', 'infer', 'admission', 'soul',
             'Ill', 'Word', 'ill', 'heaven', 'public', 'move', 'Virgin', 'permitted',
             'fine', 'eminent', 'sorry', 'thrown', 'Ah', 'according', 'much', 'heaping',
             'soon', 'impeach', 'richer', 'real', 'knows', 'angry', 'your', 'Some',
             'Deaf', 'sweep', 'wrath', 'Send', 'detractors', 'bore', 'Orpheus',
             'forward', 'pretensions', 'prayer', 'remain', 'lover', 'Turn', 'something',
             'uttered', 'chief', 'question', 'character', 'doer', 'Made', 'court',
             'Maybe', 'slightly', 'shores', 'wills', 'blade', 'Blast', 'lion', 'gain',
             'throw', 'maladies', 'result', 'fastening', 'although', 'strength',
             'forget', 'maiden', 'sleepeth', 'dreams', 'free', 'girl', 'appease',
             'befool', 'equal', 'knowledge', 'Waste', 'All', 'than', 'Soon', 'Mock',
             'wall', 'tardy', 'Thirty', 'CREON', 'welcomed', 'out', 'friend', 'accept',
             'Fine', 'fancying', 'thinking', 'still', 'opponents', 'prospering',
             'incarnate', 'younger', 'cloud', 'requite', 'nigh', 'appeared', 'In',
             'riven', 'telling', 'view', 'memories', 'Go', 'dangers', 'agencies',
             'chose', 'immediately', 'hoarded', 'sailed', 'wrong', 'poisons', 'Never',
             'olden', 'proper', 'faculty', 'doctrines', 'giving', 'charge', 'student',
             'fail', 'grey', 'Upon', 'Because', 'Among', 'woe', 'make', 'finding',
             'listening', 'likely', 'east', 'explanation', 'speak', 'reck', 'voices',
             'womb', 'cheek', 'tale', 'weariest', 'entreated', 'Hippias', 'stormy',
             'poison', 'Halls', 'Bleeding', 'interesting', 'arrived', 'bowing', 'if',
             'easier', 'please', 'wondering', 'yoke', 'summers', 'him', 'upbuild',
             'chamber', 'of', 'surpassing', 'frighten', 'fed', 'burn', 'loathliness',
             'searches', 'Here', 'lack', 'Heaven', 'talking', 'palter', 'divine',
             'advise', 'known', 'Plato', 'tread', 'force', 'None', 'Straightway',
             'World', 'we', 'interfere', 'knowing', 'serious', 'reason', 'pains',
             'examine', 'onward', 'Seeketh', 'farmer', 'laurel', 'falsehoods', 'danger',
             'Prayed', 'idle', 'shuddering', 'lord', 'beguiled', 'secret', 'write',
             'virtue', 'King', 'dividing', 'winging', 'making', 'Hangs', 'clinging',
             'Other', 'disabling', 'Think', 'fasting', 'gather', 'unspeakable',
             'artisans', 'Hast', 'unsounded', 'link', 'utterly', 'earn', 'Swear',
             'temper', 'On', 'woman', 'lift', 'sort', 'Oft', 'word', 'rotting', 'avoid',
             'intent', 'at', 'Flesh', 'slew', 'attached', 'Dead', 'endeavour',
             'eternity', 'detraction', 'Are', 'beget', 'admonished', 'relate', 'forlorn',
             'instruct', 'second', 'examined', 'sin', 'mission', 'abide', 'ring',
             'speaker', 'Surely', 'stand', 'heavy', 'considerable', 'speculate',
             'stabbing', 'vow', 'clogged', 'infinite', 'fears', 'befriend', 'delivered',
             'Antiphon', 'poured', 'linger', 'motions', 'tarrying', 'yield', 'loath',
             'steeped', 'eastern', 'fetched', 'slip', 'aforesaid', 'Clearly', 'do',
             'slay', 'breathing', 'walker', 'his', 'forgive', 'Against', 'trampled',
             'senators', 'down', 'wished', 'customary', 'trample', 'many', 'Shows',
             'wronged', 'expect', 'challenge', 'run', 'departure', 'sheltered',
             'Fortune', 'neglect', 'enough', 'laid', 'Wrath', 'Dost', 'Therefore', 'one',
             'impetuous', 'detected', 'wasteth', 'wonderful', 'shrinking', 'others',
             'misery', 'victory', 'Peace', 'persons', 'pale', 'manner', 'From', 'permit',
             'offended', 'condemned', 'lingers', 'prize', 'merrier', 'Gone', 'Minos',
             'privately', 'Doth', 'require', 'words', 'score', 'rate', 'succour',
             'plainer', 'serves', 'dare', 'native', 'thyself', 'awakened', 'crown',
             'Held', 'brother', 'gash', 'blithe', 'streams', 'they', 'underneath',
             'blinding', 'unjust', 'strove', 'excuse', 'Did', 'Attic', 'defect',
             'battering', 'With', 'probably', 'waits', 'longed', 'footstep', 'Wilt',
             'dwell', 'careless', 'May', 'done', 'perished', 'attend', 'Fire', 'blinded',
             'shalt', 'crooked', 'touch', 'have', 'contains', 'sends', 'ever', 'arm',
             'shrieking', 'seeking', 'account', 'horse', 'calculate', 'An', 'prouder',
             'bids', 'avenged', 'forever', 'edge', 'naught', 'quick', 'unknown',
             'people', 'father', 'difficulty', 'method', 'bridal', 'nonsense', 'get',
             'mad', 'Fond', 'pure', 'manifold', 'join', 'bursts', 'hero', 'helping',
             'caring', 'hardest', 'ludicrous', 'nearly', 'welcome', 'Enough', 'uplift',
             'generally', 'frozen', 'unnatural', 'burned', 'young', 'gat', 'Passion',
             'triple', 'low', 'advice', 'pine', 'Clung', 'stem', 'gentle', 'claim',
             'exhorting', 'guide', 'daemons', 'improving', 'long', 'refute', 'mildly',
             'feared', 'wilder', 'shattered', 'gifts', 'advantage', 'forsake', 'guard',
             'horses', 'bared', 'Ere', 'ope', 'quickly', 'runner', 'withal', 'lifted',
             'Fair', 'Man', 'matter', 'fell', 'ignorance', 'hunger', 'bleed', 'heareth',
             'proceed', 'diviners', 'put', 'cover', 'fallen', 'began', 'bold', 'human',
             'seen', 'hitherto', 'visage', 'direr', 'disobeyed', 'physical', 'sweet',
             'thus', 'ordered', 'hate', 'yes', 'opposing', 'spirit', 'Yester',
             'unblinded', 'drifting', 'royal', 'Furled', 'pressed', 'angrier', 'He',
             'undone', 'prefers', 'suddenly', 'harbour', 'Lead', 'he', 'comparison',
             'hold', 'fool', 'tell', 'Past', 'demigods', 'politician', 'Queen', 'gets',
             'Wastes', 'stayed', 'address', 'intended', 'labouring', 'corrupt', 'harm',
             'graceless', 'very', 'lust', 'supposing', 'support', 'Nicostratus',
             'extent', 'alter', 'contrary', 'should', 'remind', 'frame', 'forgot',
             'doing', 'comparing', 'runs', 'till', 'heels', 'vindication', 'elders',
             'paid', 'use', 'By', 'armour', 'cold', 'cheer', 'assistance', 'sting',
             'bow', 'afterwards', 'His', 'expected', 'inconsiderate', 'curls', 'Than',
             'Which', 'thankful', 'fairest', 'sit', 'might', 'has', 'displeased',
             'breath', 'laughing', 'Grey', 'aid', 'Peliad', 'state', 'any', 'bulls',
             'professed', 'Life', 'weepest', 'therefore', 'strike', 'defend', 'thee',
             'instead', 'Till', 'catches', 'refrain', 'green', 'hence', 'every', 'teeth',
             'changing', 'goodly', 'Canst', 'illegitimate', 'lightly', 'godless',
             'crafts', 'sure', 'Know', 'imagine', 'Hold', 'thine', 'only', 'again',
             'thing', 'sail', 'resolution', 'easy', 'ears', 'loud', 'shining', 'Could',
             'released', 'lives', 'Greece', 'Above', 'oath', 'Thou', 'torture', 'nature',
             'power', 'suppose', 'civil', 'throne', 'uncontrollable', 'encouraged',
             'orders', 'capital', 'unfair', 'fearing', 'thinks', 'led', 'yourselves',
             'considered', 'dancing', 'among', 'chime', 'trust', 'heel', 'Jason',
             'receive', 'families', 'voice', 'Unloose', 'prosecuted', 'forgotten',
             'oppressive', 'stopped', 'livest', 'reeking', 'Those', 'hot', 'next',
             'sees', 'own', 'within', 'wonder', 'standeth', 'brings', 'thither', 'grave',
             'For', 'then', 'sum', 'meeting', 'until', 'God', 'mere', 'two', 'return',
             'pushed', 'Somewhere', 'Odysseus', 'five', 'stained', 'live', 'pretenders',
             'repeat', 'weds', 'sanctities', 'Folded', 'moved', 'keep', 'Strength',
             'Were', 'pretends', 'like', 'plant', 'Shame', 'chide', 'ambitious',
             'whatso', 'exacted', 'suffered', 'reasoned', 'Tempts', 'oaths', 'went',
             'keen', 'foreign', 'mocking', 'heavier', 'post', 'through', 'determined',
             'tend', 'always', 'choice', 'drawn', 'goeth', 'proposed', 'kiss', 'change',
             'cavilling', 'persuasion', 'fled', 'array', 'fair', 'Thine', 'beg',
             'children', 'sorrow', 'esteemed', 'heard', 'cloak', 'Sire', 'disparagingly',
             'mouth', 'allusion', 'Out', 'recent', 'amusement', 'happier', 'air',
             'peace', 'appear', 'age', 'yonder', 'try', 'weapon', 'Spurn', 'robings',
             'light', 'Should', 'despise', 'shouldst', 'Whether', 'arraigned', 'cometh',
             'deeds', 'pain', 'Call', 'fret', 'didst', 'check', 'Closed', 'passion',
             'brought', 'savageness', 'cross', 'Too', 'truth', 'sift', 'tears',
             'obedience', 'enquirers', 'reproved', 'casteth', 'sundering', 'overtaken',
             'Olympia', 'believing', 'except', 'greatest', 'maid', 'wild', 'Others',
             'mortals', 'lap', 'off', 'queen', 'princely', 'prayed', 'discover',
             'drowned', 'wife', 'compare', 'thirst', 'news', 'Every', 'bright',
             'kinsman', 'flying', 'injured', 'fitful', 'Quick', 'throwing', 'soft',
             'Innocence', 'thousand', 'baulk', 'stop', 'worthy', 'surprised', 'gnash',
             'mass', 'having', 'longs', 'repute', 'opposite', 'villainous', 'Tigress',
             'surges', 'bound', 'Lords', 'Even', 'Say', 'introduced', 'noble', 'Shot',
             'deal', 'spare', 'succeed', 'glory', 'Groping', 'individually', 'clouds',
             'sky', 'eye', 'buy', 'Wed', 'overvaluing', 'robes', 'ran', 'continue',
             'thoughts', 'promised', 'Age', 'is', 'brown', 'Acre', 'on', 'ye', 'names',
             'persuaded', 'dared', 'perhaps', 'Not', 'unmake', 'persuading', 'direst',
             'persuasively', 'groaning', 'laugh', 'spilled', 'nights', 'disseminators',
             'sire', 'Husband', 'hide', 'bruised', 'arguments', 'lose', 'worse',
             'persuade', 'grantest', 'girt', 'audience', 'existence', 'succouring',
             'confounded', 'befall', 'merry', 'Motherless', 'leisure', 'Welcome',
             'occupation', 'CHILDREN', 'homeliest', 'Tuscan', 'drear', 'as', 'bind',
             'crafty', 'easiest', 'forsook', 'thou', 'Many', 'Chattels', 'accusations',
             'proportion', 'wave', 'dart', 'brothers', 'absorbs', 'weeping', 'Best',
             'Hitherto', 'brows', 'happen', 'dragged', 'Comic', 'fame', 'goddess',
             'bread', 'judgment', 'dog', 'Henceforth', 'poets', 'coming', 'sires',
             'bitterest', 'came', 'majority', 'depart', 'tortured', 'Anytus', 'Stay',
             'glen', 'forsaking', 'greet', 'raising', 'elaborate', 'given', 'mire',
             'fact', 'Loathe', 'duty', 'cannot', 'breaking', 'clasping', 'requited',
             'When', 'path', 'grievous', 'reputation', 'Hereafter', 'signified', 'Speak',
             'web', 'This', 'interrogate', 'pardon', 'harsher', 'behaving', 'encourage',
             'share', 'poetry', 'professors', 'person', 'guards', 'Child', 'trampling',
             'A', 'wend', 'batter', 'coward', 'compared', 'Betraying', 'residing',
             'cease', 'profits', 'recognized', 'blue', 'Your', 'dust', 'scathe',
             'breaks', 'calumny', 'oracle', 'Turned', 'duly', 'lived', 'divinities',
             'traveller', 'accuse', 'whichever', 'sake', 'commit', 'Spill', 'Swift',
             'exact', 'affirmed', 'gleam', 'disposed', 'wet', 'Both', 'teaches', 'yet',
             'portion', 'exception', 'life', 'marriage', 'accusation', 'will',
             'strangely', 'practice', 'Medea', 'wide', 'refer', 'and', 'drachma',
             'bounden', 'hope', 'claws', 'estimated', 'particle', 'canst', 'wilt',
             'learning', 'height', 'afraid', 'succours', 'purpose', 'moan', 'need',
             'present', 'pray', 'Thinking', 'show', 'Being', 'Awake', 'wasted',
             'threats', 'encaverned', 'proposes', 'best', 'Longer', 'illiterate',
             'malice', 'hand', 'trainer', 'theatre', 'wince', 'learned', 'strain',
             'weaken', 'barbarian', 'sicken', 'Guideth', 'spirits', 'Shunning',
             'fathers', 'Creon', 'anchor', 'without', 'foul', 'calleth', 'lamented',
             'Phoebus', 'confident', 'small', 'house', 'Kissed', 'philosopher', 'parted',
             'adjure', 'Bit', 'better', 'affidavit', 'beyond', 'steal', 'weep', 'So',
             'dishonour', 'flash', 'recovers', 'called', 'conscious', 'Why', 'laboured',
             'speculated', 'scorn', 'born', 'deed', 'Move', 'commands', 'sore',
             'inasmuch', 'sate', 'eyes', 'zeal', 'She', 'powers', 'joy', 'Faith',
             'sought', 'Anaxagoras', 'returns', 'unlike', 'manward', 'clear', 'members',
             'durst', 'know', 'wanted', 'sins', 'observed', 'reflect', 'creature',
             'blind', 'strife', 'hideously', 'plenty', 'louder', 'silence', 'provokes',
             'whole', 'had', 'observes', 'gum', 'superhuman', 'sign', 'helm', 'affected',
             'say', 'righteous', 'blame', 'Will', 'rooms', 'enquiry', 'deserved',
             'villainy', 'ache', 'Has', 'besides', 'stern', 'folds', 'herbs', 'Envy',
             'Potidaea', 'To', 'appears', 'sorts', 'stirred', 'LEADER', 'rise',
             'troubled', 'Pythian', 'seems', 'propriety', 'deck', 'intimated', 'witness',
             'walk', 'Save', 'choose', 'sudden', 'moving', 'rage', 'plainness', 'Whom',
             'falsely', 'wind', 'seal', 'written', 'unrighteous', 'perish', 'Very',
             'mortal', 'Pan', 'convince', 'shrivelled', 'or', 'seated', 'Once', 'turned',
             'behest', 'alliance', 'slow', 'Wrench', 'Paralus', 'lips', 'treasures',
             'sweepeth', 'speaking', 'Run', 'couldst', 'No', 'were', 'arms', 'places',
             'same', 'Aristophanes', 'improve', 'admit', 'such', 'Colchis', 'darkness',
             'hearth', 'veriest', 'reprove', 'envy', 'Attendants', 'certain', 'magic',
             'privily', 'seek', 'wondrous', 'pretend', 'hidden', 'Euripides', 'brand',
             'allow', 'earth', 'hears', 'Pelion', 'talk', 'arrest', 'Since', 'swift',
             'gathers', 'law', 'go', 'quest', 'weigh', 'Mad', 'accusing', 'four',
             'mischievous', 'Now', 'twain', 'craved', 'dame', 'citing', 'continually',
             'especially', 'Achilles', 'destruction', 'mightiest', 'devotion', 'dim',
             'child', 'Can', 'higher', 'few', 'thorn', 'understands', 'tenderness',
             'shore', 'irrational', 'Gladly', 'uncorrupted', 'who', 'rang', 'kneel',
             'golden', 'Thetis', 'appearing', 'judge', 'anguished', 'instantly',
             'almost', 'gone', 'believe', 'draw', 'necessity', 'Adeimantus', 'grace',
             'prejudice', 'themselves', 'ere', 'acquit', 'right', 'shown', 'Nothing',
             'shortly', 'surmise', 'win', 'wantonness', 'be', 'Mother', 'wise',
             'Henceforward', 'seducing', 'hated', 'placing', 'impressible', 'crag', 'Or',
             'leader', 'reared', 'haunteth', 'chosen', 'House', 'slave', 'generals',
             'immortal', 'torches', 'Bear', 'give', 'wandering', 'vile', 'guilt',
             'Better', 'undisturbed', 'looked', 'darling', 'offence', 'ornamented',
             'even', 'tried', 'enemy', 'Is', 'waiting', 'world', 'holds', 'weary',
             'bleeds', 'why', 'song', 'charges', 'comest', 'sunshine', 'brief', 'a',
             'roll', 'habit', 'Forgotten', 'Resteth', 'desperate', 'That', 'host',
             'language', 'amazed', 'handmaid', 'laws', 'first', 'Broken', 'enmities',
             'taking', 'odious', 'Sick', 'rid', 'while', 'tribe', 'Salaminian', 'And',
             'plain', 'nothingness', 'sow', 'unworthy', 'discourse', 'amount',
             'procuring', 'treasure', 'Earth', 'Guyana', 'Egypt', 'Namibia', 'Niger',
             'Heavens', 'Iraq', 'Angola', 'India', 'Myanmar', 'Japan', 'Mali',
             'Indonesia', 'Sudan', 'China', 'Tajikistan', 'Paraguay', 'Algeria',
             'Venezuela', 'Argentina', 'Central', 'Uganda', 'Mongolia', 'Bolivia',
             'Russia', 'Finland', 'Chad', 'Zambia', 'Morocco', 'Laos', 'Bangladesh',
             'Oman', 'Ethiopia', 'Kenya', 'Raskolnikov.', 'Zimbabwe', 'Turkmenistan',
             'France', 'Brazil', 'Congo', 'Pakistan', 'Mozambique', 'Pestryakov.',
             'Ghana', 'Romania', 'Tanzania', 'Uzbekistan', 'Colombia', 'Suriname',
             'Uruguay', 'DR', 'Vietnam', 'Norway', 'Botswana', 'Turkey', 'Kazakhstan',
             'Germany', 'Ukraine', 'Nepal', 'Australia', 'Greece', 'Gabon', 'Senegal',
             'Nigeria', 'Cambodia', 'Incoherently.', 'Denmark', 'Tunisia', 'Afghanistan',
             'Iran', 'Madagascar', 'Mexico', 'Mauritania', 'Razumihin.', 'Spain',
             'Somalia', 'Canada', 'Malawi', 'Sweden', 'Philippines', 'Syria', 'Guinea',
             'Exclaiming.', 'Ecuador', 'Poland', 'Eritrea', 'Italy', 'Cameroon',
             'Nicaragua', 'Yemen', 'Chile', 'Belarus', 'Libya', 'Mournfully.', 'Peru',
             'Malaysia', 'Thailand', 'Kyrgyzstan', 'Hum', 'Surely', 'Now', 'Nothing',
             'Dr', 'Brother', 'Then', 'Ah', 'Grete', 'Swales', 'Buda', 'Pesth', 'Still',
             'Miss', 'Colin', 'Clay', 'Honours', 'Unfortunately', 'Dear', 'Pooh', 'Too',
             'However', 'Contemptuously', 'Hold', 'God', 'Fly', 'How', 'This', 'Etc',
             'Come', 'Windibank', 'Application', 'Juchheisa', 'Really', 'Certainly',
             'Why', 'sweet', 'Samsa', 'Phipps', 'Fools', 'Devilpaper', 'Smiling', 'None',
             'What', 'Thanks', 'Eh', 'Finally', 'Perseverance', 'Say', 'MORRIS',
             'Brethren', 'Lemon', 'Etherege', 'Where', 'For', 'Please', 'Cordially',
             'Doctor', 'Secrecy', 'Take', 'MRS', 'Gertrude', 'Ha', 'Watson', 'Blitz',
             'Esq', 'Jones', 'Glory', 'Back', 'Here', 'Wilson', 'Roman', 'Owing',
             'Father', 'bye', 'Planing', 'Gentlemen', 'Mina', 'Airily', 'Orange',
             'Heathcoat', 'Cheveley', 'Juchhe', 'Mrs', 'Except', 'Sharp', 'Quick',
             'Again', 'Suavely', 'Peel', 'Presently', 'Study', 'Peasants', 'Bah', 'Who',
             'Good', 'Forgery', 'Brick', 'Selfishness', 'Sir', 'Methinks', 'Honey',
             'Robert', 'John', 'Faugh', 'Thoughtfully', 'Vienna', 'Nay', 'Naturally',
             'That', 'Power', 'Mephistopheles', 'Besides', 'Well', 'Liver', 'Wagner',
             'Merryweather', 'setter', 'There', 'Weak', 'When', 'Hammering', 'Smooth',
             'Others', 'Kepler', 'He', 'Irish', 'But', 'Child', 'Christ', 'Once',
             'Style', 'No', 'Struck', 'Heisa', 'Perhaps', 'Cobden', 'Laughing', '000',
             'Stone', 'Ample', 'Cigar', 'Faust', 'London', 'Murat', 'Little', 'Laughing',
             'Dishonest', 'Oh', 'CHEVELEY', 'Student', 'If', 'About', 'Count',
             'Excitedly', 'Adrian', 'Though', 'PHIPPS', 'Parchment', 'So', 'Jonathan',
             'Arthur', 'Turner', 'Holmes', 'Indeed', 'Bankers', 'Mr', 'Bazley',
             "D'Alembert", 'Alas', 'Monica', 'Work', 'And', 'Ostlers', 'Sadly', 'Pshaw',
             'Lestrade', 'Yes', 'Rising', 'Wife']
