"""
Imported by `cpt_config.py` for use in the Tkinter GUI.

Variable:
    words_two (list): Single words for 10-25 second portion of typing test.
"""

# Two-word strings for 10-20 second portion of typing test.
words_two = ['the water', 'burnt green', 'and cried', 'a sail', 'a sail', 'but oh',
             'seven days', 'seven nights', 'ancient mariner', 'be calm',
             'thou wedding-guest', 'quoth one', 'more high', 'go on', 'my boy',
             'and energy', 'he added', 'he exclaimed', 'for example', 'our food',
             'our clothing', 'impelling ships', 'grinding corn', 'printing books',
             'stamping money', 'in short', 'steps forward', 'in 1605', 'these discs',
             'not words', 'what notes', 'whither bound', 'the other', 'a burgher',
             'one angle', 'you see', 'nor fear', 'if then', 'as now', 'as here',
             "ev'n now", 'no trees', 'encheiresis naturæ', 'and now', 'said he',
             'he cried', 'what then', 'i asked', 'said he', 'and now', 'i asked',
             "irene's photograph", 'he cried', 'and endeavored', 'but china',
             'are eligible', 'very good', 'i presume', "' ‘why", "' ‘certainly",
             'jabez wilson', 'said he', 'shabby-genteel place', 'which are',
             'tearing sound', 'gaping hole', 'i asked', 'bald enough', 'said he',
             'or grieved', 'your father', 'said holmes', 'your step-father', 'of course',
             'she said', 'hosmer angel', 'and mr', 'i understand', 'not invisible',
             'but unnoticed', 'anybody bringing', 'you see', 'james windibank',
             'said holmes', 'he said', 'said holmes', 'then mr', 'the glasses',
             'the voice', 'i answered', 'charles mccarthy', 'answered holmes',
             'james mccarthy', 'the 3rd', "' ‘yes", 'and this', 'said holmes',
             'sinewy neck', 'he remarked', 'in fact', 'lady chiltern', 'lady chiltern',
             'write here', 'enter mason', 'lord goring', 'damned scoundrel',
             'lord goring', 'lord goring', 'is mr', "doesn't she", 'lord goring',
             'lord goring', 'thank you', 'lady chiltern', 'lord goring', 'have you',
             'lord goring', 'dear gertrude', 'lord goring', 'lord goring', 'quite sharp',
             'lady markby', 'would one', 'some tea', 'lady markby', 'lady markby',
             'just slightly', 'lady chiltern', 'believe me', 'of course',
             'lady chiltern', 'my worst', 'my lord', 'lord goring', 'poor woman',
             'poor woman', 'no draught', 'i hope', 'lord goring', 'lord caversham',
             'its change', 'its death', 'but how', 'said i', 'the long', 'peter hawkins',
             'dirty sheepskin', 'shortly afterwards', 'and british', 'and austrian',
             'and hungarian', 'my friend', 'he smiled', 'he proceeded', '9 may',
             'just fancy', 'good-night again', 'i know', "don't cry", 'my dear',
             'therefore r', 'arthur holmwood', 'he is', 'ye can', 'my pretty',
             "seward's diary", '26 july', 'he thought', 'for instance', 'for instance',
             'as well', 'he seemed', 'of course', "gregor's mother", 'said gregor',
             'but now', 'no-one came', 'of course', "what's happened", 'but still',
             'ah wretch', 'said they', 'well a-day', '(thought i', 'fear not',
             'fear not', 'thou wedding-guest', 'it ceased', 'the pang', 'the curse',
             'a seraph-man', 'warren hastings', 'arrived there', 'and declared',
             'to hunt', 'and shoot', 'to paris', 'or rome', 'retire dejected',
             'chapter ii', 'at cromford', 'in derbyshire', 'never mind', '& co',
             'his protector', 'late m', 'a fifth', 'another burgher', 'old peasant',
             "that's all", 'hover here', 'hover there', 'of honour', 'and servant',
             'curst when', 'or brass', 'or chisel', 'alternate chime', 'poor boy',
             'three years', 'god knows', "john's wood", 'well furnished',
             'talking excitedly', 'which are', 'he answered', 'he said', 'he said',
             'we descended', 'you  know', 'he said', 'i know', 'in addition',
             'holmes chuckled', 'sherlock holmes', 'cried holmes', 'near st', 'you are',
             'said holmes', 'said holmes', 'you see', 'said jones', 'with deference',
             'he whispered', 'said jones', 'you see', 'he explained', 'the cellar',
             'oh yes', 'oh no', 'with me', 'describe it', 'hosmer angel', 'he continued',
             'said holmes', 'james windibank', 'a lean', 'ferret-like man', 'no wind',
             'in victoria', 'said lestrade', 'marshy ground', 'he asked', 'he said',
             'and now', 'i have', 'mccarthy threatened', 'lord goring', 'lady chiltern',
             '] gertrude', 'drift apart', 'lady chiltern', 'lady chiltern',
             '[exit mason', 'lord goring', 'lord goring', 'lord goring', 'lord goring',
             'lord goring', '] oh', 'perhaps mrs', 'lady chiltern', 'lord goring',
             "shan't i", 'lord goring', 'lady chiltern', 'lady chiltern', 'lord goring',
             'lord goring', 'lord goring', "don't forget", 'so much', 'lord goring',
             'mabel chiltern', 'mabel chiltern', 'lady markby', 'miss chiltern',
             'lady chiltern', '[enter mason', 'lady markby', 'lady chiltern',
             'lady markby', "james's street", 'or perhaps', 'dear mrs', 'dear gertrude',
             'i forgot', 'their follies', 'their imperfections', 'and so', 'ruined it',
             'my lord', '] phipps', 'lord caversham', '[sitting down', 'lord caversham',
             'lord goring', 'i said', 'of exeter', 'i said', 'my friend', 'pardon me',
             'except myself', 'suppose i', 'to newcastle', 'or durham', 'or harwich',
             'or dover', 'my tablets', 'of which', 'i shall', 'of course', 'take care',
             'and said', '24 may', 'of course', 'true gentleman', 'little girl',
             'sanguine temperament', 'morbidly excitable', '26 may', 'my gog',
             'and purpose', 'poor dear', "lucy's father", 'my deary', 'he thought',
             'he thought', 'be patient', 'the tall', 'he thought', 'almost compellingly',
             'his sister', 'of course', 'and so', 'would you']
