"""
Imported by `cpt_config.py` for use in the Tkinter GUI.

Variable:
    words_one (list): Single words for 0-10 second portion of typing test.
"""

# Single words for 0-10 second portion of typing test.
words_one = ['knows', 'river', 'happiness', 'beast', 'well', 'deem', 'thinking',
             'Russia', 'This', 'also', 'softened', 'injurer', 'Aid', 'stored', 'heads',
             'Wagner', 'morrow', 'starlet', 'sake', 'untimely', 'encourage', 'shield',
             'helm', 'overvaluing', 'loneliness', 'floor', 'receive', 'family', 'pulled',
             'glen', 'convicted', 'taken', 'handmaid', 'borrowed', 'Enough', 'asking',
             'shouldst', 'action', 'signet', 'decide', 'slew', 'whirl', 'doorway',
             'relations', 'Sick', 'break', 'scorn', 'on', "he's", 'gifted',
             'blaspheming', 'advance', 'straight', 'times', 'pupils', 'Loose', 'much',
             'seem', 'Venezuela', 'rage', 'slave', 'sort', 'lies', 'pocket', 'Upon',
             'weep', 'Clearly', 'Egypt', 'wonderful', 'disguised', 'Being', 'lover',
             'Far', 'Leon', 'cushion', 'Drop', 'moves', 'Halls', 'served', 'complete',
             'numerous', 'justly', 'soft', 'busying', 'rest', 'delicate', 'Made',
             'hazard', 'elevates', 'Than', 'night', 'Have', 'intellectual', 'repent',
             'Passion', 'joyful', 'Nobody', 'lack', 'Unfathered', 'masses', 'imputed',
             'yeah', 'asserted', 'doctor', 'kinsmen', 'across', 'drawn', 'pince',
             'heaping', 'event', 'prospect', 'Others', 'Methinks', 'wilder', 'swarm',
             'frock', 'Gorgias', 'Who', 'fear', 'pushed', 'arrives', 'look', 'Mark',
             'fling', 'thing', 'forward', 'sister', 'guiding', 'dews', 'formal', 'Life',
             'highest', 'left', 'Square', 'stays', 'origin', 'eye', 'employment',
             'shared', 'Pan', 'offended', 'promise', 'finished', 'fields', 'perish',
             'burned', 'mere', 'give', 'contains', 'Sadly', 'knoweth', 'judges',
             'Orange', 'hide', 'Prevailing', 'The', 'place', 'cold', 'homeliest',
             'imprisonment', 'made', 'profits', 'yes', 'prayed', 'Mrs', 'knees',
             'medicine', 'song', 'He', 'exhortations', 'Stood', 'await', 'Waste',
             'enquiry', 'deceived', 'connected', 'eventful', 'purple', 'Peliad',
             'dearest', 'check', 'invention', 'hath', 'fulfil', 'Turkey', 'nears',
             'slanderously', 'Boy', 'World', 'gasps', 'teach', 'lounging', 'disabling',
             'craved', 'bluey', 'Hath', 'forever', 'Groping', 'bend', 'all', 'effected',
             'office', 'state', 'wondering', 'acquitted', 'hour', 'Socrates', 'moans',
             'placed', 'Through', 'wreck', 'time', 'conferred', 'from', 'arrived',
             'surprised', 'condemn', 'stopped', 'life', 'rouse', 'repose', 'glass',
             'hear', 'soon', 'denying', 'closing', 'wasteth', 'particle', 'keep', 'draw',
             'seekest', 'count', 'said:', 'path', 'harvest', 'Touching', 'bursts',
             'endured', 'politics', 'bitter', 'motion', 'Hello', 'deserved', '2',
             'their', 'persuasion', 'Yester', 'advanced', 'why', 'maybe', 'hair',
             'forsaking', 'Clay', 'screen', 'write', 'devoid', 'fetched', 'encastled',
             'god', 'weary', 'convince', 'philosopher', 'House', 'keen', 'Besides',
             'Spring', 'powers', 'hearers', 'reproach', 'deeply', 'challenge',
             'terrible', 'richer', 'laboured', 'sorry', 'determined', 'hi', 'breasts',
             'Chained', 'spiritual', 'unmake', 'rely', 'how', 'shmmopy', "'Tis",
             'duteously', 'reply', 'deeds', 'I', 'Holder', 'bushy', 'Whereby', 'fierce',
             'Constructed', 'grace', 'although', 'shores', 'hereafter', 'destroy', 'So',
             'done', 'gnash', 'manifest', 'extraordinary', 'rotting', 'raising',
             'buries', "I'm", 'easily', 'lasted', 'veriest', 'Therefore', 'Sunday',
             'defend', "weren't", 'another', 'dole', 'Clash', 'bearing', 'bold',
             'charge', 'mountains', 'feel', 'strove', 'go', 'mankind', 'Day', 'Unhappy',
             'indictment', 'cavilling', 'nailed', 'by', 'upbuild', 'money', 'Bah', 'bye',
             'sum', 'score', 'desert', 'going', 'reflect', 'Medea', 'gnawing',
             'possession', 'means', 'sheet', 'judge', 'miserable', 'wed', 'end',
             'friend', 'mass', 'Ostlers', 'trampling', 'quest', 'throwing', 'gold:',
             'touched', 'All', 'longer', 'gleam', 'Age', 'case', 'bright', 'Doubtless',
             'agonies', 'exactly', 'Fleet', 'Juchheisa', 'geniuses', 'samples', 'sought',
             'falsely', 'weaknesses', 'purge', 'succouring', 'gives', 'Fruits', 'year',
             'maketh', 'Adeimantus', 'allege', 'occur', 'transferred', 'driver', 'flew',
             '000', 'Jonathan', 'anguished', 'rich', 'undone', 'ambitious', 'rather',
             'rotunda', 'loving', 'afterwards', 'borne', 'childless', 'found', 'started',
             'appearing', 'meeting', 'volumes', 'doctrine', 'essentially', 'retained',
             'Sir', 'trouble', 'haunteth', 'defect', 'flock', 'Wilt', 'privately',
             'Shore', 'advice', 'fled', 'no', 'dog', 'thine', 'Poland', 'disobedience',
             'crag', 'doors', 'lips', 'brook', 'Spurn', 'echo', 'palter', 'speculate',
             'Slow', 'approaching', 'valleys', 'compromised', 'Yemen', 'gathered',
             'heaven', 'offered', 'them', 'anchor', 'devisers', 'Nine', 'take', 'father',
             'received', 'Haunting', 'Often', 'speaker', 'him', 'present', 'mind',
             'varied', 'stand', 'block', 'desire', 'Morocco', 'Muses', 'light', 'accuse',
             'Having', 'triviality', 'fire', 'excite', 'thoughts', 'mighty', 'build',
             'tinted', 'Gentlemen', 'claim', 'amongst', 'Happy', 'comparison', 'Ahh',
             'graves', 'Queen', 'nonsense', 'business', 'hate', 'tread', 'pent',
             'corses', 'By', 'Sooner', 'Spain', 'older', 'wonders', 'injustice',
             'watching', 'says', 'Algeria', 'warn', 'generally', 'intended', 'wait',
             'veil', 'suffer', 'Nicostratus', 'cataloguing', 'teacher', 'low', 'eminent',
             'pained', 'bound', 'Angola', 'Belarus', 'old', 'were', 'fruits', 'second',
             'estimated', 'Mr', 'the', 'Are', 'conduct', 'interrogate', 'calculate',
             'succeeded', 'suns', 'search', "mother's", 'talked', 'behalf', 'Shhhhh',
             'again', 'reprove', 'Why', 'exiled', 'actually', 'Bolivia', 'Greeks',
             'speak', 'flame', 'divinity', 'passeth', 'appeared', 'carriage', 'became',
             'doth', 'private', 'exhorting', 'followed', 'Trojan', 'pretty', 'tired',
             'vile', 'wanted', 'Parchment', 'comparing', 'lie', 'slain', 'cheer',
             'liked', 'Praising', 'gaze', 'standeth', 'weird', 'fifth', 'Get',
             'extraneous', 'lave', "o'clock", 'half', 'heavier', 'plea', 'hitherto',
             'believing', 'questioned', 'excuse', 'While', 'encompass', 'condition',
             'Mad', 'drops', 'close', 'cup', 'Cameroon', 'wakened', 'straightway',
             'Resteth', 'sky', 'eloquence', 'station', 'Forth', 'individuals', 'witness',
             'examine', 'wondrous', 'Attendants', 'am', 'pay', 'Suddenly', 'evermore',
             'succours', 'kind', 'brazenly', 'Shot', 'prophetess', 'noticeable',
             'leading', 'gently', 'writing', 'Hereafter', 'Clung', 'courteous', 'Quick',
             'job', 'possibly', 'head', 'mentioned', 'confounded', 'wayfarings',
             'Henceforth', 'withal', 'method', 'Tunisia', 'Fools', 'smooth', 'baffle',
             'despise', 'Beseech', 'bared', 'sit', 'there', 'harmed', 'ran', 'seized',
             'comest', 'Old', 'Blast', 'hoped', 'ring', 'walls', 'Earth', 'Juchhe',
             'Twas', 'stronger', 'Eritrea', 'seeming', 'Sudan', 'laughed', 'wearied',
             'habit', 'stay', 'suing', 'madly', 'Windibank', 'boldly', 'gray', 'exile',
             'Ethiopia', 'through', 'Rend', 'Smiling', 'single', 'claws', 'righteous',
             'soup', 'flung', 'put', 'fragrance', 'sucking', 'force', 'game', 'Susan',
             'enemy', 'injury', 'Too', 'brand', 'towns', 'Peru', 'sweeps', 'Betray',
             'Tuscan', 'Ere', 'desolate', 'Symplêgades', 'catches', 'vision', 'led',
             'buxom', 'ready', 'raise', 'considerable', 'cotton', 'weeping', 'hearth',
             'bruised', 'trust', 'flow', 'caught', 'useth', 'edge', 'Boscombe',
             'temperamental', 'mother', 'Loves', 'underneath', 'make', 'calculated',
             "It'll", 'glimpse', 'forbids', 'evil', 'seeing', 'falter', 'index', 'Fear',
             'among', 'very', 'follow', 'healing', 'As', 'refused', 'answered:',
             'public', 'treasures', 'Germany', 'gloom', 'charges', 'aforesaid',
             'ouverte', "know'st", 'ranger', 'Child', 'Miss', 'greatness', 'naught',
             'bears', 'lamented', 'having', 'sown', 'king', 'respected', 'receiving',
             'Prytaneum', 'named', 'dead', 'immortal', 'wise', 'honey', 'many', 'boots',
             'Irene', 'steed', 'voice', 'Hammering', 'reason', 'subject', 'examples',
             'pleasant', 'IN', 'career', 'O', 'whatso', 'about', 'dangers',
             'acknowledge', 'writers', 'tables', 'thither', 'laid', 'portion', 'grow',
             'hire', 'hardly', 'born', 'that', 'likely', 'apart', 'oppressive', 'duly',
             'frame', 'fold', 'constructing', 'Indeed', 'jointing', 'torches', 'ears',
             'princely', 'scent', 'chambering', 'stonework', 'Ar-moire', 'chose',
             'observer', 'Athenians', 'Fine', 'knee', 'Norway', 'longed', 'breeze',
             'runs', 'shmoopy', 'slower', 'pretenders', 'theatre', 'chimes', 'glory',
             'common', 'whose', 'into', 'comedy', 'during', "that's", 'boy', 'Never',
             'Arthur', 'flows', 'propriety', 'shalt', 'condemning', 'remind', 'Stop',
             'Thus', 'instead', 'Baron', 'Smooth', 'demean', 'shall', 'letter', 'must',
             'lifeand', 'hidden', 'quite', 'Cast', 'positions', 'exact', 'groaning',
             'robes', 'King', 'neither', 'sheltered', 'strange', 'sicknesses', 'Miss',
             'onto', 'inconsolable', 'Little', 'loud', 'PHIPPS', 'Has', 'frozen',
             'passed', 'mire', 'hands', 'Mother', 'Then', 'pathway', 'behaving',
             'requite', 'accusing', 'chamber', 'She', "D'Alembert", 'opinion',
             'everything', 'Where', 'spread', 'calls', 'detractors', 'marked', 'tide',
             'admit', 'whither', 'fires', 'conviction', 'Past', 'Dost', 'millions',
             'soul', 'malady', 'slightly', 'throne', 'There', 'lift', 'breath', 'may',
             'provokes', 'presidency', 'fool', 'uncorrupted', 'wasted', 'Bid', 'Athens',
             'gash', 'acquit', 'Angel', 'quiver', 'back', 'address', 'Chile', 'beating',
             'little', 'nurture', 'Muse', 'behest', 'interpretation', 'stricken',
             'knowing', 'Longing', 'imitate', 'implicating', 'elderly', 'considered',
             'seldom', 'while', 'Our', 'unconscious', 'disturbance', 'vague', 'fairest',
             'recking', 'cry', 'fools', 'actionable', 'length', 'thee', 'Alas',
             'deceive', 'swear', 'fulfilled', 'wrong', 'Husband', 'dwells', 'devouring',
             'After', 'herbs', 'free:', 'met', 'heals', 'blue', 'Those', 'call',
             'written', 'Until', 'arts', 'chances', 'insult', 'bear', 'slander', 'above',
             'Presently', 'Of', 'Australia', 'help', 'LEADER', 'Bear', 'told',
             'Chattels', 'judgment', 'fortune', 'Faith', 'goes', 'reached', 'wherefore',
             'linen', 'particular', 'Straightway', 'rages', 'Dear', 'uncontrollable',
             'Peel', 'shore', 'fathers', 'Children', 'command', 'Huh', 'LIFE',
             'Zimbabwe', 'loathliness', 'extracted', 'open', 'pretends', 'interest',
             'molten', 'burn', 'remainder', 'overtaken', 'dazzling', 'engine', 'helped',
             'hurried', 'trusty', 'witnesses', 'Here', 'thanks', 'Razumihin.', 'godlike',
             'purpose', 'forced', 'capital', 'bounden', 'justice', 'mulligatawny', 'won',
             'web', 'zeal', 'spoil', 'bids', 'garçon', 'wedded', 'labour', 'differ',
             'brains', 'earned', 'Troy', 'Be', 'Aeacus', 'persuaded', 'wandering',
             'Much', 'slanderers', 'JASON', 'horses', 'swiftly', 'chambers', 'heel',
             'gain', 'think', 'malice', 'laying', 'trod', 'Women', 'wherever',
             'grantest', 'simple', 'lonely', 'cries', 'plant', 'Bleeding', 'brain',
             'makes', 'Served', 'resurrection', 'weaken', 'fearest', 'fastening',
             'meaning', 'principally', 'softness', 'ten', 'empty', 'magistrates',
             'stated', 'helplessness', 'oracle', 'Rising', 'sheered', 'work', 'smell',
             'platitudes', 'countertop', 'John', 'clean', 'God', 'idle', 'spare', 'bow',
             'Uruguay', 'because', 'mirror', 'poverty', 'thus', 'Does', 'modern',
             'perfect', 'able', 'abide', 'Cheveley', 'ope', 'intimation', 'set', 'Out',
             'preceding', 'Pelion', 'risen', 'philosophers', 'get', 'observed', 'whence',
             'quit', 'remember', 'Red', 'feed', 'water', 'exacted', 'Again', 'Threw',
             'follows', 'any', 'bitterness', 'telling', 'Already', 'Such', 'girl',
             'known', 'meet', 'leaving', 'graceless', 'choose', 'acres', 'castle',
             'accusation', 'Mocked', 'Laughing', 'sin', 'faint', 'surges', 'who', 'Bit',
             'evenings', 'Well', 'three', 'Inverness', 'Before', 'yielded', 'tempest',
             'Atonement', 'moth', 'crawl', 'heels', 'become', 'persuasively', 'internal',
             'surpassing', 'improving', 'London', 'Many', 'Lords', 'knowledge',
             'bridegroom', 'wrath', 'fair', 'places', 'Now', 'compounded', 'persuade',
             'Beautiful', 'daughter', 'Canst', 'entreated', 'poisons', 'dart',
             'Motherless', 'ot', 'Him', 'Mexico', 'feelings', 'envy', 'country',
             'against', 'eastern', 'hard', 'Broken', "secret's", 'least', 'Hitherto',
             'alive', 'glad', 'swept', 'compared', 'behind', 'undisturbed', 'truth',
             'suffered', 'full', 'walks', 'accustomed', 'duty', 'was', 'proved',
             'escape', 'farmer', 'rises', 'waiting', 'Seemed', 'Grew', 'Held', 'Fell',
             'stern', 'sure', 'Nay', 'petition', 'foam', 'under', 'refrain', 'Is', 'nor',
             'Wherefore', 'maiden', 'thrown', 'aims', "husband's", 'athwart', 'tarrying',
             'doomed', 'woods', 'punishment', 'pursuing', 'Uh-oh', 'degree', 'forth',
             'Jerry', 'Fond', 'Unlit', 'Its', 'declare', 'Japan', 'happier', 'direst',
             'skies', 'abate', 'rarest', 'passes', 'elevated', 'before', 'wooing',
             'Shrieking', 'raging', 'Their', 'Running', 'interom', 'later', 'rush',
             'satisfaction', 'feet', 'admission', 'fly', 'virtue', 'Student', 'sudden',
             'chosen', 'this', 'steeped', 'turn', 'sensible', 'Yet', 'assure', 'Cobden',
             'intends', 'store', 'houses', 'angrier', 'draweth', 'convincing', 'China',
             'bent', 'lesser', 'letters:', 'maids', 'something', 'Whether', 'Coburg',
             'style', 'rose', 'confront', 'amazed', 'Father', 'Thanks', 'industrial',
             'her', 'yokes', 'villainous', 'daring', 'Faugh', 'map', 'doer', 'Shame',
             'Surgeons', 'array', 'lives', 'Let', 'erst', 'shrieking', 'Heathcoat',
             'labouring', 'industry', 'future', 'Roman', 'fatalities', 'effect', 'Woman',
             'surely', 'exclusively', 'claims', 'Achilles', 'wipes', 'system', 'shining',
             'rub', 'wealth', 'notions', 'linger', 'white', 'customary—previous', 'debt',
             'fantastic', 'Mephistopheles', 'Friend', 'suddenly', 'hence', 'impudence',
             'chiefly', 'wave', 'early', 'guards', 'Mulligatawny', 'No', 'Blue', 'tardy',
             'heroes', 'successfully', 'hunted', 'earn', 'Tempts', 'stealeth', 'cruelty',
             'victory', 'pause', 'scattered', 'Euripides', 'planted', 'Odysseus',
             'Shalt', 'Every', 'blest', 'beaked', 'carcanet', 'Love', 'whereas',
             'hoarded', 'poetry', 'land', 'hunt', 'others', 'bosom', 'claps', 'weepest',
             'dishonour', 'wild', '15', 'mildly', 'really', 'blinding', 'thought',
             'brave', 'home', 'himself', 'learnt', 'afraid', 'lest', 'armour', 'asks',
             'ATTENDANT', 'shapes', 'With', 'sovranty', 'plan', 'Thinking',
             'Mournfully.', 'if', 'persuasive', 'listening', 'proposes', 'Seeing',
             'Forgery', 'sweating', 'side', 'Rail', 'let', 'Run', 'fears', 'teaches',
             'kings', 'view', 'easy', 'Tomorrow', 'associated', 'Stand', 'motions',
             'spirits', 'sanctities', 'broken', 'top', 'real', 'proceed', 'yourselves',
             'incapable', 'Colombia', 'coward', 'aux', 'after', 'armed', 'pilgrimage',
             'spill', 'August', 'minæ', 'obviously', 'Malawi', 'assistance', 'Ohh',
             'ashamed', 'huddled', 'spiders', 'Ha', 'deficiency', 'locally', 'Mine',
             'gather', 'perfection', 'taking', 'corrupts', 'Against', 'therefor', 'tall',
             'coffee', 'accused', 'marriage', 'professed', 'younger', 'yore', 'kneels',
             'Shrouded', 'fareth', 'sign', 'Athenian', 'reck', 'Move', 'Whatso',
             'orators', 'riven', 'mention', 'enmity', 'corrupting', 'pains', 'alone',
             'fashion', 'triple', 'illegitimate', 'deep', 'thy', 'result', 'Iraq',
             "Kramer's", 'definitely', 'Strength', 'faced', 'news', 'Antiphon', 'heir',
             'memories', 'shatter', 'peculiar', 'first', 'doubly', 'Or', 'stem', 'Must',
             'desperate', 'cab', 'power', 'account', 'walk', 'house', 'tongue',
             'Indonesia', 'sow', 'Pestryakov.', 'alien', 'maid', 'ill', 'and', 'refer',
             'uplift', 'gladsome', 'Chorus', 'huh', 'come', 'contradict', 'appease',
             'lusty', 'entering', 'which', 'pray', 'nothing', 'harbour', 'survived',
             'moment', 'Style', 'Give', 'laughing', 'hideously', "'bout", 'bowing',
             'air', 'swells', 'should', 'alway', 'Defeat', 'addressing', 'shuddering',
             'given', 'fact', 'sins', 'didst', 'red', 'arraigned', 'babying', "B's",
             'Keep', 'charged', 'whilst', 'misery', 'lawless', 'Theodotus', 'Central',
             'divinities', 'sting', 'minutes', 'gripped', 'being', 'crafts', 'son',
             'dear', 'language', 'demands', 'Messrs', 'forlorn', 'unholy', 'Had',
             'drive', 'Ill', 'attached', 'exhibitions', 'more', 'turkey', 'However',
             'Anytus', 'lived', 'child', 'difficulty', 'Whereupon', 'devotion', 'wide',
             'Perhaps', 'lace', 'evidence', 'hears', 'supposing', 'tribe',
             'unfrequently', 'link', 'fret', 'quick', 'deck', 'pushing', 'madness',
             'sires', 'fitting', 'Pool', 'Bar', 'banishment', 'only', 'know', 'workings',
             'demigods', 'passage', 'civil', 'happy', 'continually', 'an', 'Twice',
             'troth', 'carefully', 'Ecuador', 'me', 'idols', 'Leave', 'Turned', 'Esq',
             'ills', 'narrative', 'stabbing', 'veins', 'Nicaragua', 'Kissed', 'further',
             'deed', 'resolution', 'simply', 'shortly', 'lap', 'Which', 'span',
             'Application', 'Excitedly', 'promised', 'Three', 'Musaeus', 'uh', 'deny',
             'hurt', 'running', 'might', 'drunk', 'as', 'burden', 'gas', 'consciousness',
             'Hast', 'few', 'joy', 'louder', 'seventy', "clerk's", 'Hold', 'Wisdom',
             'India', 'held', 'parted', 'handcuffs', 'dost', 'members', 'forgotten',
             'unblinded', 'road', 'fearing', 'keys', 'oaths', 'deliverance', 'mushrooms',
             'Turkmenistan', 'Certainly', 'obedient', 'mission', 'Scarlet', 'laws',
             'belongs', 'Prytanes', 'prayer', 'worthy', 'waits', 'Mmm-hmm', 'bloom',
             'worst', 'drivest', 'Say', 'remain', 'marred', 'sire', "That's", 'penalty',
             'Feel', 'together', 'whom', 'breaks', 'crooked', 'dreamed', 'Help', 'May',
             'sweetness', 'aid', 'givest', 'stab', 'chest', 'Next', 'Suavely',
             'grievous', 'lobes', 'try', 'task', 'braving', 'lethal', 'overcoat',
             'needs', 'politician', 'motive', 'Blitz', 'concerns', 'eventually', 'thou',
             'contrast', 'pilgrim', 'Brethren', 'demand', 'proposed', 'Lemon',
             'admitted', 'Beggared', 'cause', 'condemned', 'thankful', 'fierier',
             'VOICE', 'plain', 'selected', 'nearer', '"', 'greatest', 'fallen', 'chime',
             'absolute', 'Thailand', 'Dead', 'pine', 'admonished', 'pitiless',
             'flatteries', 'Oath', 'refute', 'blind', 'Hell', 'Ahoy', 'better', 'slight',
             'trembling', 'sweepeth', 'like', 'sift', 'wake', 'easiest', 'handed',
             'beside', 'Henceforward', 'enormous', 'improves', 'womb', 'native', 'court',
             'flieth', 'warrant', 'Son', 'Tanzania', 'despised', 'wife', 'hating',
             'utterly', 'Tom', 'parents', 'off', 'arousing', 'be', 'chain', 'piety',
             'fruit', 'clear', "wouldn't", 'Pray', 'fancying', 'town', 'hardihood',
             'kissed', 'Murat', 'antagonist', 'evidently', 'suppose', 'innumerable',
             'profiteth', 'arguments', 'earnest', 'Thoughtfully', 'cover', 'coming',
             'bravely', 'peace', 'Adrian', 'trying', 'Peace', 'MRS', 'Tell', 'strife',
             'termed', 'cometh', 'taketh', 'stranger', 'Whom', 'Fortune', 'brother',
             'unexamined', 'Potidaea', 'affidavit', 'checked', 'asked', 'fro', 'arrest',
             'passionately', 'Mina', 'save', 'affected', 'less', 'reflected', 'steep',
             "everyone's", 'angry', 'For', 'mortals', 'cast', 'arches', 'names',
             'secret', 'clogged', 'slow', 'enchanted', 'instantly', 'higher', 'gets',
             'star', 'grief', 'awoke', 'tarry', 'green', 'heard', 'consider', 'words',
             'landless', "o'", 'Cigar', 'dreadful', 'Hup', 'Was', 'select', 'Corinth',
             'Surely', 'disposed', 'notice', 'curses', 'harbourage', 'reliance',
             'Brazil', '$3', 'somebody', 'sight', 'inventors', 'dress', 'Acre',
             'Cordially', 'shut', 'prejudice', 'wantonness', 'tried', 'stormy',
             'threads', 'fetch', 'Lysanias', 'encouraged', 'freedom', 'speaks',
             'workmen', 'straw', 'vigour', 'grudge', 'Closed', 'permit', 'different',
             'relate', 'regular', 'said', 'erected', 'robe', 'taught', 'CREON',
             'CHILDREN', 'infringements', 'lead', 'cups', 'lacking', 'locks', 'homeward',
             'handmaids', 'dust', 'shameful', 'Ye', 'Laos', 'Only', 'bring', 'grant',
             'though', 'neglect', 'bitterest', 'Kramer', 'stoutly', 'truest', 'convict',
             'south', 'then', 'Am', 'request', 'beyond', 'obedience', 'sorts', 'never',
             'live', 'rumours', 'interrupt', 'leiter', 'lined', 'seeking', 'bleed',
             'ordering', 'glove', 'tales', 'owing', 'Incoherently.', 'gift', 'laurel',
             'brothers', 'Cambodia', 'either', "Gregor's", 'sweetest', 'animated', 'a',
             'enough', 'estimate', 'chariot', 'bread', 'Then', 'genius', 'Tread', "'",
             'saw', 'superscription', 'between', 'Her', 'irrational', 'perisheth',
             'manifold', 'understand', 'room', 'laugh', 'helping', 'strike',
             'alternately', 'bond', 'sore', 'Hangs', 'juvenile', 'Beyond', 'possible',
             'tender', 'righted', 'nevertheless', 'doubt', 'human', 'sword', 'Show',
             'laughest', 'possess', 'suitable', 'Pittheus', 'Beam', 'find', 'prefers',
             'aught', 'dangerous', 'Liver', 'Gertrude', 'interests', 'rapidly', 'Thank',
             'Sheila', 'will', 'Heaven', 'to', 'curls', 'turned', 'thrall', 'leave',
             'proper', 'elaborate', 'purposes', 'Oman', 'hatred', 'Beside', '200',
             'believed', 'dragged', 'vindication', 'understanding', 'disobeyed',
             'talking', 'Fire', 'reasons', 'Lodge', 'Salaminian', 'wiser', 'queen',
             'entreaty', 'gentle', 'seas', 'distinguished', 'Granted', 'Chose', 'Hellas',
             'reared', 'visit', 'strangely', 'Cannot', 'hero', 'Count', 'Tempestuous',
             'struggle', 'bleeds', 'great', 'We', 'doom', 'injured', 'overshadowed',
             'brow', 'Swift', 'attained', 'lingering', 'doleful', 'pretence', 'Honours',
             'careless', 'ache', 'breathing', 'my', 'faults', 'dame', 'vintage',
             'granted', 'Stole', 'probably', 'Whoa', 'comfort', 'wished', 'dare', 'Turn',
             'breaking', 'Me', 'planned', 'Would', 'befriend', 'without', 'Beneath',
             'MORRIS', 'snakes:', 'Strong', 'winds', 'already', 'Ay', 'Stone', 'deft',
             'us', 'allusion', 'Canada', 'Unloose', 'thereupon', 'sorrow', 'venture',
             'passions', 'trainer', 'settle', 'Gods', 'inveterate', 'dared', 'darkness',
             'walker', 'overpower', 'next', 'Unstrivingly', 'departure', 'Great',
             'elders', 'Guideth', 'last', 'talk', 'revealed', 'foals', 'ere', 'swelling',
             'brief', 'stands', 'sultry', 'showing', 'Myanmar', 'reeking', 'Furled',
             'Delphi', 'ivy', 'harsher', 'according', 'Heard', 'every', 'do',
             'conceiving', 'Who-ah', 'blessing', 'trade', 'Wait', 'falsest', 'wince',
             'Denmark', 'aware', 'Accepted', 'bliss', 'soothsayers', 'Uganda', 'Pesth',
             'twain', 'ingenious', 'rid', 'amount', 'seemed', 'saved', 'ute', 'lain',
             'concerning', 'music', 'Call', 'conclusion', 'lightly', 'returns',
             'Porcine', 'numberless', 'Faust', 'traveller', 'city', 'besides', 'threats',
             'craft', 'watch', 'wheel', 'windows', 'past', 'brides', 'so', 'had',
             'Briony', 'Ample', 'riddle', 'effective', 'Congo', 'curt', 'Good',
             'pretensions', 'circumstance', 'good', 'unintentional', 'six', 'Come',
             'immediately', 'myself', 'Sate', 'creep', 'distress', 'directed',
             'alliance', 'Green', 'obey', 'latter', 'plainer', 'Elaine', 'inviolate',
             'Can', 'impious', 'share', 'falleth', 'Canine', 'parts', 'verily', 'cases',
             'morning', 'jealous', 'feast', 'Soon', 'secure', 'in', 'foreign', 'fall',
             'marks', 'brought', 'easier', 'proud', 'superhuman', 'died', 'steam', 'is',
             'waves', 'Comic', 'school', 'near', 'facing', 'books', 'ways', 'keel',
             'direr', 'sets', 'until', 'Turner', 'Really', 'distinguish', 'barred',
             'Meletus', 'raised', 'forgot', 'These', 'converse', 'swift', 'indeed',
             'Holmes', 'movie', 'blessed', 'seducing', 'rooms', 'Parian', 'bred',
             'torture', 'bother', 'serious', 'yonder', 'source', 'Vision',
             'Provisionless', 'abhorred', "ditherin'", 'setter', 'Seeking', 'Niger',
             'runner', 'Because', 'bare', 'rear', "Jerry's", 'Peasants', 'children',
             'high', 'decketh', 'grave', 'your', 'Brother', 'Up', "'neath", 'wet',
             'procuring', 'pleasure', 'flights', 'patiently', 'dipping', 'unknown',
             'trained', 'disgraceful', 'observe', 'Arranged', 'Hesiod', 'these', 'Argo',
             'okay', 'allowed', 'Since', 'loafing', 'dooms', 'nearly', 'order', 'would',
             'coughing', 'flirting', 'Completely', 'teaching', 'lowest', 'citizen',
             'seek', 'one', 'royal', 'Thou', 'citizens', 'require', 'Gregor', 'new',
             'word', "it's", 'crafty', 'Minos', 'footstep', 'freed', 'unto', 'blows',
             'horse', 'Salamis', 'strain', "drinker's", 'reasoned', 'maintained',
             'wronged', "Tenbys'", 'reputation', 'Awakening', 'explanation', 'girt',
             'spirit', 'gave', 'chowder', 'unfair', 'too', 'lore', 'sunnier', 'Ah',
             'arms', 'mood', 'discreditable', 'essential', 'steps', "shepherd's",
             'ridicules', 'see', 'ease', 'succour', 'Meseems', 'have', 'wind', 'thirty',
             'About', 'Airily', 'divers', 'double', 'seems', 'sleeping', 'equal',
             'could', 'starting', 'danger', 'Will', 'Maybe', 'poising', 'net', 'trial',
             'Git', 'Aristophanes', 'shrivelled', 'goodly', 'improvement', 'appearance',
             'pondering', 'dressed', 'sounded', 'cling', 'opportunity', 'Ever',
             'labours', 'honestly', 'Shh', 'olden', 'weigh', 'hardest', 'enmities',
             'Sweden', 'almost', 'away', 'explain', 'Zambia', 'toils', 'loved',
             'Mulliga', 'Afghanistan', 'comrade', 'How', 'gentleman', 'thinks', 'beg',
             'bridal', 'seen', 'incurred', 'expected', 'streams', "father's", 'Okay',
             'Except', 'oration', 'tenderness', 'fine', 'unseen', 'avenged', 'sundry',
             'library', 'domestic', 'Suriname', 'matter', 'Reach', 'migration',
             'quietlyas', 'twined', 'occasion', 'Hmmm', 'apparatus', 'Prodicus',
             'gained', 'um', 'hold', 'wickedness', 'poets', 'cheated', 'slowly', 'My',
             'prophesy', 'offence', 'Power', 'Woe', 'persuading', 'hope', 'fairly',
             'natural', 'confess', 'not', 'returned', 'sense', "couldn't", 'Watson',
             'shadows', 'menace', "Count's", 'Waiting', 'Speak', 'villainy', 'avenge',
             'went', 'error', 'humble', 'threatened', 'description', 'port', 'opponents',
             'hurrying', 'discourses', 'neglected', 'surmise', 'street', 'Unfortunately',
             'faster', 'continued', 'savage', 'fed', 'Lestrade', 'sufficiently',
             'welcomed', 'attempt', 'feared', 'man', 'unrighteous', 'necessity',
             'dishonourable', 'shelter', 'upon', 'they', 'plenty', 'goeth', 'Back',
             'LADY', 'accusations', 'Sharp', 'eternity', 'space', 'ear', 'Above',
             'concealed', 'Both', 'inflicted', 'Buda', 'rolled', 'sung', 'trample',
             'fountain', 'escaping', 'she', 'making', 'endless', 'strong', 'down',
             'Rude', 'Bania', 'guilty', 'testimony', 'confident', 'prospering',
             'Rhadamanthus', 'nigh', 'sons', 'Hum', 'kiss', 'Chaerephon', 'paced',
             'both', 'doctrines', 'kept', 'betrayed', 'corrupter', 'Listen', 'study',
             'Envy', 'body', 'Dr', 'lose', 'sees', 'Hera', 'lost', 'blame', 'guide',
             'stop', 'companion', 'disfavour', 'announcement', 'olive', 'waver',
             'procured', 'building', 'informing', 'childish', 'riseth', 'winging',
             'throat', 'families', 'are', 'wisdom', 'Wastes', 'prove', 'heal', 'Um',
             'Reading', 'over', 'memory', 'bravest', 'hated', 'Merryweather', 'Unless',
             'door', 'its', 'especially', 'centuries', 'weariest', 'An', 'husband',
             'beautiful', 'certain', 'face', 'till', 'reserve', 'Guyana', 'hot', 'curse',
             'here', 'friendless', 'unjust', 'Wrath', 'pressed', 'bind', 'craftsmen',
             'wisest', 'opened', 'shrinking', 'looked', 'dim', 'burning', 'sundering',
             'keeper', 'drag', 'evening', 'Somalia', 'Cold', 'Philippines', 'praise',
             'Longer', 'delivered', 'prophecy', 'Self', 'deprive', 'contain', 'our',
             'recent', 'CHEVELEY', 'inclined', 'feature', 'beareth', 'Heisa', 'often',
             'Ah-ha', 'putting', 'vaulted', 'ignorant', 'questions', 'days', 'wrought',
             'manward', 'than', 'quietly', 'stone', 'milky', 'wow', 'garments',
             'disturbs', 'false', 'speech', 'care', 'Myself', 'enquirers', 'loathing',
             'merely', 'same', 'punish', 'height', 'At', 'creature', 'dwell', 'forsook',
             'canst', 'wall', 'faith', 'neighbours', 'foot', 'proportion', 'slay',
             'deters', 'artisans', 'confirm', 'Prayed', "hills'", 'each', 'Hey',
             'envelopes', 'Swales', 'continue', 'Mali', 'Loathe', 'Fair', 'answered',
             'deserves', 'Argentina', 'beat', 'charities', 'student', 'waste', 'begin',
             'base', 'brazen', 'sworn', 'identified', 'smallest', 'practice', 'appear',
             'stained', 'mock', 'courtyard', 'opens', 'ledge', 'babes', 'emotional',
             'occupational', 'shiver', 'journey', 'happened', 'poison', 'iron',
             'decided', 'fast', 'service', 'refutation', 'fleece', 'If', 'kindness',
             'avoid', 'attend', 'Hill', 'aside', 'Holding', 'Lead', 'Kepler', 'stint',
             'Names', 'blithe', 'Nigeria', 'From', 'durst', 'Lord', 'ask', 'gifts',
             'honour', "Holmes's", 'individually', 'move', 'mocking', 'tend', 'closed',
             'uttered', 'wit', 'entirely', 'trick', 'feasts', 'pride', 'naked', 'of',
             'Guinea', 'Innocence', 'love', 'window', 'bards', 'win', 'compliance',
             'worse', "It's", 'truly', 'neck', 'undreamed', 'Iôlcos', 'Men', 'masters',
             'lasting', 'practise', 'unless', 'counted', 'Oft', 'Oh', 'Long', 'Gone',
             'Pshaw', 'gat', 'Some', 'unjustly', 'mischievous', 'Among', 'Uzbekistan',
             'turning', 'for', 'unfortunate', 'wanderings', 'clouds', 'I', 'glimpses',
             'daily', 'Madagascar', 'lamps', 'young', 'several', 'hurts', 'On', 'lady',
             'DR', 'standest', 'reward', 'His', 'Brick', 'saying', 'couldst', 'brows',
             'hansom', 'sweetly:', 'repeat', 'panting', 'grown', 'Reject', 'senses',
             'rays', 'prosper', 'See', 'firmament', 'Reflecting', 'physical', 'woe',
             'please', 'Half', 'got', 'opposite', 'greet', 'Wilson', 'tower',
             'Dishonest', 'Best', 'minds', 'deme', 'sepulchre', 'thyself', 'searching',
             'Set', 'honest', 'but', 'unworthy', 'drawers', 'holds', 'lucrative',
             'mightiest', 'merry', 'sufferings', 'founder', 'youthful', 'Anaxagoras',
             'goddess', 'mouth', 'hap', 'Whitby', 'choice', 'MEDEA', 'tailor', 'folk',
             'whether', 'England', 'ails', 'finding', 'moan', 'at', 'payment',
             'Christian', 'Crosseth', 'eyeballs', 'Quest', 'successor', 'company',
             'even', 'abandoned', 'None', "Something's", 'glasses', 'livest', 'frighten',
             'law', 'spilled', 'ones', 'you', 'Oxford', 'suffers', 'Man', 'fingers',
             'comes', 'shaft', 'nights', 'studied', 'Monica', 'entreat', 'does', 'vex',
             'Etherege', 'constantly', 'Wild', 'convinced', 'torn', 'golden', 'art',
             'deal', 'strayed', 'agencies', 'rehearse', 'Hungarian', 'backwards',
             'delight', 'tears', 'raiment', 'arrowy', 'essay', 'warnings', 'failed',
             'Malesherbes', 'thorn', 'mysteries', 'Romania', 'majority', "let's", 'mad',
             'pilot', 'own', 'requires', 'dreams', '140', 'herself', 'garden', 'papers',
             'course', 'NURSE', 'Thyself', 'giving', 'prosperous', 'Witness:', 'beats',
             'Folded', 'Samsa', 'shoulders', 'incarnate', 'opposing', 'Finland', 'But',
             'Somewhere', 'impetuous', 'filled', 'utter', 'Syria', 'senators', 'Should',
             'change', 'deigned', 'plot', 'added:', 'concentration', 'affirm', 'onward',
             'invented', 'Olympia', 'finds', 'somewhere', 'infer', 'lessons', 'support',
             'figures', 'feeble', 'corrupt', 'where', 'pure', 'awakened', 'mine', 'Very',
             'standing', 'perilous', 'driven', 'discrowned', 'consequence', 'Irish',
             'voila', 'wrongs', 'produce', 'looks', 'pen', 'Came', 'buying', 'Greece',
             'Art', 'using', 'enquire', 'They', 'soldiers', 'people', 'deteriorating',
             'play', 'kneel', 'Raskolnikov.', 'foundation', 'pallor', 'Young',
             'touching', 'Greek', 'Forgotten', 'drew', 'friends', 'Disgusting', 'still',
             'aileth', 'pawnbroker', 'peeped', 'Reasons', 'intent', 'impeach', 'turns',
             'Mock', 'welcome', 'afford', 'smiling', 'Themis', 'salt', 'listen',
             'savageness', 'Go', 'shaking', 'spoken', 'Vietnam', 'Golden', 'wants',
             'chide', 'nothingness', 'Gifts', 'midnight', 'wanting', 'elder', 'other',
             'swinging', 'knowest', 'gold', 'permitted', 'Cephîsus', 'accept', 'Deep',
             'wailing', 'grim', 'stars', 'advantage', 'pretended', 'appears', 'round',
             'thine:', 'unsounded', 'Wrought', 'Struck', 'speaking', 'fiery', 'Colchis',
             'Plato', 'hastily', 'Wrench', 'Libya', 'brown', 'worth', 'wounds', 'grasp',
             'wagons', 'couch', 'Armoire', 'yearning', 'Senegal', 'amusement', 'Shaped',
             'strive', 'Shunning', 'Uh', 'gale', 'mean', 'lifteth', 'compelled',
             'Thirty', 'scathe', 'apprehend', 'sailed', 'character', 'Iran', 'long',
             'corrupted', 'Home', 'Deaf', 'middle', 'hunger', 'stood', 'Comes', 'hotel',
             'years', "'attorney", 'Pythian', 'stintless', 'affirmed', 'world', 'gone',
             'produced', 'dramatic', 'Send', 'Kazakhstan', 'clergyman', 'loveth',
             'baulk', 'throw', 'greater', 'sleepeth', 'befall', 'ago', 'encaverned',
             'ruined', 'pain', 'such', 'wounded', 'send', 'fell', 'troubled', 'rare',
             'Owing', 'Betraying', 'now', 'oligarchy', 'whips', 'herb', 'conscious',
             'hearts', 'therefore', 'weapon', 'unspeakable', 'Lest', 'Dire', 'frail',
             'clustering', 'art—and', 'felt', 'wish', 'likes', 'defending', 'things',
             'believe', 'sicken', 'host', 'Pakistan', 'impressible', 'pace', 'can',
             'perils', 'chopped', 'doubtless', 'halls', 'it', 'Hi', 'tidings', 'Awake',
             'warned', 'bade', 'dread', 'ordered', 'anyone', 'sunshine', 'Like', 'harm',
             'bad', 'occupation', 'assembly', 'opposed', 'Whoop', 'rock', 'oath', 'lion',
             'hither', 'eyes', 'what', 'bed', 'absorbs', 'Mauritania', 'quickly', 'fail',
             'Secrecy', 'savagery', 'measured', 'Wouldst', 'yoke', 'greedily', 'mark',
             'searches', 'tiding', 'show', 'Thetis', 'seed', 'cloud', 'skywards',
             'sunlight', 'remarkable', 'casts', 'dazzle', 'orders', 'crab', 'bore',
             'war', 'godless', 'groom', 'observes', 'doing', 'regarded', 'winged',
             'brute', 'destruction', 'residing', 'delivers', 'attention', 'twine',
             'along', 'train', 'robbed', 'swell', 'searched', 'Parliament', 'Other',
             'Study', 'Stay', 'knew', 'Join', 'fifteen', 'Grey', 'barbarian', 'forgive',
             'spent', 'shown', 'with', 'diverse', 'hid', 'contrary', 'maintenance',
             'steal', 'Wow', 'within', 'sleep', 'pardon', 'Thought', 'teeth', 'Eh',
             'paid', 'moderate', 'heareth', 'shroud', 'joined', 'when', 'repute',
             'assuredly', 'touch', 'desires', 'Mongolia', 'beget', 'wakes', 'crimes',
             'reach', 'sun', 'arisen', 'Mmm', 'sunderstood', 'rise', 'table',
             'pleasantly', 'improve', 'eager', 'forget', 'some', 'benefited', 'Flesh',
             'weds', 'imaginary', 'diest', 'use', 'heart', 'razor', 'moving', 'fit',
             'Zeus', 'odious', 'cruel', 'snaps', 'moon', 'esteemed', 'tuna', 'flying',
             'favour', 'heedfully', 'gotta', 'parish', "fixin's", 'daemons', 'Paralus',
             'Yeah', 'Devilpaper', 'gathers', 'proof', 'Orpheus', 'spurned', 'Gladly',
             'locked', 'New', "You're", 'poor', 'lifted', 'his', 'Botswana', 'engaged',
             'or', 'temper', 'fiercely', 'Finally', 'Glory', 'Toward', 'To',
             'repeatedly', 'casteth', 'cliff', 'lucky', 'bless', 'published', 'far',
             'George', 'English', 'daughters', 'stayed', 'Ukraine', 'grey', 'ample',
             'variety', 'Etc', 'Robert', 'cross', 'contrition', 'been', 'front',
             'Phoebus', 'commands', 'endure', 'pity', 'befool', 'Time', 'brethren',
             'Wha', 'Edward', 'themselves', 'Look', 'shallow', 'inward', 'foul',
             'parlour', 'sapped', 'Association', 'has', 'changing', 'danced', 'flash',
             'Bobbin', 'bit', 'out', 'squeaking', 'commit', 'ye', 'inquisition', 'afar',
             'alarms', 'dreameth', 'anywhere', 'drifting', 'gates', 'offering', 'wend',
             'cylinder', 'amid', 'tortured', 'misleader', 'conventions', 'matters',
             'conversing', 'sail', 'Skylla', 'Could', 'hopes', 'day', 'crown', 'clerk',
             'citing', 'detected', 'called', 'nez', 'balance', 'dire', 'instruction',
             'battering', 'want', 'Nepal', "I'll", 'magic', 'Blessing', 'gods', 'noble',
             "you're", '$2', 'respect', 'Weak', 'fain', 'guard', 'tell', 'rang',
             'crawling', 'Drew', 'blinded', 'Virgin', 'Till', 'did', 'imagine',
             'inclination', 'escaped', 'towards', 'concern', 'boldness', 'question',
             'story', 'science', 'breast', 'Sorry', 'altogether', 'flesh', 'Adios',
             'dark', 'chief', 'Chad', 'serve', 'princess', 'Wed', 'report', 'visage',
             'argue', 'Bread', 'rows', 'hopeth', 'Kyrgyzstan', 'line', 'requited',
             "apothecary's", 'Shows', 'overcome', 'fitful', 'striving', 'ought',
             'Paraguay', 'Absolutely', 'stealing', 'answer', 'whichever', 'CHILTERN',
             'Nonconformist', 'prouder', 'experiments', 'defence', 'dream', 'You',
             'resolute', 'Vienna', 'true', 'join', 'crew', 'Tajikistan', 'lust', 'sate',
             'Kenya', 'run', 'Know', 'forerunners', 'cheek', 'since', 'Away', 'lands',
             'folds', 'ability', 'passion', 'gazpacho', 'those', 'Lucy', 'sends',
             'difficult', 'happen', 'learn', 'disseminators', 'assume', 'needed',
             'spoke', 'smitings', 'diviners', 'backward', 'he', 'used', 'intentionally',
             'anything', 'inconsiderate', 'recognized', 'starved', 'scarce', 'loath',
             'illiterate', 'Shall', 'Planing', 'list', 'majesties', 'need', 'sheer',
             'manner', 'burneth', 'generals', 'extended', 'endeavour', 'inflicting',
             'kinsman', 'tale', 'alter', 'Excuse', 'atheist', 'Spill', 'compare', 'part',
             'reckless', 'forsake', 'post', 'today', 'noblest', 'throughout', 'grew',
             'vacuous', 'clinging', 'guilt', 'note', 'lord', 'catch', 'More', 'object',
             'bosoms', 'photograph', 'scene', 'nerves', 'dawn', 'Ajax', 'limbs',
             'inventor', 'entire', 'youth', 'impiety', 'ungrateful', 'delightful',
             'start', 'pushes', 'Lay', 'begun', 'Selfishness', 'bodies', 'apt',
             'hungrily', 'we', 'conceive', 'arranged', 'counselled', 'responsibility',
             'Swear', 'League', 'undervaluing', 'exception', 'wills', 'Arnheim', 'amain',
             'yearly', 'depart', 'best', 'votes', 'carried', 'shattered', 'caring',
             'grovelled', 'woman', 'Think', 'discourse', 'remained', 'subtly', "isn't",
             'gonna', 'vain', 'scarcely', 'Sire', 'troubleth', "man's", 'calleth',
             'hand', 'rule', 'vote', 'widower', 'allow', 'wings', 'Make', 'small',
             'thirst', 'return', 'protestation', 'treasure', 'swerve', 'Still',
             'heaviest', 'causing', 'maladies', 'Honey', 'Sun', 'Strangling', 'fasting',
             'vow', 'Liberal', 'leisure', 'roamed', 'bid', 'calm', 'passing', 'free',
             'dwellings', 'self', 'drachma', 'circle', 'Won', 'Sherlock', 'Doth',
             'Bankers', 'Most', 'headed', 'Aww', 'What', 'tawny', 'heavy', 'effort',
             'working', 'propose', 'clashing', 'began', 'In', "she's", 'ice', 'divine',
             'short', 'value', 'trampled', 'sleeps', 'Malaysia', 'up', 'bleating',
             'four', 'interfere', 'pale', 'prevent', 'ancient', 'scapegrace', 'once',
             'Homer', 'cloak', 'anger', 'nymphs', 'say', 'Ghana', 'living', 'prosecuted',
             'setting', 'facetious', 'carelessness', 'obtain', 'Right', 'Easter', 'else',
             'unlike', 'around', 'inevitable', 'came', "don't", 'Attic', 'refuse',
             'expenditure', 'earth', 'spell', 'extent', 'dull', 'calumny', 'vanish',
             'recovers', 'Scarce', 'Tigress', 'Welcome', 'armchair', 'Mere', 'adjure',
             'clasping', 'Perseverance', 'serves', 'loss', 'Though', 'poured', 'regard',
             'instant', 'eat', 'displeased', 'godhead', 'robings', 'Jones', 'intimated',
             'lingers', 'meekly', 'Nothing', 'Lancashire', 'Not', 'Your', 'glow',
             'somewhat', 'women', 'When', 'discover', 'Did', 'roll', 'succeed', 'sway',
             'Wife', 'interesting', 'Creon', 'Critobulus', 'existence', 'specimen',
             'privily', 'obliged', 'Sweet', 'helper', 'shame', 'whole', 'sweetie',
             'hallowed', 'released', 'buy', 'learned', 'learning', 'master', 'chariots',
             'understands', 'removing', 'large', 'Grete', 'pounds', 'inmost', 'wherein',
             'Ugh', 'position', 'Contemptuously', 'Word', 'merrier', 'concealment',
             'sly', 'Thine', 'ignorance', 'Once', 'haters', 'prophetic', 'professors',
             'blade', "we're", 'absolutely', 'Save', 'assault', 'Jason', 'Were',
             'jouped', 'boss', 'Amphipolis', 'chair', 'And', 'Evil', 'leader', 'longs',
             'One', 'laughter', 'cloudy', 'cared', 'That', 'gadfly', 'waxeth', 'person',
             'Please', 'falsehoods', 'signified', 'instruct', 'chance', 'moved', 'most',
             'terribly', 'bride', 'arm', 'mistress', 'ludicrous', 'weighty', 'enemies',
             "didn't", 'rate', 'sound', 'paths', 'sweet', 'separate', 'mortal',
             'attributed', 'Soup', 'Phipps', 'A', 'prisoner', 'pretend', 'curious',
             'Doctor', 'slip', 'strangest', 'plainness', 'customary', 'imposed',
             'dissembled', 'silence', 'Nor', 'conceit', 'Pooh', "Let's", 'reproaching',
             'passages', 'clasped', 'reproved', 'Gabon', 'right', 'fray', 'Better',
             'thousand', 'Childless', 'superior', 'dancing', 'ornamented', 'Even',
             'disparagingly', 'cease', 'Szgany', 'certainly', 'Aw', 'Seeketh', 'Namibia',
             'dares', 'softly', 'por', 'examining', 'political', 'Gate', 'tremble',
             'Mozambique', 'improver', 'beach', "can't", 'efforts', 'cognizance',
             'always', 'willing', 'Hunted', 'battle', 'success', 'draughts', 'Fly',
             'strength', 'ghastly', 'closely', 'Italy', 'class', 'deception', 'stir',
             'stirred', 'Wert', 'quarrel', 'batter', 'perished', 'denounce', 'rarer',
             'prize', 'litten', 'none', 'dividing', 'changed', 'producing', 'fancy',
             'seated', 'detraction', 'sent', 'voices', 'dawnedthey', 'Hippias', 'It',
             'hallucination', 'audience', 'Thy', 'minute', 'beguiled', 'examined',
             'yawn', 'just', 'Take', 'Liverpool', 'sufficient', 'shaped', 'five',
             "Lestrade's", 'except', 'Exclaiming.', 'Within', 'cannot', 'During',
             'Bangladesh', 'Rested', 'trackless', 'heed', 'untrodden', 'Cyprian', 'shed',
             'speculated', 'infinite', 'gum', 'odd', 'faces', 'inasmuch', 'weak',
             'brings', 'Grief', 'waited', 'wonder', 'figure', 'placing', 'fight',
             'encouragement', 'reigning', 'two', 'France', 'yield', 'Work', 'Yes',
             'answering', 'Hunter', 'hast', 'bounding', 'expect', 'Do', 'took', 'Seek',
             'darling', 'unnatural', 'moods', 'ever', 'Accordingly', 'White', 'bulls',
             'advise', 'drear', 'persons', 'sweep', 'Heavens', 'games', 'way',
             'censuring', 'military', 'summers', 'Unholy', 'age', 'deserve', "He's",
             'lay', 'waistcoat', 'accusers', 'clearly', 'injure', 'name', 'perhaps',
             'nature', 'fame', 'Bob', 'security', 'precinct', 'Try', 'introduced',
             'Christ', 'men', 'seal', 'temples', 'wood', 'wilt', 'Dark', 'drowned',
             'Bye', 'faculty', 'yet', 'Naturally', 'Bazley', 'smite', 'griefs', 'east',
             'betray', 'stain', 'avail', 'Colin']
