"""
Imported by `cpt_config.py` for use in the Tkinter GUI.

Variable:
    short_sentences (list): Short sentences for 25-40 second portion of typing test.
"""

short_sentences = ['Of course.', 'Leave me in peace!', 'I am afraid.',
                   'In a technical talk', "But by God's mercy.", 'He felt the change.',
                   'Or else Crevez.', 'Tell her tobegin!', 'You must know.',
                   "What's the slope?", 'If you can.', 'love thy neighbour.',
                   'I wish Father Jove.', 'And not from fear.', 'small workshops',
                   'It is excluded.', 'He shouted.', 'Not that your wife.',
                   'As for yourselves.', "She'll gallop.", 'Fully penitent.',
                   'So he at once said.', "Jove's daughter.", 'My darling.',
                   'I said to my men.', 'Gazing after him?', 'Fool that he was.',
                   "Don't be impudent.", 'Tell her tobegin.', 'What are they doing.',
                   'Hunting big game!', 'Practice makes more', 'Traces indeed.',
                   'Burning matches.', 'His eyes glowed.', 'Suddenly he started.',
                   'One less to keep?', 'You can smell ants?', 'And his wife.',
                   'Alice was silent.', 'I should think so.', 'When you exercise.',
                   'Even as wax melteth.', 'He continued.', 'Come sit down.',
                   'Probing her further.', 'As for the stranger.',
                   'In this type of talk', 'Yet if you like.', 'As regards mortals.',
                   'Addressing Zossimov.', 'Hunting big game.', 'Only to get it over.',
                   'South Africa', 'Now I have been ill?', 'How they push.',
                   'Father Eumaeus.', 'United Kingdom', 'How can i get copy?',
                   'What do you think.', 'Another must go to.', 'During that time.',
                   'Mad besides.', 'How much water?', 'Why was he here.',
                   'She came up to me.', 'If they question me.', 'If you can?',
                   'Goodness knows why.', ' he muttered.', 'He got him there.',
                   'It could come soon.', 'Bring me sulphur!', 'Ask a question',
                   'To smaller animals.', 'He passed him by.', 'Why do you go.',
                   'Put in Raskolnikov.', 'Most importantly', 'Quite right.',
                   'It was now daylight.', 'Strike me openly.', 'Observed Zametov.',
                   'She took his shape.', 'But with sour sugar.', 'The root was black.',
                   'He stood still.', 'To be sure?', 'I then bored a hole?',
                   'And I charge you.', ' what came of it?', 'Great Goddess Diana?',
                   'Dmitri Prokofitch?', 'Obtain feedback', 'You must admit that.',
                   'Ulysses saw her.', 'Semyon Zaharovitch.', 'Not a commonplace?',
                   ' what came of it.', 'Wake up Pisistratus.', "I don't want.",
                   "Don't be too sure.", 'Father stranger.', 'There I saw Helen.',
                   'What do you say.', 'You can smell ants.', 'There he married.',
                   'Leave me in peace.', "Apollo's messenger.", 'In a conference talk',
                   'Have you met before.', "That's enough.", 'After the talk',
                   'Sulphur dioxide?', 'Be off with you!', 'How do you mean.',
                   'drawing people in', 'Considerate even?', 'He answered dryly.',
                   'I am in great want.', 'As you say.', 'I am also stronger.',
                   'Gazing after him.', ' I should think so.', 'Is perfectly true.',
                   'And only fancy.', 'And rang at No.', 'With many kisses.',
                   'Generally speaking', 'Be off with you.', 'Now another point.',
                   'What a misfortune.', "You're a loose fish?", "D'you hear.",
                   'Do you know.', 'Then Euryalus said.', 'It is tyranny?',
                   'A good old woman.', 'Has a cleft palate.', 'Do you hear?',
                   'Without opening it.', 'Calypso went home.', 'While blessings.',
                   'His old thoughts.', 'That I know.', 'Use vocal energy',
                   " 'I was frightened.", 'Let me persuade you.', 'O swineherd Eumaeus?',
                   'Bring in the parcel.', 'conference talks', 'About my mother?',
                   'For instance.', "I'll be bound.", 'And his hometown.',
                   'Tell me also truly.', 'You are a one.', 'And he is my friend.',
                   'The sly dog.', 'Remember that', 'Believe me.', 'Mumbled Zossimov.',
                   'More simply.', 'meet new people', 'You country louts.',
                   "they won't do it", 'But Vrazumihin.', 'Relax and have fun',
                   'Light of my eyes!', 'This further grief.', 'He had not the axe.',
                   'As for Telemachus.', "Nastasya's with him.", 'Here was the gate.',
                   'So here you are.', 'All out of sight.', "You're a loose fish.",
                   'The hobbit has been.', "I don't want!", 'At that very hour.',
                   'He showed you too?', "I've no boots.", 'Telemachus Euryades.',
                   'What do you want.', 'Cried Raskolnikov.', 'Why do you keep on.',
                   'Not only that.', 'Dounia and I.', 'He knows me?',
                   'Confound you then.', 'Our one hope.', 'That is to say.',
                   "That's a sin.", 'The mules drew well.', 'Bring me sulphur.',
                   'Is it possible.', 'He was so kind.', 'what the axes mean',
                   'Matryoshka Dolls', 'Allow me to observe.', 'Is not the meanness.',
                   'So big and dense.', "For God's sake.", 'He asked suddenly.',
                   'What endurance too.', "'Press F10 to save'", 'You are forgetting.',
                   'beware the projector', 'Semyon Zaharovitch!', 'It is not right.',
                   'And mocked at him?', 'I shall never.', 'You are forgetting!',
                   "You'd be sure to.", 'He is injured.', 'Rex probably did.',
                   'If these Achaeans.', 'We have suffered?', 'She was howling.',
                   'The twin volcanoes.', 'Burkina Faso', 'Blinking eyelashes.',
                   'In these cases', 'I noticed that.', 'My dear father.',
                   "But we'll see.", 'As for your voyage.', "Therefore I'm mad.",
                   'Sail night and day!', 'But my dear nurse.', 'She added.',
                   'He is an Egyptian.', 'He embraced him.', 'He muttered!',
                   "It's strange though.", 'Cigarette case.', 'Opened her mouth.',
                   'Are fajitas Mexican?', 'For instance!', 'Pear grows on pear.',
                   'Well and what then.', 'Then a third man.', 'Than with them.',
                   'Nothing of the sort.', 'He will forgive.', 'On this Polites.',
                   'She must be forty.', 'He thought?', 'And cause headaches.',
                   ' Razumihin insisted.', 'United States', 'She is an angel.',
                   'He is very rich.', 'To be sure.', 'Winds from East.',
                   'Here he is himself.', 'And mocked at him.', 'You are harsh.',
                   'love thy neighbour?', 'No reason to.', 'I find that black',
                   'The devil.', "But we'll see!", 'Is epsom salt good?',
                   'THE LAESTRYGONES.', 'He turned round.', "Therefore I'm mad!",
                   'Not far from here.', 'As for the boar.', 'As for yourself.',
                   'Give him his helmet.', 'Presently she said.', 'I am a student.',
                   'Telemachus wept.', 'Immense experience.', 'Sail night and day.',
                   'Not Razumihin.', 'Hurriedly dressing.', 'For nearly 60 years.',
                   'This means that.', 'Not a commonplace.', 'Now I have been ill.',
                   'Just what I thought.', 'As for the day time.',
                   'So I lost my temper.', 'It is despotism.', 'She cried to him.',
                   "I don't know.", 'And a dirty one.', 'Mumbled Zossimov?',
                   'Just our friends?', 'South Sudan', 'Asked the waiter.',
                   'A friend of mine.', 'And the purse too.', 'Very good.',
                   'Only to get it over?', 'Razumihin agreed.', 'Do you hear.',
                   'Find collaborators', 'Wake up Penelope.', 'As for the suitors.',
                   'And so long ago.', "It's impossible.", 'She is mistrustful.',
                   'They do not breed.', 'The sly dog!', "It's my property.",
                   'The doors were gold.', 'My darling?', 'I am in great want?',
                   'Light of my eyes.', 'the main result', 'Like a leaf?',
                   'I am no prophet.', 'Tell an anecdote', 'The idea struck him.',
                   'To my horror?', 'He is very rich?', 'Just our friends.',
                   'One less to keep.', 'What does this mean.', 'He cried again.',
                   'Do you have to?', 'Blinking eyelashes!', 'My heart is beating.',
                   'At your service.', 'About This Article:', 'My poor unhappy man.',
                   "I'll show you.", 'Papua New Guinea', 'Like a leaf.',
                   'As for your own end.', 'He answered.', 'Tell me then truly.',
                   'More loudly.', 'Gilberto Baschiera!', 'He let go the helm.',
                   'I am still strong.', 'Has no will.', 'Why did I add that.',
                   'Wretched creature.', 'In other words,', 'This is the point.',
                   'The student.', 'practice some more', 'Farewell stranger.',
                   'Ask your father.', 'But now tell me.', 'She held a veil.',
                   "You've heard that.", 'Unstable Wi-Fi', "But don't mind me.",
                   'Not only that!', 'Man in general.', 'To my horror.',
                   'And sat down again?', 'working meetings', 'But heavens.',
                   'Let us be going.', 'Go to hell then.', 'Just now.',
                   'After scanning Mr.', 'They threatened him.', 'and your institution',
                   'It is tyranny.', 'He knew me and said.', 'He was overwhelmed.',
                   'There is no one.', 'We have suffered.', 'I want to get home?',
                   'I want to get home.', 'Am I not a goddess.', 'Neither his mother!',
                   'Ulysses himself.', 'Asked Razumihin.', 'More simply!',
                   ' I would say.', 'Formerly a student.', 'What does it mean?',
                   'I went to Cyprus.', 'I remember.', 'She bore Nestor.',
                   'Would you believe.', 'Coming here.', 'And proved it.',
                   'But she stopped!', 'I will put bread.', 'When Marmeladov.',
                   "D'you hear!", 'Volume adds emphasis', 'Who was listening?',
                   'And say nothing.', 'Their messenger!', 'And sat down again.',
                   'As much as I liked.', 'Why the word ought.', 'Leave off doing so.',
                   'Turn a little.', "Cote d'Ivoire", 'Dmitri Prokofitch.',
                   'All the time.', 'His head ached less.', 'and how to read it',
                   'Without hurry.', "Don't you mind her.", 'Impudent baggage.',
                   'We must lock up.', 'Have mercy upon me.', 'Life is real.',
                   'Who was listening.', 'Grinding his teeth.', 'Sitting up again.',
                   'I have already told.', 'Not to be beaten.', 'Here was his house.',
                   'Wearing a full.', 'You precious idiot.', 'Well and what then!',
                   'She cried to him?', 'This is your case!', 'She must be forty!',
                   'Furthermore I say.', 'and design elements', 'Give him the bow.',
                   'I know all about it.', 'All that time.', 'You will be unhappy.',
                   'Give it to her.', 'But he went on.', 'This god appeared.',
                   'Yesterday Zametov.', 'Stay where you are?', 'It is very possible.',
                   'When he was.', 'About 300,000', 'He is Egyptian.', 'She added!',
                   'Speed can energize', 'Queen Penelope.', 'I was all dismayed.',
                   'Began Zossimov.', 'I am not sure.', 'Scaling this up to.',
                   'All right.', 'He thought.', 'Known as moonquakes.',
                   'Considerate even.', 'He went on gaily.', 'If you were their.',
                   ' Razumihin insisted!', 'I only wanted.', ' and so on.',
                   'The sun was now set.', 'What can you do?', 'It was a disgrace.',
                   'New Zealand', 'As for my escort.', 'Order in person!',
                   'Strange to say.', 'Third class.', 'This is serious.',
                   'Heaven help me.', 'He wore spectacles.', 'I besought her aid.',
                   'But I prevented him.', 'What am I to do.', 'I wish Father Jove?',
                   '7 million dollars?', 'Messenger Mercury.', 'You are tired.',
                   'You are our all.', 'How many carbs?', 'In this grey house.',
                   'Nikolay Dementyev.', 'I began to jeer.', 'The drunkard.',
                   'Neither his mother.', 'They meant no guile.', 'She is only a woman.',
                   'Silent and frowning.', 'Here was the house?', "It's like a tomb.",
                   'Night was coming on.', 'What do you mean.', 'Muttered to himself.',
                   'Good heavens.', 'And I ran after him.', 'Flat Number 14.',
                   'Come along.', 'To be depended upon.', 'Excuse my saying so.',
                   'Raised his head.', 'You were wrong.', 'Like one distraught.',
                   "That's what's bad.", 'Then I said to them.', "That's very natural.",
                   'Meanwhile Ulysses.', 'They had just left.', 'What am I to do now.',
                   'As for Telemachus?', 'But come inside.', 'Exaggerating it all.',
                   'We are neighbours.', 'Then he got up.', "Don't be impudent?",
                   'After the wedding.', 'He knows me.', 'No mistake about it.',
                   'O swineherd Eumaeus.', 'Our one stay.', 'She is a quick girl.',
                   'Coming forward.', "She'll jog along.", 'You are not asleep.',
                   'Then they cut it up.', ' he muttered?', 'Pear grows on pear!',
                   'The cheapest.', 'If I were told.', 'It made me ill.', 'He was pale.',
                   'She was beseeching.', 'I am sorry for him.', 'What are you saying.',
                   'Along that theme.', 'Warm gratitude.', 'Sulphur dioxide.',
                   'Bear everything.', 'But Ulysses said.', 'Then Antinous said.',
                   'More than that.', 'Where are you going.', 'Exaggerating it all?',
                   'This smartness.', "That's evident.", 'Saudi Arabia',
                   'We are just here.', 'Again the hospital.', "That's very natural?",
                   'But for that.', 'How strange it was.', ' Do you hear.',
                   'I had nine ships.', 'I would obey you.', 'Let us then be off.',
                   'Poor gentle things.', 'When he got back.', 'Or as a blind.',
                   'Grinding his teeth!', 'What was I saying.', 'Good luck to you.',
                   'Bless my heart.', 'You filthy glutton.', 'You may amuse him.',
                   'They had separated.', 'Here was the house.', 'How Many ML Is 6 MG?',
                   'Fajita is a Tex-Mex.', 'An italian banker.', 'Martin, an island',
                   'Am I not a goddess!', 'Rex had feathers.', 'With gentle eyes.',
                   'Roused himself.', 'This is the point?', 'But she stopped.',
                   'She bore Nestor?', 'Another thought.', 'Almost physical.',
                   "And I'm sick of it.", 'The hopelessness.', 'Ten minutes passed.',
                   "At two o'clock.", 'And so at all costs.', 'Get you to your bed.',
                   'Stay where you are.', 'Ask the porter.', 'Eggs are rich.',
                   'To Razumihin.', 'Ajax was wrecked.', 'This is your case.',
                   'Then bring it to me.', 'May visit you also.', 'My dear boy.',
                   'In vexation.', 'Known as moonquakes?', 'He muttered.',
                   'You are right.', 'if all else fails', 'From a child.',
                   'The twin volcanoes!', 'She is afraid.', 'An obstinate.',
                   'Let my life go.', 'Her name is Arete.', 'A good old woman!',
                   'Their messenger.', 'I come from Alybas.', 'North Korea',
                   'We become casuists.', 'Queen Penelope!', 'O swineherd Eumaeus!',
                   'Gallop indeed.', 'I knew all about it.', 'Are you still here.',
                   'About my mother.', 'Tit Vassilitch.', 'I shall say no more.',
                   'German women.', 'PART THE SECOND.', 'Like a witchs oils.',
                   'And blue and white.', 'I bit my arm.', 'And every soul.',
                   'It passed me by.', 'PART THE FOURTH.', 'I saw that curse.',
                   'My lips were wet.', 'My throat was cold.', 'I fear thee.',
                   'Is it he.', 'Is this the man.', 'When a boy.', 'Though poorly clad.',
                   'And the master.', 'Used to say.', 'Le beau sabreur.',
                   'Partly by day.', 'A man who.', 'Disdainful of ease.',
                   'It is this spirit.', 'And turning iron.', 'On his own account.',
                   'So clear and pure.', 'Quire of Women.', 'Sound thou on.',
                   'The tear doth gush.', 'In every dance.', 'Nor terrors appall.',
                   'Take this pitcher.', 'I hasten on.', 'The day before me.',
                   'Under me the sea.', 'Am I awake.', 'He stands already.',
                   'With glaring eyes.', 'I have thee now.', 'Look at it well.',
                   'And in return.', 'We hate and love.', 'An under be.',
                   'And an above.', 'A wager on it.', 'Enter a Student.',
                   'We carry it home.', 'A sure possession.', 'O happy he.',
                   'It must be bought.', 'And Irene Adler.', 'And then he choked.',
                   'Limp and helpless.', 'In the chair.', "' she said.",
                   'As she left him.', 'We must have a cab.', 'On the contrary.',
                   'My dear sir.', 'Cried the King.', 'What is it.', "' I asked.",
                   "' said I.", 'As Spaulding said.', '‘This is Mr.', "' said he.",
                   'As he released me.', 'If you leave.', "' I answered.",
                   'I thought as much.', 'To-day is Saturday.', 'It was a pokey.',
                   'He waved his hand.', 'Turned on his heel.', "He's a young man.",
                   'It is past ten.', 'Here we are.', 'Close in swiftly.',
                   'With a rending.', 'One of the broad.', 'And left a square.',
                   'So I see.', 'The other answered.', 'As a rule.',
                   'And vulgar enough.', 'It is possible.', 'On the contrary.',
                   'Just as mine are.', 'There is a date.', 'The case has.',
                   'In some respects.', 'Was then called.', 'I left him.',
                   'But he is right.', 'I am sure.', 'Was one of them.',
                   'Mark that point.', 'That is it.', 'Holding it out.',
                   'But who is he.', 'It is obvious.', 'I tell you that.',
                   '] MABEL CHILTERN.', 'Same thing often.', 'She was untruthful.',
                   '[After a pause.', 'I am not changed.', 'My dear fellow.',
                   '] LORD GORING.', 'In your case.', 'It is only fair.', 'By the way.',
                   'It is so pretty.', 'To live the truth.', 'It is nothing.',
                   '] Lord Goring.', 'I am sure Mr.', '] MABEL CHILTERN.', 'If I had.',
                   '] Dear Lady Markby.', '] MABEL CHILTERN.', 'I need hardly say.',
                   'I prefer books.', '[The butler enters.', 'With either of you.',
                   '] LORD GORING.', 'And reads it.', '] LORD CAVERSHAM.',
                   'In this room.', 'During the Season.', 'From four to seven.',
                   'To share its life.', 'Here I am noble.', 'I am boyar.',
                   'And I am master.', 'The Count smiled.', 'If he can help it.',
                   'With an excuse.', 'He left me.', 'Hour after hour.', ') 12 May.',
                   'Or to any other.', 'Is it not so.', 'I quite understood.',
                   '* 15 May.', 'If I be sane.', 'The other was fair.',
                   'As fair as can be.', 'In a voice which.', 'Any of you.',
                   'I tell you all.', '* 19 May.', '* 31 May.', 'With his wide hat.',
                   'And high boots.', 'And in my garb.', 'As they think.',
                   'And in them.', 'We must part.', 'Such a soft.',
                   'In his stately way.', 'To the door.', 'The door is shut.',
                   'And to know that.', 'And yet My dear.', "' He wrung my hand.",
                   'I am afraid.', "That won't harm ye.", 'To my astonishment.',
                   'As I expected.', 'I would like a cat.', 'To get dressed.',
                   'She then cried.', 'To grasp the key.', 'Using the jaw.',
                   "Don't go away.", 'And approved fully.', 'Nor dim nor red.',
                   'Like Gods own head.', 'As through a grate.', 'Is that a DEATH.',
                   'And are there two.', 'Her lips were red.', 'And to and fro.',
                   'And in and out.', 'PART THE SIXTH.', 'What saw I there.',
                   'Lifeless and flat.', 'By the holy rood.', 'A man all light.',
                   'In any event.', 'We find Copernicus.', 'A workman at Lyons.',
                   'On the other hand.', 'Member for Salford.', 'The career of Mr.',
                   'And live at ease.', '—to travel abroad.', 'He did not.',
                   'Having once failed.', 'To his successors.', 'Even when a boy.',
                   'A model of which.', 'Driven by horses.', 'After the trial.',
                   'One of them said.', '{45} At length.', 'To the war.',
                   'Thy goodly round.', 'While He is near.', 'We to the mill.',
                   'And cheeks so red.', 'O pass not by.', 'Yet a few paces.',
                   'When over us.', 'But let us watch.', 'And all be well.',
                   'And a name.', 'House and hearth.', 'Accursed be Mammon.',
                   'Accursed be Hope.', 'Accursed be Faith.', 'Chorus of Spirits.',
                   'For love of God.', 'Close with my plan.', 'Or pen shall it be.',
                   'In magic veil.', 'From unseen hand.', 'Loss and gain.',
                   'Joy and sorrow.', 'There is a way.', "He's waited long.",
                   'As to this science.', 'Is a short time.', 'And high to climb.',
                   'To ruin me.', "I can't imagine.", 'Pacing up and down.',
                   "' she cried.", 'Ringing the bell.', 'We may take it.',
                   'As it pulled up.', 'Said a woman.', 'I motioned for air.',
                   'Never to return.', 'My dear Watson.', 'My dear Watson.',
                   'Said Jabez Wilson.', 'Near the city.', "' said I.", 'To an end.',
                   'Duncan Ross was.', 'On the contrary.', 'As I understand.',
                   'Richer by some £30.', 'I had a dozen.', 'As a rule.',
                   'What do you think.', 'It is all right.', 'Said the stranger.',
                   "It's all clear.", "' All right.", "I'm not rich.", 'For the Friday.',
                   'And your father.', 'Did you tell him.', 'Having lit it.',
                   'As to the letters.', 'Glancing over them.', 'Who was he.',
                   'He appears as Mr.', 'What do you say.', 'Said my wife.',
                   'Not a word.', 'A lad of eighteen.', 'So they have.',
                   'I then took my gun.', 'I dropped my gun.', 'He calls attention.',
                   'And with reason.', 'Her lips parted.', 'No one but Mr.',
                   'That is important.', 'I should think.', 'Sound at heart.',
                   'Of the Hall.', 'Winking at me.', 'When the maid.', 'It was damp.',
                   'There are none.', 'He raised his hand.', 'As you know.', 'It is so.',
                   'You will sign it.', 'Became wealthy men.', 'I did it.',
                   'I pray not.', '] LADY CHILTERN.', 'That is all.', 'May I try.',
                   'That is all.', 'The gospel of gold.', "I couldn't do it.",
                   'By the way.', 'You are not going.', '[To LORD GORING.',
                   '] I hope so.', 'What has poor Mr.', '[With a curtsey.',
                   'In yellow covers.', '] The fact is.', 'There is a pause.',
                   '] Do you know.', '] LADY CHILTERN.', 'Faults and all.', 'It may be.',
                   'For that reason.', 'Makes it indeed.', 'And so masters it.',
                   'I am coming to you.', 'Is it worth while.', 'My dear father.',
                   'At this hour.', 'He bowed gravely.', 'Even you would not.',
                   'I dare be sworn.', 'He answered: Well.', 'Away with it.',
                   'Wish to ship goods.', 'So that the client.', 'I desire it much.',
                   'Hawkins in secret.', 'And also to Mina.', 'If he did see it.',
                   'Entered the room.', 'Here I am.', 'I hope so.', 'But I fear.',
                   'Is it not so.', 'Which opened south.', 'The phantom shapes.',
                   'I looked down once.', 'The Count stood up.', 'Their red jaws.',
                   'Mina is a woman.', 'And by the sea.', 'We shall see.',
                   'But never mind.', 'I must stop.', 'From every one.',
                   "' My dear Mina.", 'Periods of gloom.', 'I am writing now.',
                   "An' the like.", 'Lies all of them.', 'I must watch him.',
                   'Or if at only one.', 'Had the same habit.', 'Another week gone.',
                   'Not even to Mr.', 'Another three days.', 'And no news.',
                   "But I'm content.", "And comin' quick.", 'With a rag of sail.',
                   'He said to himself.', 'Across the room.', 'But down below.',
                   'Where Gregor was.', 'It was dark.', 'For some reason.',
                   'Just as I expected.', 'Said his father.']
