"""
Imported by `cpt_config.py` for use in the Tkinter GUI.

Variable:
    long_sentences (list): Long sentences for 30-60 second portion of typing test.
"""

# Long sentences for 30-60 second portion of typing test.
long_sentences = ['His anger was mounting.', 'As soon as he has come up he.',
                  'How many calories burn?', 'Build a house in Nigeria?',
                  'We need an end of all such matter.', 'These were more in number.',
                  'Thick glasses helped him read the print.',
                  'In the rear of the ground floor was a large passage.',
                  'The bombs left most of the town in ruins.', 'I lie awake thinking!',
                  'He flung off his boots!', 'A wildlife technician.',
                  'They loosed the sack?', 'He may drown himself.',
                  'The couch cover and hall drapes were blue.',
                  'A round hole was drilled through the thin board.',
                  'acoustics also play a role', 'I have buried my tracks.',
                  'He wrote his last novel there at the inn.',
                  'What do i do if i lost my dri',
                  'The man wore a feather in his felt hat.',
                  'The brass tube circled the high wall.', 'Patroclus peer of gods in.',
                  'Some one may tell you.', 'Consider this matter I pray.',
                  'Sit down to your dinner.', 'You have perceived aright.',
                  'Is macrame hard to learn?',
                  'The youth drove with zest, but little skill.',
                  'Take the winding path to reach the lake.',
                  'Put the chart on the mantel and tack it down.',
                  'The small pup gnawed a hole in the sock.',
                  'The lamp shone with a steady green flame.',
                  'The heart of Ulysses was.', 'The dark pot hung in the front closet.',
                  "He hit Eupeithes'helmet.", 'First he killed Antinous.',
                  'There is an underwater.', 'Alice was thoroughly puzzled.',
                  'It is a mixing bowl of pure.',
                  'The latch on the back gate needed a nail.',
                  'Eight miles of woodland burned to waste.',
                  'The cold drizzle will halt the bond drive.', 'Alice sighed wearily!',
                  'But be sure and do as I bid.', 'Bending over the water.',
                  'The youngest pope in history.', 'Answered Raskolnikov.',
                  'We need not send them any!',
                  'Both lost their lives in the raging storm.',
                  'Birth and death mark the limits of life.', 'Observed Raskolnikov.',
                  'Keep your visuals simple', 'But Agelaus shouted out!',
                  'They are men who walk the middle of the road.',
                  'Adraste brought her a seat.',
                  'The door was barred, locked, and bolted as well.',
                  'And here you are again.',
                  'The heart beat strongly and with firm strokes.',
                  "'Go to the Boot menu.'", 'Jove counselled their.',
                  "Mayn't I ask a question.", 'Antinous scolded him and said.',
                  'They stowed everything.', "It's actually slowing?",
                  'O swineherd Eumaeus saying.', 'Soap can wash most dirt away.',
                  'Let water be poured over our?', 'Ulysses hit him on the right.',
                  'The thaw came early and freed the stream.',
                  'He rushed to the corner.', 'Then we cast lots in a helmet.',
                  'I will not spare you.', 'Both have a high potential fo',
                  'Seats were ranged all along.', 'With such fanaticism.',
                  'Are eyes always the same?', 'He took her right hand in.',
                  'Tell me also your country.', 'Then Telemachus sprang away?',
                  'The node on the stalk of wheat grew daily.',
                  'Paper is scarce, so write with much care.',
                  'They took the dead away.', "The soft cushion broke the man's fall.",
                  'They sacrificed the sheep.', 'For all valid claims we will.',
                  'Plead with the lawyer to drop the lost cause.',
                  'Drive the screw straight into the wood.',
                  'Their brains were shed upon.', 'If you cut down a saguaro.',
                  'Canned pears lack full flavor.', 'The day before yesterday.',
                  'Poached eggs and tea must suffice.', 'There were tall trees.',
                  'Using radiometric dating.', 'contain surprises in the plot',
                  'I will be chief too if I can.', 'Telemachus came first.',
                  'Standing around burns.', 'His spleen rose within him.',
                  'Hang tinsel from both branches.',
                  'Keep the hatch tight and the watch constant.',
                  'Avoid a meaningless argument.', 'Do they know about the flat?',
                  'Then they began to fight.',
                  'The logs fell and tumbled into the clear stream.',
                  'Those last words were a strong statement.', 'Are you going already.',
                  'BUT MINERVA CONCLUDES A PEACE.',
                  'The just claim got the right verdict.', 'If you point your car keys?',
                  '"  or "By reading my paper', 'In the midst of want.',
                  'The cloud moved in a stately way and was gone.',
                  'He could not have said why?', 'I will do you all the harm I!',
                  'Next Tuesday we must vote.', 'I know you are hard pressed.',
                  'They know nothing about ships.', 'Took the famous tongue.',
                  'The typical american sees at!', 'Here aforetime sat Neleus.',
                  'none of these "frills" matter', 'And they are pleased.',
                  'At the end of the talk', 'Quench your thirst, then eat the crackers.',
                  'The salt breeze came across from the sea.',
                  'He crawled with care along the ledge.',
                  'Corn is a gluten free grain,', 'Therefore pass these Sirens.',
                  'In the first edition.', 'Thus even in death your fame.',
                  'A whiff of it will cure the most stubborn cold.',
                  'When Circe strikes you with.', 'How are babushka dolls made?',
                  'A large size in stockings is hard to sell.',
                  'The famous line in titanic.', 'I can easily find another.',
                  'I have travelled much.', 'Observed Nikodim Fomitch.',
                  'Heaven put it in her heart.', 'Wipe the grease off his dirty face.',
                  'Avoid a monotone presentation',
                  'The harder he tried the less he got done.',
                  'The marsh will freeze when cold enough.', 'The largest known prime.',
                  'Then Vulcan came up to them.', 'I understand and heed.',
                  'Hear what I have to say.', 'But he has come to some.',
                  'The sun came up to light the eastern sky.',
                  'The red tape bound the smuggled food.', 'But when it was now...',
                  'The cigar burned a hole in the desk top.', 'Bid the suitors take.',
                  'I was never uneasy about you.', 'I am son of king Apheidas.',
                  'He will cut off your nose.', 'Acid burns holes in wool cloth.',
                  "Princess peach didn't move.",
                  'A bowl of rice is free with chicken stew.', "That's quite possible.",
                  'Take this to the stranger.', 'I sat up in bed and wept.',
                  'Yet grieve for these as I may.', 'It was as though the South.',
                  'A fresh start will work such wonders.', 'He admired their harbours.',
                  'You knew perfectly well.',
                  'The mute muffled the high tones of the horn.',
                  'The horn of the car woke the sleeping cop.',
                  'It was as though the South!',
                  'Dispense with a vest on a day like this.',
                  'It was done before the boy could see it.',
                  'The flint sputtered and lit a pine torch.',
                  'I want to go home at once?', 'March the soldiers past the next hill.',
                  'She blushed when he gave her a white orchid.',
                  'His heart was black with rage.', 'echoes and delays are at play',
                  'Muttered Nikodim Fomitch.', 'He sent me off first!',
                  'The barrel of beer was a brew of malt and hops.',
                  'A cramp is no small danger on a swim.', 'They stayed with me twelve.',
                  'It is an island covered with.',
                  'His hip struck the knee of the next player.',
                  'I called a council and said?',
                  'The ink stain dried on the finished page.',
                  'He broke a new shoelace that day.', 'I can tell you something.',
                  'Menelaus and Ulysses were.', 'Then he left the river!',
                  'The dry wax protects the deep scratch.',
                  'The meal was cooked before the bell rang.',
                  'They tell me you are his son?', 'Nine or ten tiny openings?',
                  'The corner store was robbed last night.',
                  'She had formerly been a mere.',
                  'The third act was dull and tired the players.',
                  'When they had made their.', 'As for your oath we will let.',
                  'Bribes fail where honest men work.', 'My grievance is purely.',
                  'I will not be long in?', 'The brown house was on fire to the attic.',
                  'Pink clouds floated with the breeze.',
                  'These coins will be needed to pay his debt.',
                  'Post no bills on this office wall.', 'Plain popcorn is gluten free.',
                  'This is your estimated load:', 'As I am always called.',
                  'A polar bear and a grizzly.', 'Somewhat disconcerted.',
                  'Bring your problems to the wise chief.',
                  'This will astonish everybody.', "Perhaps I'll simply tell.",
                  'I beseech you in your.', 'But he will be very angry?',
                  "Is servile and won't revolt.",
                  'The curtain rose and the show was on.',
                  'The lure is used to catch trout and flounder.',
                  'But as nothing followed.', 'It is full of beautiful.',
                  'Beavers live in a lodge they!', 'Mad on that very point.',
                  'She caused their drink to!', 'So astronaut literally means.',
                  'Eumaeus sprang to his feet.', 'Very much absorbed him.',
                  'I had to clear up my things.', 'Dragged about by his hair.',
                  'He wheeled the bike past the winding road.',
                  'There is not a single plant.',
                  'The black trunk fell from the landing.',
                  'The horse balked and threw the tall rider.',
                  'There is an underwater?', 'Pyotr Petrovitch went on!',
                  'He would touch it up himself.', 'Write at once or you may forget it.',
                  'I cannot understand it.', 'For there is always a risk.',
                  'If you can gain her over.', 'Take this to the stranger!',
                  'But as years went by.', 'I understand and heed!',
                  'I will also give him sandals!', 'Here not even a bird may pass.',
                  'The man made no answer.', 'Do not be angry with me.',
                  'Moreover the king swore in.',
                  'The spot on the blotter was made by green ink.',
                  'or by giving me a job', 'She is in love with Mars.',
                  'He is making quite a name?',
                  'One step more and the board will collapse.',
                  'The prince ordered his head chopped off.',
                  'It is a band of steel three inches wide.', 'Eurymedusa of Apeira!',
                  'Fill the ink jar with sticky glue.', 'She put him on a good cloak.',
                  'Have been married since 1995.', 'Ulysses sat by the fire?',
                  'Slash the gold cloth into fine ribbons.',
                  'But as Telemachus was thus?', 'As regards your question.',
                  'Then he left the river.', 'They did not attack my men.',
                  'There are twelve chief men.', 'Smoke poured out of every crack.',
                  'That move means the game is over.', 'This is what my father used.',
                  'I can take no excuses.', 'The young kid jumped the rusty gate.',
                  'Soak the cloth and drown the sharp odor.', 'It has two entrances.',
                  'In the majority of cases.', '4 million as wealthy.',
                  'We come from Ithaca under.', 'The pipe began to rust while new.',
                  'They felt gay when the ship arrived in port.',
                  'Oak is strong and also gives shade.',
                  'The shaky barn fell with a loud crash.', 'Asked Razumihin frowning.',
                  'The young prince became heir to the throne.',
                  'A pencil with black lead writes best.', 'They have eight limbs.',
                  'They can live up to two years!', 'I was never uneasy about you?',
                  'Then he went up to it.', 'What is the formula in excel?',
                  "It's easy to tell the depth of a well.",
                  'Volcanoes that were erupting.', 'I will show you the house!',
                  'How to calculate your...', 'I too will make trial of it.',
                  'your approach or solution', 'Smile when you say nasty words.',
                  'He was then coming from.', 'Sickness kept him home the third week.',
                  'Dill pickles are sour but taste fine.',
                  'A cone costs five cents on Mondays.', 'I will not prevaricate nor.',
                  'I do not wish to drive any.', 'He took her right hand in?',
                  'The green light in the brown box flickered.',
                  'A flat pack takes less luggage space.',
                  'Cut the cord that binds the box tightly.',
                  'overcommitted faculty members', 'North winds bring colds and fevers.',
                  'A clean neck means a neat collar.', "That's not what I want now.",
                  'Bail the boat to stop it from sinking.', 'On this they all shouted.',
                  'Tell me your little notion!', 'How long do you have to wait?',
                  "It's actually slowing.", 'If your master comes home.',
                  'But the rest stayed where.', 'Your son has done them no.',
                  'How to Calculate a Percentage',
                  'The hail pattered on the burnt brown grass.',
                  'A cloud weighs around a!', 'The pleasant hours fly by much too soon.',
                  'AND PHILOETIUS LEAVE THE TOWN.', "Don't worry yourself.",
                  'Presently she began again.',
                  'The boss ran the show with a watchful eye.',
                  'Which can make you feel dizzy.',
                  'The rise to fame of a person takes luck.',
                  'Sunday is the best part of the week.',
                  'Even the worst will beat his low score.', "I'm a man of experience.",
                  "I believe it's reality.", 'He surrounded the city with.',
                  'The gloss on top made it unfit to read.', 'Relax and stay confident',
                  'Three sons of Alcinous.',
                  'The farmer swapped his horse for a brown ox.',
                  'As though for his benefit.',
                  'A yacht slid around the point into the bay.',
                  'Thereon he said to Menelaus.', 'They brought in a five year.',
                  'A compliance function is resp', 'As though on purpose?',
                  'Then they loosed the hawsers.',
                  'The mail comes in three batches per day.',
                  'The game received multiple?',
                  "She saw a cat in the neighbor's house.",
                  'See the player scoot to third base.', 'She caused their drink to.',
                  'One insolent fellow said to.', 'I never yet saw any one so.',
                  'It is a good thing for you?',
                  'Choose between the high road and the low.',
                  'Act on these orders with great speed.',
                  'The peace league met to discuss their plans.',
                  'Dinner is not a bad thing.', 'I will also give him sandals.',
                  'I will carry him off in your.', 'Aldermen and town councillors.',
                  'I think thatwill be the best.',
                  'The goose was brought straight from the old market.',
                  "It's awfully stupid though!", 'It lies squat on the horizon.',
                  'Here there were no taverns.', 'She would trust me again.',
                  'A chink in the wall allowed a draft to blow.',
                  'Tell her a part only.', 'She danced like a swan, tall and graceful.',
                  'and schedules may not line up', 'One habit of intelligent.',
                  "Haven't I lived just now.", 'It is all coming true.',
                  'It was quite deserted.',
                  'The loss of the second ship was hard to take.',
                  'Seed is needed to plant the spring corn.',
                  'The paper box is full of thumb tacks.', "I don't agree with you.",
                  'He sent the figs, but kept the ripe cherries.',
                  'The stray cat gave birth to kittens.', 'But the real geniuses.',
                  'I was astonished as I saw.',
                  'The heap of fallen leaves was set on fire.',
                  'Beat the dust from the rug onto the lawn.',
                  'When they reached the House.', "That's what I've forgotten.",
                  'If you felt free from guilt?', 'Here no wind beats roughly?',
                  'Told us the whole story.', "Don't you worry yourself.",
                  'You knew perfectly well!', 'He asks you to wait till.',
                  'There was a dead silence.', 'Never forgive the old woman.',
                  "Pack the kits and don't forget the salt.",
                  'Do not be in a hurry to send?', "Plankton's computer wife!",
                  'Raskolnikov went out.', 'The png was invented as an.',
                  'The source of the huge river is the clear spring.',
                  'You must not give him.', 'We were among the first he!',
                  'The junk yard had a mouldy smell.', 'Ulysses will not return.',
                  'Beavers live in a lodge they.', 'Suitors of my noble mistress.',
                  'If you mumble your speech will be lost.',
                  'A tame squirrel makes a nice pet.', 'His heart was beating.',
                  'For the Cyclopes have no.', 'When Ulysses got there.',
                  'I saw no more of you.', 'The first one opened in 1982.',
                  'Penelope laughed when she.', 'Every one approved his saying.',
                  'Pile the coal high in the shed corner.',
                  'The child almost hurt the small dog.', '000 during this time.',
                  'We tried to replace the coin but failed.',
                  'I will show you the house.', 'I am Ulysses son of Laertes!',
                  'Footprints showed the path he took up the beach.',
                  'Madam, this is the best brand of corn.',
                  'Down that road is the way to the grain farmer.',
                  'Thieves who rob friends deserve jail.',
                  'He asks no person to vouch for him.', 'It has two entrances?',
                  'Wake and rise, and step into the green outdoors.',
                  'I have trouble enough of my.', 'On the higher parts of lofty.',
                  'A small creek cut across the field.',
                  'The kite flew wildly in the high wind.', 'He thought gleefully?',
                  'What do you think of him.',
                  'The zones merge in the central part of town.',
                  'The grass and bushes were wet with dew.',
                  'The empty flask stood on the tin tray.',
                  'When they reached the House!', 'The Palais de Cristal?',
                  'The new prime number is 2.', 'Show me the way to your town!',
                  'The three story house was built of stone.',
                  'Back when dinosaurs existed.',
                  'The bloom of the rose lasts a few days.',
                  'Tack the strip of carpet to the worn floor.',
                  'Threatened or being squished.',
                  'It was a bad error on the part of the new judge.',
                  'He knew the skill of the great young actress.',
                  'They are pushed back each time they attack.',
                  'After this he went away.',
                  'Tuck the sheet under the edge of the mat.',
                  'Pure bred poodles have curls.', 'I gave him twelve light.',
                  'They were approaching!', 'There is a fine hard tang in salty air.',
                  'But Ulysses gave a great cry.', 'The small red neon lamp went out.',
                  'It matters not if he reads these words or those.',
                  'Continued Nikodim Fomitch.', 'As everyone called her.',
                  'Here Ulysses lay down!', 'It takes a good trap to capture a bear.',
                  'He wrote his name boldly at the top of the sheet.',
                  'Those words were the cue for the actor to leave.',
                  'This is what my father used?',
                  'Paint the sockets in the wall dull green.',
                  'If you lose your license...', 'I am sorry for father.',
                  'She had formerly been a mere?', 'Federal laws apply to everyon',
                  "A ripe plum is fit for a king's palate.",
                  'If you see them ill treating.', 'Telemachus Amphimedon?',
                  'The money comes from.', 'And of course they would.',
                  'Ulysses is indeed dead.', 'The british government.',
                  'When we were close to her.', 'While we were taken up with.',
                  'A rod is used to catch pink salmon.', "'Exit the BIOS Setup'",
                  'I did not miss what I aimed.',
                  'The rude laugh filled the empty room.', 'The base remained where it.',
                  'Therefore I will tell you.', 'He threw his arms about him.',
                  'Hoist the load to your left shoulder.', 'I am sure you must be!',
                  'Trample the spark, else the flames will spread.',
                  'There is something else?', 'Then draw your sword and sit.',
                  'No matter how far you go!',
                  'The kite dipped and swayed, but stayed aloft.',
                  'Alcinous therefore said to.', 'I am ready to ask pardon.',
                  'Any talk represents you', 'I vote the young lady tells.',
                  'Before the Achaeans went to.',
                  'A vent near the edge brought in fresh air.',
                  'Ulysses had been long gone.',
                  'The square wooden crate was packed to be shipped.',
                  'Adding fast leads to wrong sums.', 'Type out three lists of orders.',
                  'In the majority of cases?', 'And even if you were right.',
                  'Rice is often served in round bowls.', 'Everyone was talking.',
                  'The stitch will serve but needs to be shortened.',
                  'I suspected his intention.',
                  'The roof should be tilted at a sharp slant.',
                  'The slang word for raw whiskey is booze.',
                  'if your talk is not clear', 'Bring a seat with a fleece.',
                  'The glow deepened in the eyes of the sweet girl.',
                  'research group meetings', 'Feel the heat of the weak dying flame.',
                  '000 other bricks before it.', "'Press F2 to enter BIOS Setup",
                  'Slide the bill between the two leaves.', 'Answered the young man.',
                  'I appeal more especially to.', 'Four hours of steady work faced us.',
                  'The old pan was covered with hard fudge.',
                  'The vane on top of the pole revolved in the wind.',
                  'It snowed, rained, and hailed the same morning.',
                  'The ramp led up to the wide highway.', 'You have feared neither God.',
                  'One australian cattle dog?', 'The play began as soon as we sat down.',
                  'Schools for ladies teach charm and grace.',
                  'I will come down to the city.', 'Would that Apollo would so.',
                  'Why Is SCM Important? SCM is.', 'Nine or ten tiny openings.',
                  'Appear on the periodic table.',
                  'The club rented the rink for the fifth night.',
                  'What Is Pink Himalayan Salt?', 'Home AC is leaking water?',
                  'And a number of people have!',
                  'They could laugh although they were sad.',
                  'I dare not let myself think.', 'I will hide nothing from you.',
                  'There are many ways to do these things.',
                  'She called his name many times.',
                  'He used the lathe to make brass objects.', 'They knew me at once.',
                  'Is kettle corn gluten free?', 'Flossing prevents gum disease?',
                  "We're happy to provide one.", 'We had to row at first.',
                  'He has sent me to call you.',
                  'Flood the mails with requests for this book.',
                  'So you see I know all about?', 'Do us citizens need a visa?',
                  'The sky in the west is tinged with orange red.',
                  'I have changed my mind.', 'She was waiting at my front lawn.',
                  'When we got to Sunium.', "Hershey's kisses are named?",
                  'I am oppressed with care?',
                  'Three for a dime, the young peddler cried.',
                  'We need grain to keep our mules healthy.',
                  'Alcinous and Ulysses both.', 'Say it slowly but make it ring clear.',
                  'When the child of morning.', 'and so forth) will disappear',
                  'Glue the sheet to the dark blue background.',
                  'He girded his sword about.',
                  'The wharf could be seen at the farther shore.',
                  'You are the chief man here.', 'We did not get on much.',
                  'A speedy man can beat this track mark.',
                  'The red paper brightened the dim stage.',
                  'I was for jeering at the mite?', 'The glass lens was added in.',
                  'I am full of heaviness?', 'A zestful food is the hot-cross bun.',
                  'I do not much think they.', 'They instead breathe through.',
                  'Try to have the court decide the case.',
                  'I want to get back and so do.',
                  'The box is held by a bright red snapper.',
                  'Turn on the lantern which gives us light.',
                  'Presently he turned sick.', 'The fruit peel was cut in thick slices.',
                  'They stowed everything?', 'She said a moment later.',
                  'I am an excellent archer.', 'What are underlying shares of',
                  'Some god must have told them.', 'The birds all flew on our?',
                  'This process is called.',
                  'Fill your pack with bright trinkets for the poor.',
                  'In many cases, persistent pai', 'Paper will dry out when wet.',
                  'Feed the white mouse some flower seeds.',
                  'But Venus took care of them.', "That's the last straw.",
                  'Ulysses sat by the fire.', 'I would have you hold your.',
                  'The juice of lemons makes fine punch.',
                  'Glass will clink when struck by metal.', 'Violin bows are commonly.',
                  'The ethiopian calendar is 7.', 'Alice felt dreadfully puzzled!',
                  'I should like to give it to.', 'I filled a large skin with.',
                  'When at the last ball!', 'A dash of pepper spoils beef stew.',
                  'If Ulysses comes to his own.', 'He scowled at him and cried.',
                  'A stiff cord will do to fasten your shoe.',
                  'The pods of peas ferment in bare fields.',
                  'The train brought our hero to the big town.',
                  'Good luck to you too my.',
                  'The pencil was cut to be sharp at both ends.',
                  'You see it is hot now.', 'Somebody has told Heruvimov.',
                  'Jump the fence and hurry up the bank.',
                  'As soon as he had done so he.', 'He went on board and sat in.',
                  "In saying that it's not new.",
                  'The shelves were bare of both jam or crackers.',
                  'Serve the hot rum to the tired heroes.', 'When they had all put on.',
                  'Nastasya cried suddenly.', 'No need to explain that.',
                  'He saw the point at once.', 'Zossimov will be there too.',
                  'Bathe and relax in the cool green grass.',
                  'As bacteria are so light?',
                  'The weight of the package was seen on the high scale.',
                  'Rumour went round the town.', 'I hope you will apprehend my.',
                  'A pod is what peas always grow in.',
                  'Clams are small, round, soft, and tasty.',
                  'to simulate the environment',
                  'He offered proof in the form of a large chart.',
                  'Grace makes up for lack of beauty.',
                  'Raise the sail and steer the ship northward.',
                  'You shall pay for it with.',
                  'Shut the hatch before the waves push it in.',
                  'Pitch the straw through the door of the stable.',
                  'He drank everything away.', 'Her tongue was unloosed.',
                  'Next Sunday is the twelfth of the month.',
                  'Razumihin made a movement.', 'You ill conditioned cur?',
                  'Rake the rubbish up and then burn it.', 'Due to being rich in.',
                  'It is hard to erase blue or red ink.', 'I am lost in admiration.',
                  'Squealing like a little pig.', 'Presently he soared off into.',
                  'Most of the news is easy for us to hear.',
                  'Within a deep pool of water.',
                  'The loss of the cruiser was a blow to the fleet.',
                  'They loosed the sack.', 'Lasting over 680 years?',
                  "Which is the founder's name?", 'Which shone with a watery.',
                  'When he had thoroughly.', 'Not a day or night comes out.',
                  'He snatched up one of them.', 'In some form or other we need fun.',
                  'With evident enjoyment.', 'Let us be up and do that in.',
                  'When she had given it me.', 'Mauna kea and mauna loa in?',
                  'Each penny shone like new.',
                  'Seven seals were stamped on great sheets.',
                  'To have is better than to wait and hope.', 'Some one may tell me.',
                  'Greet the new guests and leave quickly.',
                  'Menelaus rose and dressed.', 'As the sail bellied out with.',
                  'He was always very patient.', 'We were among the first he.',
                  'I am not mocking you.', "It's one of the few capitals.",
                  'Nintendo trademarked Mario.', 'He was afraid of pursuit.',
                  'When the wine had got into.', 'But I did not catch him.',
                  'There were tall trees!', 'The son of Tydeus went on.',
                  'The plant grew large and green in the window.',
                  'And cleared his throat.',
                  'The hinge on the door creaked with old age.', 'But at such a moment.',
                  "It's a dense crowd in two distinct ways.", 'I am not worthy of you.',
                  'The old woman ran after him.', 'The boy owed his pal thirty cents.',
                  'A joy to every child is the swan boat.',
                  'Ulysses was glad when he saw.', 'He was descended from.',
                  'The streets are narrow and full of sharp turns.',
                  'Asked Pyotr Petrovitch.', 'I can have no desire to go?',
                  'She went up to the citizens.',
                  'The drip of the rain made a pleasant sound.',
                  'Let water be poured over our.', 'Read verse out loud for pleasure.',
                  'But still did not scream.',
                  'The wreck occurred by the bank on Main Street.',
                  'You are the chief man here!', 'Your party yesterday.',
                  'As though on purpose.', 'What are the differences?',
                  'Loop the braid to the left and then over.',
                  'Then Theoclymenus said to.', 'Her purse was full of useless trash.',
                  'So you see I know all about.', 'He is making quite a name.',
                  'This strong arm shall shield your honor.',
                  'How long does it take to get.',
                  'The news struck doubt into restless minds.',
                  'I lost my head completely.', 'Ino daughter of Cadmus.',
                  'He lifted up his hands to.', 'How much does it cost?',
                  'Help me now as you did then.',
                  'The chap slipped into the crowd and was lost.',
                  'New pants lack cuffs and pockets.', 'When he had taken aim he let.',
                  'He was in a furious passion!', 'It held a dove in its talons.',
                  'Moderation is best in all.',
                  'Write a fond note to the friend you cherish.',
                  'Here the Graces bathed her.', 'Hippos can even sleep.',
                  'Rather than the reflection.', 'The large house had hot water taps.',
                  'I can easily find another!', 'Heave the line over the port side.',
                  'Then Telemachus sprang away.', 'Going to sleep again.',
                  'Has left my head rather.', "This bow is a man's matter.",
                  'This makes it a safe snack!', 'Open your book to the first page.',
                  'They went down a turning.', 'There we fought for nine.',
                  'A siege will crack the strong defense.',
                  'It is a very celebrated place.', 'I will yoke my horses.',
                  'Has left my head rather!', 'The Knave shook his head.',
                  'She mended a shirt for you.',
                  'The nozzle of the fire hose was bright brass.',
                  'A smatter of French is worse than none.',
                  'A saw is a tool used for making boards.',
                  'I will both help to kill him.', 'As for my ship it is lying.',
                  'How much does it cost to adve',
                  'The bills were mailed promptly on the tenth of the month.',
                  'There are not ten suitors.', 'Pluck the bright rose without leaves.',
                  'Slide the box into that empty space.', 'But no one liked him.',
                  'Keep it simple and spartan', 'Idare say there may be one.',
                  'Screw the round cap on as tight as needed.',
                  'The Hatter shook his head.', 'A cold dip restores health and zest.',
                  'Cars and busses stalled in snow drifts.', 'He will also tell you.',
                  'Porfiry said amiably?', 'When she reached the suitors!',
                  'Slipped back into his mind.',
                  'The beetle droned in the hot June sun.',
                  'A pink shell was found on the sandy beach.',
                  'The screen before the fire kept in the sparks.',
                  'And seeing how late it was.', 'We went over them all.',
                  'There the flood mark is ten inches.', 'He could not rest on one.',
                  'On the islands the sea breeze is soft and mild.',
                  'The first part of the plan needs changing.',
                  'We need not send them any.',
                  'Crouch before you jump or miss the mark.',
                  'Nudge gently but wake her now.',
                  'A wisp of cloud hung in the blue air.', 'particularly with busy',
                  'Then he said to Ulysses.', 'I cannot eat in peace.',
                  'The baby puts his right foot in his mouth.',
                  'To reach the end he needs much courage.', 'I climb the hill side.',
                  'The hog crawled under the high fence.', 'That would not suit me.',
                  "They're as thick as thieves.",
                  'The ram scared the school children off.',
                  'Somebody has told Heruvimov?', 'When mice live in the wild.',
                  'Shepitied him deeply.', 'It contains two communities.',
                  'Mark the spot with a sign painted red.',
                  'The rarest spice comes from the far East.', 'Was not afraid at all.',
                  "To that end, you'll need more",
                  'Jerk the cord, and out tumbles the gold.', 'Along with her came her?',
                  'When the frost has come it is time for turkey.',
                  'For a map to be completely.', 'Men think and plan and sometimes act.',
                  'She will mix a mess for you.', 'The Dormouse slowly opened.',
                  'Then I set my foot upon him.', 'I sat up in bed and wept?',
                  'Can he have gone away.', 'The birch looked stark white and lonesome.',
                  'Laughing and making jokes.',
                  'The fruit of a fig tree is apple-shaped.',
                  'Therefore I am suppliant at.', 'I called a council and said.',
                  'This made Ulysses very angry.', 'I will also give you clothes.',
                  'There is a lag between thought and act.',
                  'A cruise in warm waters in a sleek yacht is fun.',
                  'A lame back kept his score low.', 'King Neptune watched him as!',
                  'Such was I in battle.', 'Lift the square stone over the fence.',
                  'And where are my clothes.', "It's a way out of it!",
                  'But Dounia was vexed.',
                  'They took their kids from the public school.',
                  'The Mock Turtle went on.', 'Lush fern grow on the lofty rocks.',
                  'I shall have to hear about.', 'Every projector is different',
                  'Pick a card and slip it under the pack.', 'Are LYFT drivers allowed?',
                  "Perhaps I'll simply tell!", 'So we asked heaven for a sign.',
                  'The eyes are always the same.', 'When they saw it they were!',
                  'Peep under the tent and see the clowns.', 'When at the last ball.',
                  'Jazz and swing fans like fast music.', 'And shook her head at me.',
                  'A good book informs of what we ought to know.',
                  'The Navy attacked the big task force.',
                  'Add the column and put the sum here.', "An apology can't be used as.",
                  'Another may be as handsome.', 'Therefore you shall die.',
                  'It was a nice conversation.', 'If it had been their doing!',
                  'The beauty of the view stunned the young boy.',
                  "There's a nice young man.", 'I will arm myself as well.',
                  'Mysterious seismic activity.', 'At that high level the air is pure.',
                  'The bark of the pine tree was shiny and dark.',
                  'Salamanders and lizards.', 'In the stifling heat.',
                  'We frown when events take a bad turn.',
                  "We don't like to admit our small faults.",
                  'Move the vat over the hot fire.',
                  'Tight curls get limp on rainy days.', 'With such fanaticism?',
                  'I think I may as well go in.', 'They wept bitterly in their.',
                  'The largest known prime?', ' for a thousand versts.',
                  'You were beside yourself.', 'Your name is down there.',
                  'A list of names is carved around the base.', 'I would send you more.',
                  'I am oppressed with care.',
                  'The fish twisted and turned on the bent hook.',
                  'The hostess taught the new maid to serve.',
                  'A break in the dam almost caused a flood.',
                  'A gray mare walked before the colt.', 'I shall have to hear about!',
                  'But let us say no more!', 'The buddha commonly depicted.',
                  'Prove the women by all means!', 'He shall have my sword.',
                  'You may preach as much as.', 'What does that matter.',
                  'Over the course of 7 years.', 'Idare say there may be one?',
                  'She took me in and was kind.', 'Sweet words work better than fierce.',
                  'You shall have the mules.', 'Supper was then served.',
                  'He lent his coat to the tall gaunt stranger.',
                  'They started at once.', 'Eumaeus sprang to his feet!',
                  'Green ice frosted the punch bowl.', 'I have travelled much?',
                  'Shouted a loud voice.', 'A castle built from sand fails to endure.',
                  'I make all my lays myself.', 'It would be a long story?',
                  'Some ads serve to cheat buyers.', 'He went moodily home.',
                  'They pulled without flagging.', 'The man is not yet born.',
                  'Arete was the first to speak?', "It's past two o'clock.",
                  'He picked up the dice for a second roll.',
                  'Draw the chart with heavy black lines.', 'These he let out the goat?',
                  'Tear a thin sheet from the yellow pad.',
                  '6 million people who live in.', 'As regards your questions.',
                  'The student said hotly.', 'As for my not coming near you.',
                  'The slush lay deep along the street.', 'Then they reached Pherae.',
                  'They slice the sausage thin with a knife.',
                  'The real buddha was actually.', 'Telemachus said to the son!',
                  'We find joy in the simplest things.', 'The birds all flew on our.',
                  'Looked out of the window.',
                  'The case was puzzling to the old and wise.',
                  'Who had long been dead.', 'A pot of tea helps to pass the evening.',
                  'Such was I in battle!', 'A crumpled shirt front.',
                  'The colt reared and threw the tall rider.',
                  'The grass curled around the fence post.',
                  'Jerk the rope and the bell rings weakly.',
                  'He takes the oath of office each March.', 'It is indeed nearly bed.',
                  'How long does it take?', 'We now have a new base for shipping.',
                  'Mince pie is a dish served to children.',
                  'Beef is scarcer than some lamb.', 'There we found a woman.',
                  'And at once he leaped up.', 'When we got there we beached.',
                  "Ripe pears are fit for a queen's table.",
                  'The duke left the park in a silver coach.',
                  'Opposite them sat Penelope.',
                  'These days a chicken leg is a rare dish.',
                  'The set of china hit the floor with a crash.',
                  'Light maple makes for a swell room.',
                  'A ridge on a smooth surface is a bump or flaw.',
                  'Burn peat after the logs give out.',
                  'Try to trace the fine lines of the painting.',
                  'I am in great trouble.', " That's a way of going on?",
                  'For "high-stakes" talks', 'Women form less than half of the group.',
                  'It will be worth a great.',
                  'A gem in the rough needs work to polish.',
                  'Fasten two pins on each side.', 'It came out to be around 700.',
                  'A gold vase is both rare and costly.', 'He had spoken the truth.',
                  'Heaven forbid that I should.', 'There is something else.',
                  '000 birds each year in the UK.', 'If we face such numbers as.',
                  'A cure for psychopathy.', 'Cap the jar with a tight brass cover.',
                  'The gold ring fits only a pierced ear.',
                  'And a number of people have.', 'Take their horses out.',
                  'They brought sheep and wine!',
                  'Sit on the perch and tell the others what to do.',
                  'Bring in the best pig you.', 'Macrame patterns and knots ar',
                  'All that you have been saying?', 'Telemachus said to the son.',
                  "You wouldn't believe!",
                  'The point of the steel pen was bent and twisted.',
                  'A severe storm tore down the barn.', 'Ulysses has died in a far.',
                  'A young child should not suffer fright.',
                  'in front of a live audience', 'How to tell if your...',
                  'After the dance, they went straight home.',
                  'The pirates seized the crew of the lost ship.',
                  'They were approaching.', 'I have no wish to set myself.',
                  'But now let us go to bed.', 'Many cities did he visit.',
                  'And the Gryphon never learnt.', 'From that moment I saw them?',
                  'Mars made Venus many presents.', 'Alcinous and Ulysses both!',
                  'She flew weeping to his side.', '7 million dollars for their.',
                  'I had any number of servants.',
                  'The smell of burned rags itches my nose.',
                  'The ancient coin was quite dull and worn.',
                  'I see the likeness just as.', 'There are luscious figs also.',
                  'Then Vulcan came up to them?', 'How does species richness aff',
                  'Screen the porch with woven straw mats.',
                  'Idomeneus sailed for Troy.', 'The tongs lay beside the ice pail.',
                  'Meaning that prior to 2016.',
                  'Stop whistling and watch the boys march.',
                  'Then he roused Telemachus.',
                  'Shake the dust from your shoes, stranger.',
                  'Cut the pie into large parts.',
                  'A pound of sugar costs more than eggs.',
                  'I will find wives for both.', 'Their servants are all young.',
                  'And whom he had never seen.', 'Their brains were shed upon!',
                  "You'll drive me crazy too.", 'He says he is a Cretan.',
                  'Slipped back into his mind?', 'Or if you will plough.',
                  'There is a great town there.', 'Compared to the northern.',
                  'The stems of the tall glasses cracked and broke.',
                  'Calves thrive on tender spring grass.',
                  'Their eyelids droop for want of sleep.', 'Do not be angry with me!',
                  'He could see him sailing.', "And I've done homage.",
                  'The slab was hewn from heavy blocks of slate.',
                  'They know nothing about ships!',
                  'A six comes up more often than a ten.',
                  'The aim of the contest is to raise a great fund.',
                  'She was daughter to Dolius.', 'It lies squat on the horizon?',
                  'But as Telemachus was thus.', 'We can attend to that later.',
                  'And that she would never.', 'No matter how far you go.',
                  'Why had he never expected?', 'The friendly gang left the drug store.',
                  'My delight was in ships.', 'This plank was made for walking on.',
                  'Never mind my mother.', 'He smoke a big pipe with strong contents.',
                  'I will tell you all about it.', 'You know how I love you.',
                  'If you drive in Turkey...', 'She held steadily on her.',
                  'Look in the corner to find the tan shirt.',
                  'Always close the barn door tight.', 'Every one in that country.',
                  'As though suddenly cut off.', 'It takes heat to bring out the odor.',
                  'Thus brooding as he sat.', 'Of course it is strange.',
                  'The sheep were led home by a dog.',
                  'Hemp is a weed found in parts of the tropics.',
                  'Better hash is made of rare beef.',
                  'Will you please answer that phone.', 'And stood in the window.',
                  'My clothes are wretchedly.', 'There are more than two factors here.',
                  'I will not conceal it from.',
                  'The mule trod the treadmill day and night.',
                  'The pearl was worn in a thin silver ring.',
                  'Is corn silk for clothing?',
                  'The team with the best timing looks good.',
                  'Plead to the council to free the poor thief.',
                  'He threw down the shaft.', 'Do you submit to this tamely.',
                  "I've done with fancies.", 'Worms and ants are more relat',
                  "Fortunately, I've got a basel",
                  'The dirt piles were lines along the road.',
                  'All sat frozen and watched the screen.',
                  'The night shift men rate extra pay.',
                  'Brass rings are sold by these natives.',
                  'A thing of small note can cause despair.',
                  'I kept my own ship outside.', 'I see how abominably you are.',
                  'He is avoiding the suitors.', 'We are sure that one war is enough.',
                  'It discomfits their enemies.', 'Medieval chastity belts are.',
                  'She understands the man?',
                  'A toad and a frog are hard to tell apart.',
                  'If it had been their doing.', 'So they came up one after.',
                  'The hogs were fed chopped corn and garbage.',
                  'Shape the clay gently into block form.',
                  'A cloud of dust stung his tender eyes.',
                  'The quick fox jumped on the sleeping cat.',
                  'She will then be frightened!',
                  'To send it now in large amounts is bad.', 'Alice sighed wearily.',
                  'I will return at once.', 'Iceland does not have a!',
                  'When space invaders was.',
                  'The horse trotted around the field at a brisk pace.',
                  'You are not a Christian.', 'Here no wind beats roughly.',
                  'The pipe ran almost the length of the ditch.',
                  'My position is intolerable.', 'She will then be frightened.',
                  'She also gave him a sharp!',
                  'He broke his ties with groups of former friends.',
                  'Castor breaker of horses.',
                  'The hitch between the horse and cart broke.',
                  'She is very feeble now.', 'Poverty is not a vice.',
                  'The price is fair for a good antique clock.',
                  'I wish you would stay here.',
                  'A brown leather bag hung from its strap.', 'He told her everything.',
                  'The fly made its way along the wall.',
                  'He was spotted by jamie foxx.', 'I shall feel easier myself.',
                  'There is a strong chance it will happen once more.',
                  'As I am always called!', 'How do you heal a zombie?',
                  'This was an immeasurable.', 'The phalanstery is ready.',
                  'Note closely the size of the gas tank.', 'This is all over now.',
                  'I will not be long in.', 'Will you pay me back.',
                  'provide an email address)', 'Why do you not bring him here.',
                  'A streak of color ran down the left edge.',
                  'He cried in a transport.', 'I lie awake thinking.',
                  'If your car fails its MOT you', 'Which prevents stiff blood.',
                  'A student and gentleman.', 'And you had to pay a license.',
                  'A force equal to that would move the earth.',
                  'Sell your gift to a buyer at a good gain.',
                  'Ulysses leading the way.', 'I will allow her to wash them.',
                  'What are the requirements?', "Mayn't I ask a question!",
                  'but as a general rule',
                  'The sofa cushion is red and of light weight.',
                  'As the sail bellied out with?', 'When Ulysses saw him so worn.',
                  'The chair looked strong but had no bottom.',
                  'The play seems dull and quite stupid.', 'That his hands trembled!',
                  'Many cities did he visit!', 'The "Are You Experienced" album',
                  'Tell it to herself alone.', " That's a way of going on.",
                  'Dots of light betrayed the black cat.', 'And were only unearthed in.',
                  'We let the ships run before!',
                  'The kitten chased the dog down the street.',
                  'The children were terrified.', 'When Telemachus came up.',
                  'Bring a whip each of you.',
                  'Be sure to set the lamp firmly in the hole.',
                  'Nestor then addressed them.', 'Transcription copies the DNA.',
                  'Beg of him to speak the truth.', "This is because it doesn't.",
                  "And thank God he's dying.",
                  'A shower of dirt fell from the hot pipes.',
                  'Is focalin safer than adderal',
                  'The dusty bench stood by the stone wall.',
                  "It's awfully stupid though.", 'He had a servant with him.',
                  'If you can gain her good will.',
                  'Split the log with a quick, sharp blow.',
                  'I am Ulysses son of Laertes.',
                  'Float the soap on top of the bath water.',
                  'The swineherd brought him.', 'And the company backed down.',
                  'Thetis had offered it as a!', 'Antinous and Eurymachus.',
                  'What is the difference betwee', 'And get me a little sausage.',
                  'I will not conceal it from?',
                  "The facts don't always show who is right.",
                  'Either mud or dust are found at all times.',
                  'He snatched up one of them?', 'The two then started.',
                  'My name is Vrazumihin.', 'Sonia sat down again.',
                  'Unsurprisingly called.', 'But he heeded not my.',
                  'Use one cup of oatmeal.',
                  'Cod is the main business of the north shore.',
                  'The alarm was soon carried.',
                  'Paste can cleanse the most dirty brass.', 'Pyotr Petrovitch went on.',
                  'The juryall brightened up.', "It's worth mentioning again",
                  'This had been made by Ithacus?', 'As for the other five ships.',
                  'A stuffed chair slipped from the moving van.',
                  'And there is this further.', 'Raskolnikov stood waiting.',
                  'Fairy tales should be fun to write.', 'And one has but to suppose.',
                  'I am come back to my own.', 'The tiny girl took off her hat.',
                  'As for this unfortunate.', 'See the cat glaring at the scared mouse.',
                  'Where were they when the noise started.',
                  "Hershey's kisses are named.",
                  'There was a sound of dry leaves outside.',
                  'No estate can stand such.',
                  'Coax a young calf to drink from a bucket.',
                  'A thin stripe runs down the middle.', 'When the couple refused to.',
                  'Still weeping and moaning.', 'Elvis was originally blonde.',
                  'How to pass data from view to', 'And Luzhin got angry.',
                  'Bad nerves are jangled by a door slam.', 'He gave a sudden start.',
                  'Name. Veterans may change the',
                  'The bright lanterns were gay on the dark lawn.',
                  'I will be chief too if I can!', 'He robbed us to get drink.',
                  'It was this that saved us all.', 'But have you noticed.',
                  'In these circumstances', 'The lease ran out in sixteen weeks.',
                  'A cup of sugar makes sweet fudge.',
                  'The rope will bind the seven books at once.',
                  'Nastasya shrieked again.', 'The earth is 4.54 billion.',
                  "I believe it's reality?", 'You are insolent and cruel.',
                  'First find the queen.', 'Ulysses said to Demodocus.',
                  'I can have no desire to go.', 'This service is free.',
                  'He saw the greatness of the Cyclops?', 'Traces of hydrogen sulphide.',
                  'Every word and phrase he speaks is true.',
                  "So theycouldn't get them out.", 'At least is not alive.',
                  'He seems a splendid person.', 'As it is your age shall.',
                  'Are worms and ants closely re', 'There are different types of.',
                  'Or will he go to Ephyra as.', 'The answers may surprise you.',
                  'I wish to ask him some.', 'So the maids went out.',
                  'The bunch of grapes was pressed into wine.',
                  'There are two main names.', 'Can WMA files be converted?',
                  'The pot boiled, but the contents failed to jell.',
                  'I have changed my mind!', 'Send the stuff in a thick paper bag.',
                  'He was very glad of a warm.', 'This we therefore did.',
                  'Once we stood beside the shore.',
                  'The straw nest housed five robins.', 'So she went in search of her.',
                  "Open the crate but don't break the glass.",
                  'But now he has fallen on.', 'I will tell you what he had.',
                  'The pencils have all been used.', 'He asked me to his house.',
                  'Do not try to keep me!',
                  'The crunch of feet in the snow was the only sound.',
                  'We are extremely stern?', 'I will tell you truly!',
                  'Some of them pitied him.',
                  'We talked of the side show in the circus.',
                  'A round mat will cover the dull spot.', 'Poor unhappy stranger.',
                  'I will tell you the real.', 'Do that with a wooden stick.',
                  'O Lord of the Earthquake.', 'The doctor cured him with these pills.',
                  'We therefore summon you!', 'Multiply an entire column.',
                  'First of all, you need...',
                  'The store walls were lined with colored frocks.',
                  'Are pyle tvs any good?',
                  'The man went to the woods to gather sticks.',
                  'There are not ten suitors!', 'Breathe deep and smell the piny air.',
                  'Nine men were hired to dig the ruins.',
                  'Hedge apples may stain your hands green.',
                  'A white silk jacket goes with any shoes.',
                  'You cannot respect Luzhin.', 'SCYLLA AND CHARYBDIS.',
                  'Dull stories make her laugh.', 'At last all was still.',
                  'He seems to have travelled.', 'The crown of humanity.',
                  'Daniel radcliffe was allergic.', 'I want to go home at once.',
                  'All that I have said will.', 'The typical american sees at.',
                  'In the form of pressure waves.', 'rewrite it based on feedback',
                  'A plea for funds seems to come again.',
                  'Cats and dogs each hate the other.', 'Get these things put.',
                  'Then Piraeus came up with.', '000 students take the course.',
                  'It is a good thing for you.', 'I came to consult Teiresias.',
                  'There he chose twelve shields.',
                  'It takes a lot of help to finish these.', 'Pyotr Petrovitch paused.',
                  'and then read it again',
                  'Take the match and strike it against your shoe.',
                  'In these trying circumstances', 'Read just what the meter says.',
                  'Position in the womb.', 'He chose four shields.',
                  'They sang the same tunes at each party.',
                  'Give me your advice therefore.', 'Time brings us many changes.',
                  'And by now he was near.',
                  'Press the pants and sew a button on the vest.',
                  'If you leave these flocks!', 'The game received multiple.',
                  'This was an immeasurable!', 'Take a chance and win a china doll.',
                  'Corn cobs can be used to kindle a fire.', 'He never closed his eyes.',
                  'Set the piece here and say nothing.', 'Eurymachus then said!',
                  'Hercules to his shame killed.', 'The geese are the suitors.',
                  'No estate can stand such?', 'You gave me thirteen pear.',
                  'We therefore summon you.', 'He knew what he was doing.',
                  'There is no man living.', 'If you felt free from guilt.',
                  'Prove the women by all means.', 'Looked out of the window?',
                  'As long as my son was still.', 'If the ancestors of the t.',
                  'I dare not clasp your knees.', 'His name was Eurybates.',
                  'Are andes creme de menthe glu',
                  'Fly by night, and you waste little time.',
                  'It is late morning on the old wall clock.',
                  'Tell me your little notion.', 'The clan gathered on each dull night.',
                  'Glancing at him timidly.', 'She will mix a mess for you?',
                  'Telemus son of Eurymus.', 'Tea served from the brown jug is tasty.',
                  'Get the trust fund to the bank early.', 'Hearing and seeing nothing.',
                  'The price was right, the size', 'You cannot brew tea in a cold pot.',
                  'The petals fall with the next puff of wind.',
                  'If you leave these flocks.',
                  'The sink is the thing in which we pile dishes.',
                  'Not to be themselves.', 'How to change password facebo',
                  'Telemachus went on board.',
                  'Weave the carpet on the right hand side.',
                  'His shirt was clean but one button was gone.',
                  'As long as she was still.', 'Yet grieve for these as I may?',
                  'He took the lead and kept it the whole distance.',
                  'Oats are a food eaten by horse and man.', 'Therefore you shall die!',
                  'Mushrooms and cucumbers.', 'Ulysses killed Demoptolemus.',
                  'Two plus seven is less than ten.',
                  'The store was jammed before the sale could start.',
                  'Help the woman get back to her feet.', 'She was daughter to Dolius!',
                  'He sent me off first.', 'In a controlled environment.',
                  'Use a pencil to write the first draft.',
                  'The stale smell of old beer lingers.',
                  'Flax makes a fine brand of paper.',
                  'The lazy cow lay in the cool grass.', 'These all bit the dust.',
                  'Two blue fish swam in the tank.',
                  'Yell and clap as the curtain slides back.',
                  'Does asurion send you refurbi', 'We like to see clear weather.',
                  'But Mars kept no blind look.', 'It discomfits their enemies?',
                  'The Knave shook his head!', 'Others on the pavement.',
                  '000 devising a new national.', 'Take two shares as a fair profit.',
                  'See how limping Vulcan.', 'Small children came to see him.',
                  'You shall give me a very?', 'Do you remember Luise.',
                  'A thick coat of black paint covered all.',
                  'Place a rosebush near the porch steps.', 'black is never truly black',
                  'You may not believe me.', 'Men strive but seldom get rich.',
                  'This indeed was what.', 'The young girl gave no clear response.',
                  'I am not worthy to love you.',
                  'High seats are best for football fans.',
                  'The seer will presently come.', 'To be at the service.',
                  'I swear by king Jove.', 'Eurymachus then said.',
                  'The fur of cats goes by many names.', 'Let us then get one ready.',
                  'The farm where he grew up.',
                  'The walled town was seized without a fight.',
                  'To make pure ice, you freeze water.', 'If I must include a plot',
                  'So the two stood bandying.', 'What are the requirements to.',
                  'If you were not there.', 'When she had got them into.',
                  'A sullen smile gets few friends.', 'Even though you may yourself?',
                  'And the great geniuses.', 'If he were to come again.',
                  "What's the difference?", 'There are twelve chief men?',
                  'Nestor was astonished.', 'Do not be in a hurry to send.',
                  'Corrected Raskolnikov.', 'The bank pressed for payment of the debt.',
                  'They brought sheep and wine.', 'Still he is younger than you.',
                  'One habit of intelligent!', 'Was it round the point.',
                  'They pulled without flagging!', 'I remembered a minute ago.',
                  'I will nod my head to you.', "This is because it doesn't?",
                  'Plotted something together.',
                  'The swan dive was far short of perfect.', '[message objective]...',
                  'Presently he turned sick!', 'That would be too cunning.',
                  'What brought you here.', 'Leaves turn brown and yellow in the fall.',
                  'A quart of milk is water for the most part.',
                  'Jove the lord of thunder?', 'She was kind to sick old people.',
                  'Ddrinking a lot of water', 'The lawyer tried to lose his case.',
                  'Farmers came in to thresh the oat crop.',
                  'Do whatever you like with him.', 'Do not go out against Ulysses!',
                  'Gray paint stretched for miles around.', 'As the ram was going out.',
                  'When Ulysses got there!',
                  'Let it burn, it gives us warmth and comfort.',
                  'Roads are paved with sticky tar.',
                  'The room was crowded with a wild mob.',
                  'The tube was blown and the tire flat and useless.',
                  'He would not have stirred.', 'Then they sailed away to.',
                  'Crack the walnut with your sharp side teeth.',
                  'I am now safe to perish?', "It's all said and forgiven.",
                  'Steam hissed from the broken valve.',
                  'The last switch cannot be turned off.',
                  'Mud was spattered on the front of his white shirt.',
                  'The latter turned round.', 'The tin box held priceless stones.',
                  'We let the ships run before.', 'It is plain you take after.',
                  'The way to save money is not to spend much.',
                  'The idea is to sew both edges straight.', 'He swam seaward again.',
                  'Along with her came her.', 'He flung off his boots.',
                  'Fate--destiny in particular.', 'Dearth never comes there.',
                  'Settling back in his place.', 'Pale and grave before him.',
                  'We are both Ryazan men.', 'We went up to the garret.',
                  'The fin was sharp and cut the clear water.',
                  'The ripe taste of cheese improves with age.',
                  'He was the son of Nisus.', 'Fine soap saves tender skin.',
                  'She gave me plenty of bread.', 'I was very sorry for him.',
                  'What are Federal laws?', 'Take shelter in this tent, but keep still.',
                  'This is a grand season for hikes on the road.',
                  'They want me to marry again.',
                  'When you hear the bell, come quickly.',
                  'He had on a dirty old shirt.', 'He was trying for the fourth.',
                  'When she reached the suitors.', "A child's wit saved the day for us.",
                  'A thin book fits in the side pocket.',
                  'A big wet stain was on the round carpet.', 'I am full of heaviness.',
                  'Dip the pail once and let it settle.',
                  'They told wild tales to frighten him.', 'When they had made their?',
                  'On that same staircase.', 'Flossing prevents gum disease.',
                  'A baby panda is smaller than.', 'Bottles hold four kinds of rum.',
                  'He has to entertain largely.', 'Experts depend on three bunga',
                  'And they will be here.', 'The cement had dried when he moved it.',
                  'The two met while playing on the sand.',
                  'The lone star flag was active.', 'Penelope laughed when she?',
                  'Iphicles set him at liberty.', 'The leg fell into the bath.',
                  'We dress to suit the weather of most days.',
                  'They took the axe and the saw to the forest.',
                  'Two streams go through it.', 'But he will be very angry.',
                  'The dune rose from the edge of the water.',
                  'Hippos really do have big.', 'Porfiry said amiably.',
                  'I will answer you quite truly.', 'She was running after him.',
                  'Telemachus and his crew.', 'I look with hope upon your.',
                  'Penelope washed her face.', 'Our plans right now are hazy.',
                  'Jove and the other gods know.', 'Would that Apollo would so!',
                  'The little tales they tell are false.', 'Then Helen took her seat.',
                  'There used to be volcanoes.', 'Tend the sheep while the dog wanders.',
                  'He was always very patient?', 'Does UPS ship on Saturday?',
                  'Are there bald superheroes', 'Mentor and Halitherses.',
                  'and on some projectors', 'Hop over the fence and plunge in.',
                  'Pages bound in cloth make a book.', 'Polybus lived in Egyptian.',
                  'One man may be of weak!',
                  'They floated on the raft to sun their white backs.',
                  'A waxed floor makes us lose balance.', 'It poured without ceasing.',
                  'State and local laws apply to', 'This will be much more as it.',
                  'She sat down with it on her.', 'It was insufferably close.',
                  'And though I am a scoundrel.', 'A comet smells like rotten.',
                  'The sun does make a sound.', 'I have suffered much.',
                  'Jove the lord of thunder.', 'flyovers of network graphs',
                  'Slide the tray across the glass top.', 'The fat pigs have to go to.',
                  'Take the ship on to the town.',
                  'The show was a flop from the very start.', 'That his hands trembled.',
                  'I received him hospitably.', 'And did he beat her badly.',
                  'Talks at conferences are', 'See nobody and ask no.',
                  "Here's the gentleman.", 'I will pay you myself.',
                  'If I beg and pray you to set.', "['Tap in the top right corner",
                  'Qualifications and Training',
                  'Carry the pail to the wall and spill it there.',
                  'The theft of the pearl pin was kept secret.',
                  'Press the pedal with your left foot.', 'Let us then be wise in time.',
                  'Stop and stare at the hard working man.', 'I will tell you truly.',
                  'The pennant waved when the wind blew.', 'Ulysses began by saying.',
                  'Drew his greatcoat over him.', 'Octopuses and squids have.',
                  'It was hidden from sight by a mass of leaves and shrubs.',
                  'His body was all swollen.', 'He asked the head clerk.',
                  'They tell me you are his son.', 'The song was copyrighted.',
                  'Then he came back again.', 'The Palais de Cristal.',
                  'Do not aim at him all at once.', 'He is evidently in great.',
                  'The leg fell into the bath!', 'I would have you consider.',
                  'not necessarily accuracy', 'It was all his doing.',
                  'The people wondered as they.', 'A fence cuts through the corner lot.',
                  "Nestor's youngest daughter.", 'If there were meat and wine.',
                  'I have told you the whole.', "Which is the founder's name.",
                  'Neat plans fail without luck.', 'Go now and come here later.',
                  'Here Ulysses lay down.', 'So we asked heaven for a sign!',
                  'You must have studied under!', 'You were beside yourself!',
                  'The houses are built of red clay bricks.',
                  'The square peg will settle in the round hole.',
                  'And that when I have money.', 'Nestor gave out the gold.',
                  'He sent the boy on a short errand.',
                  'The desk and both chairs were painted tan.',
                  'Show me the way to your town.', 'You swaggering bully.',
                  'Is "wyrd" in the dictionary?',
                  'Clothes and lodging are free to new men.',
                  'One australian cattle dog.', 'There was a prophet here.',
                  'The term ended in late June that year.',
                  'Zossimov testifies to that.', 'I sent him on with my crew.',
                  'Bring your best compass to the third class.',
                  'You have had your supper.', 'Let me have twelve jars.',
                  'Throw out the used paper cup and plate.',
                  'These thistles bend in a high wind.',
                  'Fake stones shine but cost little.', 'I am now safe to perish.',
                  'I would insist as follows.', 'A filing case is now hard to buy.',
                  'Shake hands with this friendly child.',
                  'The fight will end in just six minutes.',
                  'The birch canoe slid on the smooth planks.',
                  'Ulysses fell into a deep.',
                  'The sky that morning was clear and bright blue.',
                  'A man in a blue sweater sat at the desk.',
                  'He said the same phrase thirty times.',
                  'The work of the tailor is seen on each side.',
                  'They are great sailors.', 'If he is still at home.',
                  'Shrieking and wailing.', 'The big red apple fell to the ground.',
                  'He lay prone and hardly moved a limb.',
                  'Drop the two when you add the figures.',
                  'I will show you the way to.', 'I think thatwill be the best?',
                  'Thither presently came also.', 'No stifling closeness.',
                  'He would put me in prison.', 'I would have you consider?',
                  'In the meantime I will go to.', "Plankton's computer wife.",
                  'The first worm gets snapped early.',
                  'The poor boy missed the boat again.', 'The soul is retrograde.',
                  'Very much absorbed him!', 'THE CATTLE OF THE SUN.',
                  'Ten pins were set in order.', 'There was a dead silence?',
                  'The beach is dry and shallow at low tide.',
                  'Take great care of them.',
                  'Port is a strong wine with a smoky taste.',
                  'A gold ring will please most any girl.',
                  'A salt pickle tastes fine with ham.', 'He thought gleefully.',
                  'A fur muff is stylish once more.', 'Why does my left side of my s',
                  'Add salt before you fry the egg.', 'I too was a rich man once.',
                  'Much of the story makes good sense.',
                  'In the form of pressure waves!', 'Even a Geek Can Speak',
                  'Tea in thin china has a sweet taste.',
                  'Dunk the stale biscuits into strong drink.',
                  'He was in a furious passion.', 'But Agelaus shouted out.',
                  'You must have studied under.',
                  'Help the weak to preserve their strength.',
                  'First they carried the dead.', 'I will stay somewhere here.',
                  'Phylo now placed this by her.', 'What joy there is in living.',
                  'The purple tie was ten years old.', 'Looking at the faces.',
                  "The copper bowl shone in the sun's rays.",
                  'Smoky fires lack flame and heat.',
                  'The clothes dried on a thin wooden rack.', 'And not ask forgiveness!',
                  'Who is imf chief economist?', 'He asks you to wait till!',
                  'Boards will warp unless kept dry.', 'I filled a large skin with?',
                  'Forgets an army in Egypt.',
                  'He carved a head from the round block of marble.',
                  'As soon as possible, pump 8-1', 'When she began to suck again.',
                  'A lathe cuts and trims any wood.', 'Here we landed to take in?',
                  'Leave now and you will arrive on time.', 'Moving with my uncle.',
                  'It contains two communities?', 'Just hoist it up and take it away.',
                  'Computer and Information', 'He has sent me to call you?',
                  'The leaf drifts along with a slow spin.',
                  'There is an island called.', 'Lasting over 680 years.',
                  'We admire and love a good cook.', 'Have a try therefore at.',
                  'Never thought of them.', 'Even a just cause needs power to win.',
                  'All that I have said will!', 'Forgotten it all at once.',
                  'The jacket hung on the back of the wide chair.',
                  'Do not try to keep me.', 'The blind man counted his old coins.',
                  'He could not have said why.', 'The stranger is quite.',
                  'It was this that saved us all!', 'It held a dove in its talons!',
                  "'Enable Boot to Network.'", 'He could not repress it.',
                  'Alice felt dreadfully puzzled.',
                  'The clock struck to mark the third period.',
                  'Pyotr Petrovitch put in.', "It's a way out of it.",
                  'You ill conditioned cur.', 'His wide grin earned many friends.',
                  'Is the freezer in the fridge?',
                  "Let's all join as we sing the last chorus.",
                  'The music played on while they talked.',
                  'The doorknob was made of bright clean brass.',
                  'At night the alarm roused him from a deep sleep.',
                  'The box was thrown beside the parked truck.',
                  'Mauna kea and mauna loa in.', 'When they had done so.',
                  'He was a horrid creature.', 'Give me something to drink.',
                  'The plush chair leaned against the wall.',
                  "Nestor's youngest daughter!", 'I do not like it myself.',
                  'We went to Pylos and saw.', 'Here we landed to take in.',
                  'His heart growled within him.', 'A fridge is where you place i',
                  'As he mixed the wine.', 'Our troops are set to strike heavy blows.',
                  'Arete was the first to speak.',
                  'The line where the edges join was clean.', 'Presently he said to.',
                  'The long journey home took a year.', 'All that you have been saying.',
                  'If you point your car keys.',
                  "We don't get much money but we have fun.",
                  'He was waiting for Sonia!',
                  'Find the twin who stole the pearl necklace.',
                  'I do not wish to drive any?', "You can't bear a slight.",
                  'Pepsi responded by notifying.', 'The bill was paid every third week.',
                  'He wrote down a long list of items.',
                  'Green moss grows on the northern side.',
                  'I do not know how to begin.',
                  'The vamp of the shoe had a gold buckle.',
                  'Drop the ashes on the worn old rug.', "you're going too fast",
                  'Slide the catch back and open the desk.', 'We ran away in a fright.',
                  'The cleat sank deeply into the soft turf.',
                  'The early phase of life moves fast.', 'And you are correct, there is',
                  'Sever the twine with a quick snip of the knife.',
                  'If you choose to take.', 'Carbs: 35 grams. Fiber: 11 gr',
                  'Guess the results from the first scores.',
                  'The nag pulled the frail cart along.', 'Who beat the landlady.',
                  'A sip of tea revives his tired friend.', 'You seem to be a sensible.',
                  'Are brains similar to feet?', 'A rag will soak up spilled water.',
                  'Dragged about by his hair!', 'When they saw it they were.',
                  'The wall phone rang loud and often.',
                  'They can live up to two years.', 'He looked round hurriedly.',
                  'That guy is the writer of a few banned books.',
                  'He had an allergy to nickel.', 'If he is still at home!',
                  'The key you designed will fit the lock.', 'U.S. citizens traveling.',
                  'Do the alps always have snow?', 'His son was astounded when.',
                  'The only resident is a woman.',
                  'The girl at the booth sold fifty bonds.',
                  'This had been made by Ithacus.',
                  'The wrist was badly strained and hung limp.',
                  'It is long and difficult.', 'Do they know about the flat.',
                  'There he lay in his bed till.', "He didn't even look at him.",
                  'A strong bid may scare your partner stiff.',
                  'A sash of gold silk will trim her dress.', 'He doubted whether to.',
                  'This horse will nose his way to the finish.', "You wouldn't believe.",
                  'Protect these my goods.', 'Increased species richness do',
                  'Nastasya scrutinised him.', 'He was glad enough to see.',
                  "Cheap clothes are flashy but don't last.",
                  'She flaps her cape as she parades the street.',
                  'He ordered peach pie with ice cream.', 'They trembled all over.',
                  'Twist the valve and release hot steam.',
                  'No hardship seemed to keep him sad.',
                  'The urge to write short stories is rare.', 'And dropped her eyes.',
                  'My husband foresaw it all.', 'This will slow you down',
                  'The wide road shimmered in the hot sun.', 'This never leaves it.',
                  'Nine rows of soldiers stood in line.',
                  'The lake sparkled in the red hot sun.', 'But I know what I will do.',
                  'Hurdle the pit with the aid of a long pole.',
                  "Dig deep in the earth for pirate's gold.",
                  'Jerk the dart from the cork target.', 'Too. all mammals get.',
                  'An upper servant brought.', "I've known this peasant.",
                  'The new girl was fired today at noon.', 'The ten highest mountain.',
                  'It would be a long story.', 'Going off into a giggle.',
                  'As the dun nightingale.', 'Fish evade the net and swim off.',
                  'The water in this well is a source of good health.',
                  'The map had an X that meant nothing.',
                  'When your hair stands on end.', 'Why had he never expected.',
                  'It makes me furious to look.',
                  'Hats are worn to tea and not to dinner.',
                  'The odor of spring makes young hearts jump.',
                  'One man may be of weak.', 'Watch the log float in the wide river.',
                  'It poured without ceasing?', 'Later on Menelaus joined us.',
                  'The fan whirled its round blades softly.', 'On this Amphinomus said.',
                  'which may build anticipation', 'Mend the coat before you go out.',
                  'We are your own children!', 'I will gild her horns.',
                  'It caught its hind paw in a rusty trap.',
                  'Grape juice and water mix well.', 'As she vomited it up.',
                  'And not ask forgiveness.', 'Even though you may yourself.',
                  "The beam dropped down on the workmen's head.",
                  'I do not so much care.', 'Dare devil that you are.',
                  "An apology can't be used?",
                  'Breakfast buns are fine with a hot drink.',
                  'Presently the crew came up.', 'He graduated in may 2017.',
                  'You killed many a man.', '6 mg is how many milliliters?',
                  'No cement will hold hard wood.', 'Preparing for a competition t',
                  'Now that Ulysses is revenged.',
                  'The office paint was a dull, sad tan.',
                  'All that day did they travel.',
                  'The rush for funds reached its peak Tuesday.',
                  'Thus piteously did they weep.', 'Performance enhancing drugs',
                  'She also gave him a sharp.', 'She sewed the torn coat quite neatly.',
                  'Five years he lived with a shaggy dog.',
                  'Pack the records in a neat thin case.',
                  'The knife was hung inside its bright sheath.',
                  'For six days I and my men.',
                  'Kick the ball straight and follow through.', 'Telemachus Amphimedon.',
                  'What is supply chain manageme', 'Agelaus was the first to.',
                  'He put his last cartridge into the gun and fired.',
                  'At this moment Eteoneus.', 'But does water really help?',
                  'The vast space stretched into the far distance.',
                  'Live wires should be kept covered.', 'He took nothing by it.',
                  'The best method is to fix it in place with clips.',
                  'But let us say no more about.',
                  'The crooked maze failed to fool the mouse.',
                  'The steady drip is worse than a drenching rain.',
                  'Go through their posts,', 'I went security for you.',
                  'Add the sum to the product of these three.',
                  'Pyotr Petrovitch replied.', 'These pills do less good than others.',
                  'Like being kept as a pet.', 'What is one significant diffe',
                  'A king ruled the state in the early days.',
                  'Mesh wire keeps chicks inside.', 'As though suddenly cut off!',
                  'I was already disposed to?', 'The suitors were dismayed.',
                  'She flew weeping to his side!',
                  'Prod the old mule with a crooked stick.',
                  'Simply for my own personal.',
                  'A steep trail is painful for our feet.',
                  'Thereon Circe came up to me.', 'A blue crane is a tall wading bird.',
                  'The wagon moved on well oiled wheels.',
                  'A tusk is used to make costly gifts.', 'She understands the man.',
                  'Nobody else attended.', 'She is very feeble now?',
                  'Do not go out against Ulysses.', 'They may stay till morning.',
                  'The pup jerked the leash as he saw a feline shape.',
                  'The sense of smell is better than that of touch.',
                  'If this does not please you.', 'So you have got back.',
                  'From that moment I saw them.', 'Where have you been wandering.',
                  'Write fast if you want to finish early.',
                  'Is Himalayan pink salt dyed?', 'I will do you all the harm I.',
                  'The hilt of the sword was carved with fine designs.',
                  'I have come here with my.',
                  'Pour the stew from the pot into the plate.',
                  'An abrupt start does not win the prize.',
                  'She has a smart way of wearing clothes.',
                  'They were quickly replaced.', 'I was already disposed to.',
                  'The tree top waved in a graceful way.', "That's the porter's voice.",
                  'This three years past.', 'They are very fond of one.',
                  'Torn scraps littered the stone floor.',
                  'The lobes of her ears were pierced to hold rings.',
                  'Whitings are small fish caught in nets.',
                  'That he had had yesterday.', 'The hat brim was wide and too droopy.',
                  'I will therefore tell you.', 'Ducks fly north but lack a compass.',
                  'Tin cans are absent from store shelves.',
                  'Fruit flavors are used in fizz drinks.', 'Are there any animals?',
                  'This latest Volkswagen', 'He ran half way to the hardware store.',
                  "It's not supposed to exist.", "I live in Shil's house.",
                  'Heaven forbid that I should?', 'I see the likeness just as?',
                  "Add the store's account to the last cent.",
                  'From everything together.', 'Never mind about him.',
                  'No doubt about the way the wind blows.',
                  'I have neither ship nor crew.', 'As bacteria are so light.',
                  'Presently he said to!', 'Ulysses hit Eurydamas.',
                  'Ship maps are different from those for planes.',
                  'Observed Raskolnikov!', 'But the unofficial flag.',
                  'The child crawled into the dense grass.', 'The younger one asked.',
                  'Dimes showered down from all sides.',
                  'Both brothers wear the same size.', 'Morning will come in due.',
                  'That was five weeks ago.',
                  'The cup cracked and spilled its contents.',
                  'The mighty contest is at an.', 'Raskolnikov shuddered.',
                  'A rich farm is rare in this sandy waste.',
                  'The coffee stand is too high for the couch.',
                  'The man who made that belt.', 'I am sure you must be.',
                  'The sand drifts over the sill of the old house.',
                  'Trees would immediately fall.',
                  'The ship was torn apart on the sharp reef.',
                  'We are your own children.',
                  'Wood is best for making toys and blocks.',
                  'But he gave way to cards.', 'The frosty air passed through the coat.',
                  'How do i change my name at th', 'Possibly afraid of their own.',
                  'you should always practice', 'Gita Gopinath is the professo',
                  'When we reached the sea shore.',
                  'The boy was there when the sun rose.',
                  'This will lead the world to more sound and fury.',
                  'So they had tofall a long way.', 'Then draw your sword and sit!',
                  'Code is used when secrets are sent.',
                  'Hold the hammer near the end to drive the nail.',
                  'King Neptune watched him as.',
                  'The desk was firm on the shaky floor.',
                  'Many hands help get the job done.', 'Turned down the passage.',
                  'You shall give me a very.', 'He was sitting apart.',
                  'We did not get on much?', 'Corrected Raskolnikov!']
