short_sentences = ['Of course.', 'Leave me in peace!', 'I am afraid.', 'In a technical talk', "But by God's mercy.",
                   'He felt the change.', 'Or else Crevez.', 'Tell her tobegin!', 'You must know.', "What's the slope?",
                   'If you can.', 'love thy neighbour.', 'I wish Father Jove.', 'And not from fear.', 'small workshops',
                   'It is excluded.', 'He shouted.', 'Not that your wife.', 'As for yourselves.', "She'll gallop.",
                   'Fully penitent.', 'So he at once said.', "Jove's daughter.", 'My darling.', 'I said to my men.',
                   'Gazing after him?', 'Fool that he was.', "Don't be impudent.", 'Tell her tobegin.',
                   'What are they doing.', 'Hunting big game!', 'Practice makes more', 'Traces indeed.',
                   'Burning matches.', 'His eyes glowed.', 'Suddenly he started.', 'One less to keep?',
                   'You can smell ants?', 'And his wife.', 'Alice was silent.', 'I should think so.',
                   'When you exercise.', 'Even as wax melteth.', 'He continued.', 'Come sit down.',
                   'Probing her further.', 'As for the stranger.', 'In this type of talk', 'Yet if you like.',
                   'As regards mortals.', 'Addressing Zossimov.', 'Hunting big game.', 'Only to get it over.',
                   'South Africa', 'Now I have been ill?', 'How they push.', 'Father Eumaeus.', 'United Kingdom',
                   'How can i get copy?', 'What do you think.', 'Another must go to.', 'During that time.',
                   'Mad besides.', 'How much water?', 'Why was he here.', 'She came up to me.', 'If they question me.',
                   'If you can?', 'Goodness knows why.', ' he muttered.', 'He got him there.', 'It could come soon.',
                   'Bring me sulphur!', 'Ask a question', 'To smaller animals.', 'He passed him by.', 'Why do you go.',
                   'Put in Raskolnikov.', 'Most importantly', 'Quite right.', 'It was now daylight.',
                   'Strike me openly.', 'Observed Zametov.', 'She took his shape.', 'But with sour sugar.',
                   'The root was black.', 'He stood still.', 'To be sure?', 'I then bored a hole?', 'And I charge you.',
                   ' what came of it?', 'Great Goddess Diana?', 'Dmitri Prokofitch?', 'Obtain feedback',
                   'You must admit that.', 'Ulysses saw her.', 'Semyon Zaharovitch.', 'Not a commonplace?',
                   ' what came of it.', 'Wake up Pisistratus.', "I don't want.", "Don't be too sure.",
                   'Father stranger.', 'There I saw Helen.', 'What do you say.', 'You can smell ants.',
                   'There he married.', 'Leave me in peace.', "Apollo's messenger.", 'In a conference talk',
                   'Have you met before.', "That's enough.", 'After the talk', 'Sulphur dioxide?', 'Be off with you!',
                   'How do you mean.', 'drawing people in', 'Considerate even?', 'He answered dryly.',
                   'I am in great want.', 'As you say.', 'I am also stronger.', 'Gazing after him.',
                   ' I should think so.', 'Is perfectly true.', 'And only fancy.', 'And rang at No.',
                   'With many kisses.', 'Generally speaking', 'Be off with you.', 'Now another point.',
                   'What a misfortune.', "You're a loose fish?", "D'you hear.", 'Do you know.', 'Then Euryalus said.',
                   'It is tyranny?', 'A good old woman.', 'Has a cleft palate.', 'Do you hear?', 'Without opening it.',
                   'Calypso went home.', 'While blessings.', 'His old thoughts.', 'That I know.', 'Use vocal energy',
                   " 'I was frightened.", 'Let me persuade you.', 'O swineherd Eumaeus?', 'Bring in the parcel.',
                   'conference talks', 'About my mother?', 'For instance.', "I'll be bound.", 'And his hometown.',
                   'Tell me also truly.', 'You are a one.', 'And he is my friend.', 'The sly dog.', 'Remember that',
                   'Believe me.', 'Mumbled Zossimov.', 'More simply.', 'meet new people', 'You country louts.',
                   "they won't do it", 'But Vrazumihin.', 'Relax and have fun', 'Light of my eyes!',
                   'This further grief.', 'He had not the axe.', 'As for Telemachus.', "Nastasya's with him.",
                   'Here was the gate.', 'So here you are.', 'All out of sight.', "You're a loose fish.",
                   'The hobbit has been.', "I don't want!", 'At that very hour.', "He'll kill her.",
                   'He showed you too?', "I've no boots.", 'Telemachus Euryades.', 'What do you want.',
                   'Cried Raskolnikov.', 'Why do you keep on.', 'Not only that.', 'Dounia and I.', 'He knows me?',
                   'Confound you then.', 'Our one hope.', 'That is to say.', "That's a sin.", 'The mules drew well.',
                   'Bring me sulphur.', 'Is it possible.', 'He was so kind.', 'what the axes mean', 'Matryoshka Dolls',
                   'Allow me to observe.', 'Is not the meanness.', 'So big and dense.', "For God's sake.",
                   'He asked suddenly.', 'What endurance too.', "'Press F10 to save'", 'You are forgetting.',
                   'beware the projector', 'But not killed.', 'Semyon Zaharovitch!', 'It is not right.',
                   'And mocked at him?', 'I shall never.', 'You are forgetting!', "You'd be sure to.", 'He is injured.',
                   'Rex probably did.', 'If these Achaeans.', 'We have suffered?', 'She was howling.',
                   'The twin volcanoes.', 'Burkina Faso', 'Blinking eyelashes.', 'In these cases', 'I noticed that.',
                   'My dear father.', "But we'll see.", 'As for your voyage.', "Therefore I'm mad.",
                   'Sail night and day!', 'But my dear nurse.', 'She added.', 'He is an Egyptian.', 'He embraced him.',
                   'He muttered!', "It's strange though.", 'Cigarette case.', 'Opened her mouth.',
                   'Are fajitas Mexican?', 'For instance!', 'Pear grows on pear.', 'Well and what then.',
                   'Then a third man.', 'Than with them.', 'Nothing of the sort.', 'He will forgive.',
                   'On this Polites.', 'She must be forty.', 'He thought?', 'And cause headaches.',
                   ' Razumihin insisted.', 'United States', 'She is an angel.', 'He is very rich.', 'To be sure.',
                   'Winds from East.', 'Here he is himself.', 'And mocked at him.', 'You are harsh.',
                   'love thy neighbour?', 'No reason to.', 'I find that black', 'The devil.', "But we'll see!",
                   'Is epsom salt good?', 'THE LAESTRYGONES.', 'He turned round.', "Therefore I'm mad!",
                   'Not far from here.', 'As for the boar.', 'As for yourself.', 'Give him his helmet.',
                   'Presently she said.', 'I am a student.', 'Telemachus wept.', 'Immense experience.',
                   'Sail night and day.', 'Not Razumihin.', 'Hurriedly dressing.', 'For nearly 60 years.',
                   'This means that.', 'Not a commonplace.', 'Now I have been ill.', 'Just what I thought.',
                   'As for the day time.', 'So I lost my temper.', 'It is despotism.', 'But not killed!',
                   'She cried to him.', "I don't know.", 'And a dirty one.', 'Mumbled Zossimov?', 'Just our friends?',
                   'South Sudan', 'Asked the waiter.', 'A friend of mine.', 'And the purse too.', 'Very good.',
                   'Only to get it over?', 'Razumihin agreed.', 'Do you hear.', 'Find collaborators',
                   'Wake up Penelope.', 'As for the suitors.', 'And so long ago.', "It's impossible.",
                   'She is mistrustful.', 'They do not breed.', 'The sly dog!', "It's my property.",
                   'The doors were gold.', 'My darling?', 'I am in great want?', 'Light of my eyes.', 'the main result',
                   'Like a leaf?', 'I am no prophet.', 'Tell an anecdote', 'The idea struck him.', 'To my horror?',
                   'He is very rich?', 'Just our friends.', 'One less to keep.', 'What does this mean.',
                   'He cried again.', 'Do you have to?', 'Blinking eyelashes!', 'My heart is beating.',
                   'At your service.', 'About This Article:', 'My poor unhappy man.', "I'll show you.",
                   'Papua New Guinea', 'Like a leaf.', 'As for your own end.', 'He answered.', 'Tell me then truly.',
                   'More loudly.', 'Gilberto Baschiera!', 'He let go the helm.', 'I am still strong.', 'Has no will.',
                   'Why did I add that.', 'Wretched creature.', 'In other words,', 'This is the point.', 'The student.',
                   'practice some more', 'Farewell stranger.', 'Ask your father.', 'But now tell me.',
                   'She held a veil.', "You've heard that.", 'Unstable Wi-Fi', "But don't mind me.", 'Not only that!',
                   'Man in general.', 'To my horror.', 'And sat down again?', 'working meetings', 'But heavens.',
                   'Let us be going.', 'Go to hell then.', 'Just now.', 'After scanning Mr.', 'They threatened him.',
                   'and your institution', 'It is tyranny.', 'He knew me and said.', 'He was overwhelmed.',
                   'There is no one.', 'We have suffered.', 'I want to get home?', 'I want to get home.',
                   'Am I not a goddess.', 'Neither his mother!', 'Ulysses himself.', 'Asked Razumihin.', 'More simply!',
                   ' I would say.', 'Formerly a student.', 'What does it mean?', 'I went to Cyprus.',
                   'Death and despair.', 'I remember.', 'She bore Nestor.', 'Would you believe.', 'Coming here.',
                   'And proved it.', 'But she stopped!', 'I will put bread.', 'When Marmeladov.', "D'you hear!",
                   'Volume adds emphasis', 'Who was listening?', 'And say nothing.', 'Their messenger!',
                   'And sat down again.', 'As much as I liked.', 'Why the word ought.', 'Leave off doing so.',
                   'Turn a little.', "Cote d'Ivoire", 'Dmitri Prokofitch.', 'All the time.', 'His head ached less.',
                   'and how to read it', 'Without hurry.', "Don't you mind her.", 'Impudent baggage.',
                   'We must lock up.', 'Have mercy upon me.', 'Life is real.', 'Who was listening.',
                   'Grinding his teeth.', 'Sitting up again.', 'I have already told.', 'Not to be beaten.',
                   'Here was his house.', 'Wearing a full.', 'You precious idiot.', 'Well and what then!',
                   'She cried to him?', 'This is your case!', 'She must be forty!', 'Furthermore I say.',
                   'and design elements', 'Give him the bow.', 'I know all about it.', 'All that time.',
                   'You will be unhappy.', 'Give it to her.', 'But he went on.', 'This god appeared.',
                   'Yesterday Zametov.', 'Stay where you are?', 'It is very possible.', 'When he was.', 'About 300,000',
                   'He is Egyptian.', 'She added!', 'Speed can energize', 'Queen Penelope.', 'I was all dismayed.',
                   'Began Zossimov.', 'I am not sure.', 'Scaling this up to.', 'All right.', 'He thought.',
                   'Known as moonquakes.', 'Considerate even.', 'He went on gaily.', 'If you were their.',
                   ' Razumihin insisted!', 'I only wanted.', ' and so on.', 'The sun was now set.', 'What can you do?',
                   'It was a disgrace.', 'New Zealand', 'As for my escort.', 'Order in person!', 'Strange to say.',
                   'Third class.', 'This is serious.', 'Heaven help me.', 'He wore spectacles.', 'I besought her aid.',
                   'But I prevented him.', 'What am I to do.', 'I wish Father Jove?', '7 million dollars?',
                   'Messenger Mercury.', 'You are tired.', 'You are our all.', 'How many carbs?', 'In this grey house.',
                   'Nikolay Dementyev.', 'I began to jeer.', 'The drunkard.', 'Neither his mother.',
                   'They meant no guile.', 'She is only a woman.', 'Silent and frowning.', 'Here was the house?',
                   "It's like a tomb.", 'Night was coming on.', 'What do you mean.', 'Muttered to himself.',
                   'Good heavens.', 'And I ran after him.', 'Flat Number 14.', 'Come along.', 'To be depended upon.',
                   'You may kill me!', 'Excuse my saying so.', 'Raised his head.', 'You were wrong.',
                   'Like one distraught.', "That's what's bad.", 'Then I said to them.', "That's very natural.",
                   'Meanwhile Ulysses.', 'They had just left.', 'What am I to do now.', 'As for Telemachus?',
                   'But come inside.', 'Exaggerating it all.', 'We are neighbours.', 'Then he got up.',
                   "Don't be impudent?", 'After the wedding.', 'He knows me.', 'No mistake about it.',
                   'O swineherd Eumaeus.', 'Our one stay.', 'She is a quick girl.', 'Coming forward.',
                   "She'll jog along.", 'You are not asleep.', 'Then they cut it up.', ' he muttered?',
                   'Pear grows on pear!', 'The cheapest.', 'If I were told.', 'It made me ill.', 'He was pale.',
                   'She was beseeching.', 'I am sorry for him.', 'What are you saying.', 'Along that theme.',
                   'Warm gratitude.', 'Sulphur dioxide.', 'Bear everything.', 'But Ulysses said.',
                   'Then Antinous said.', 'More than that.', 'Where are you going.', 'Exaggerating it all?',
                   'This smartness.', "That's evident.", 'Saudi Arabia', 'We are just here.', 'Again the hospital.',
                   "That's very natural?", 'But for that.', 'How strange it was.', ' Do you hear.', 'I had nine ships.',
                   'I would obey you.', 'Let us then be off.', 'Poor gentle things.', 'When he got back.',
                   'Or as a blind.', 'Grinding his teeth!', 'What was I saying.', 'Good luck to you.',
                   'Bless my heart.', 'You filthy glutton.', 'You may amuse him.', 'They had separated.',
                   'Here was the house.', 'How Many ML Is 6 MG?', 'Fajita is a Tex-Mex.', 'An italian banker.',
                   'Martin, an island', 'Am I not a goddess!', 'Rex had feathers.', 'With gentle eyes.',
                   'Roused himself.', 'This is the point?', 'But she stopped.', 'She bore Nestor?', 'Another thought.',
                   'Almost physical.', "And I'm sick of it.", 'The hopelessness.', 'Ten minutes passed.',
                   "At two o'clock.", 'And so at all costs.', 'Death and despair?', 'Get you to your bed.',
                   'Stay where you are.', 'Ask the porter.', 'Eggs are rich.', 'To Razumihin.', 'Ajax was wrecked.',
                   'This is your case.', 'Then bring it to me.', 'May visit you also.', 'My dear boy.', 'In vexation.',
                   'Known as moonquakes?', 'He muttered.', 'You are right.', 'if all else fails', 'From a child.',
                   'The twin volcanoes!', 'She is afraid.', 'An obstinate.', 'Let my life go.', 'Her name is Arete.',
                   'A good old woman!', 'Their messenger.', 'I come from Alybas.', 'North Korea', 'We become casuists.',
                   'Queen Penelope!', 'O swineherd Eumaeus!', 'Gallop indeed.', 'I knew all about it.',
                   'Are you still here.', 'About my mother.', 'Tit Vassilitch.', 'I shall say no more.',
                   'German women.']
